// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - TanStack devtools (dev-only, first), tanstackStart, viteReact, tailwindcss, tsConfigPaths,
//     nitro (build-only), VITE_* env injection, @ path alias,
//     React/TanStack dedupe, error logger plugins, and sandbox detection (port/host/strictPort).
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

export default defineConfig({
  // cPanel serves .output/public directly from public_html.
  // The production build uses root-relative /assets/... URLs, so assets remain
  // valid when a prerendered HTML file is opened at any public route.
  tanstackStart: {
    server: { entry: "server" },
  },
  // MySkyParcel production runtime is cPanel + Passenger + Nitro node-server.
  // Public route HTML is generated by the CI smoke server after the Nitro build;
  // this avoids the TanStack preview-prerenderer expecting a legacy dist/server.js
  // path that this Nitro build does not produce.
  nitro: {
    preset: "node-server",
  },
});
