import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Boxes, Check, Globe, Headphones, Layers, Lock, Play, ShieldCheck, Sparkles } from "lucide-react";
import { useState, type FormEvent } from "react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { TrustBar } from "@/components/TrustBar";
import { CertificateTemplatePreview } from "@/components/CertificateTemplatePreview";
import { CITY_IMAGES } from "@/lib/cityImages";

export const Route = createFileRoute("/ana-sayfa")({ head: () => ({ meta: [{ title: "MySkyParcel — Gökyüzünde Sana Özel Sembolik Bir Yer" }, { name: "description", content: "81 il ve 81 milyon benzersiz gökyüzü parseli fikri." }] }), component: Index });
const SKY_PARCEL_MODEL = { cityCount: 81, layersPerCity: 10, sectorsPerCity: 1_000, parcelsPerCity: 1_000_000, totalParcels: 81_000_000 } as const;
const STATS = [{ icon: Globe, big: "81 MİLYON", title: "TOPLAM GÖKYÜZÜ PARSELİ", text: "81 il × 1.000.000 parsel uzun vadeli hedef" }, { icon: Layers, big: "10", title: "KATMAN / İL", text: "Her il için 10 katman" }, { icon: ShieldCheck, big: "1.000", title: "SEKTÖR / İL", text: "Her il için 1.000 sektör" }, { icon: Boxes, big: "1.000.000", title: "PARSEL / İL", text: "Her il için 1.000.000 parsel" }, { icon: Headphones, big: "DESTEK", title: "DESTEK EKİBİ", text: "İletişim kanalları üzerinden bize ulaşabilirsiniz" }, { icon: Lock, big: "", title: "GÜVENLİ ALTYAPI", text: "Güvenlik ve ödeme altyapısı ayrıca doğrulanmalıdır" }];
const CERTIFICATE_PACKAGES = [
  { id: "digital", name: "DİJİTAL PARSEL SERTİFİKA", price: 149, features: ["Dijital sertifika", "Parsel kodu ve kayıt bilgileri"] },
  { id: "elite", name: "ÖZEL PARSEL SERTİFİKA", price: 349, features: ["Özel tasarım sertifika", "A4 fiziksel baskı", "Dijital sertifika"] },
  { id: "premium", name: "PREMİUM PARSEL SERTİFİKA", price: 699, features: ["Premium tasarım sertifika", "Çerçeveli baskı", "Dijital sertifika"] },
] as const;
const POPULAR_CITIES = [{ name: "İSTANBUL", slug: "istanbul", code: "IST", image: CITY_IMAGES.IST }, { name: "ANKARA", slug: "ankara", code: "ANK", image: CITY_IMAGES.ANK }, { name: "İZMİR", slug: "izmir", code: "IZM", image: CITY_IMAGES.IZM }, { name: "ANTALYA", slug: "antalya", code: "ANT", image: CITY_IMAGES.ANT }, { name: "BURSA", slug: "bursa", code: "BUR", image: CITY_IMAGES.BUR }, { name: "KAYSERİ", slug: "kayseri", code: "KAY", image: CITY_IMAGES.KAY }, { name: "GAZİANTEP", slug: "gaziantep", code: "GZT", image: CITY_IMAGES.GZT }] as const;

function Index() {
  const navigate = useNavigate();
  const [certificateCode, setCertificateCode] = useState("");
  const parcelModelCheck = SKY_PARCEL_MODEL.cityCount * SKY_PARCEL_MODEL.parcelsPerCity === SKY_PARCEL_MODEL.totalParcels;
  function handleCertificateSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); navigate({ to: "/sertifika-dogrula", search: { code: certificateCode.trim() } }); }
  return <div className="ana-sayfa relative isolate min-h-screen overflow-x-hidden bg-slate-50 text-slate-900">
    <SiteHeader variant="light-bg" />
    <main className="relative z-10">
      <section className="relative isolate min-h-[312px] overflow-hidden sm:min-h-[344px] lg:min-h-[376px]">
        <img src="/hero-background.jpg" alt="MySkyParcel gökyüzü" className="pointer-events-none absolute inset-0 -z-10 h-full w-full object-cover" />
        <div className="pointer-events-none absolute inset-0 -z-[5] bg-white/10" />
        <div className="relative z-10 mx-auto max-w-[1600px] px-4 py-4 sm:py-5 lg:px-8">
          <div className="min-w-0 max-w-3xl rounded-2xl bg-white/10 p-3 backdrop-blur-[2px] sm:p-4">
            <span className="inline-block max-w-full rounded-md border border-amber-700/50 bg-white/45 px-3 py-1 text-[8px] leading-4 tracking-[0.1em] text-slate-900 shadow-sm backdrop-blur-md sm:px-4 sm:text-[9px]">HER İL İÇİN {SKY_PARCEL_MODEL.layersPerCity} KATMAN · {SKY_PARCEL_MODEL.sectorsPerCity.toLocaleString("tr-TR")} SEKTÖR · {SKY_PARCEL_MODEL.parcelsPerCity.toLocaleString("tr-TR")} PARSEL<br /><strong>TOPLAM {SKY_PARCEL_MODEL.totalParcels.toLocaleString("tr-TR")} GÖKYÜZÜ PARSELİ</strong></span>
            <h1 className="mt-2 break-words font-display text-3xl font-bold leading-[1.05] tracking-tight text-slate-950 drop-shadow-sm sm:text-4xl lg:text-5xl">GÖKYÜZÜNDE<br /><span className="text-amber-700">SANA ÖZEL</span><br />SEMBOLİK BİR YER</h1>
            <p className="mt-2 max-w-lg text-xs font-semibold leading-5 text-slate-900 drop-shadow-sm sm:text-sm">MySkyParcel ile gökyüzünde sana özel bir parsel seçebilir, benzersiz sertifikanla bu anı ölümsüzleştirebilirsin.</p>
            <div className="mt-2 flex max-w-full flex-wrap gap-2"><Link to="/turkiye-haritasi" className="inline-flex max-w-full items-center gap-2 rounded-md bg-amber-600 px-4 py-2 text-[10px] font-bold text-white shadow-lg transition hover:bg-amber-700 sm:px-5 sm:text-xs"><Sparkles className="h-4 w-4 shrink-0" /> GÖKYÜZÜ HARİTASINA GİT</Link><button type="button" disabled className="inline-flex items-center gap-2 rounded-md border border-slate-700/40 bg-white/45 px-4 py-2 text-[10px] font-semibold text-slate-800 opacity-70 backdrop-blur-md"><Play className="h-4 w-4" /> VİDEOYU İZLE</button></div>
            <div className="mt-3 max-w-3xl rounded-xl border border-white/50 bg-white/35 px-3 py-2 text-left shadow-lg backdrop-blur-md"><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-slate-900 sm:text-[10px]">81 MİLYON BENZERSİZ PARSEL</p><p className="mt-0.5 text-[9px] font-semibold leading-4 text-slate-900 sm:text-xs">Her parsel kendine özel bir parsel koduyla oluşturulur. Bir parsel yalnızca bir kişi tarafından satın alınabilir; satın alınan parsel sahibinin hesabına kaydedilir ve aynı parsel yeniden üretilemez.</p></div>
          </div>
        </div>
      </section>
      <section className="relative z-10 mx-auto max-w-[1600px] px-4 pt-4 sm:pt-5 lg:px-8"><div className="grid gap-4 rounded-2xl border border-slate-200 bg-white/85 p-4 shadow-xl backdrop-blur-md sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{STATS.map((s) => <div key={s.title} className="flex min-w-0 items-start gap-3"><s.icon className="mt-0.5 h-5 w-5 shrink-0 text-amber-700" /><div className="min-w-0">{s.big && <p className="font-display text-lg font-bold text-slate-950">{s.big}</p>}<p className="text-[11px] font-semibold tracking-[0.08em] text-slate-900">{s.title}</p><p className="mt-0.5 text-[10px] text-slate-600">{s.text}</p></div></div>)}</div>{!parcelModelCheck && <p className="mt-2 text-center text-[10px] text-slate-600">Parsel model verisi henüz doğrulanmadı.</p>}</section>
      <section className="relative z-10 mx-auto max-w-[1600px] px-4 py-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{CERTIFICATE_PACKAGES.map((p) => <article key={p.id} className="flex min-w-0 flex-col rounded-2xl border border-slate-200 bg-white/90 p-5 shadow-xl backdrop-blur-md"><h3 className="font-display text-lg text-slate-950">{p.name}</h3><ul className="mt-3 space-y-1.5 text-xs">{p.features.map((f)=><li key={f} className="flex items-start gap-2 text-slate-600"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-700"/><span>{f}</span></li>)}</ul><CertificateTemplatePreview tier={p.id} className="mt-5"/><p className="mt-4 font-display text-2xl text-amber-700">{p.price.toLocaleString("tr-TR")} <span className="text-base">TL</span></p><Link to="/paketler" className="mt-3 inline-flex min-h-10 items-center justify-center rounded-md bg-amber-600 px-5 py-2 text-[11px] font-bold text-white shadow-md transition hover:bg-amber-700">HEMEN İNCELE</Link></article>)}</div></section>
      <section className="relative z-10 mx-auto max-w-[1600px] px-4 pb-6 lg:px-8"><div className="rounded-2xl border border-slate-200 bg-white/90 p-4 shadow-xl backdrop-blur-md sm:p-5"><h3 className="font-display text-base text-slate-950">SERTİFİKA DOĞRULA</h3><p className="mt-1.5 text-xs text-slate-600">Sertifika numaranızı girerek geçerliliğini kontrol edebilirsiniz.</p><form onSubmit={handleCertificateSubmit} className="mt-3 flex flex-col gap-2 sm:flex-row"><label htmlFor="homepage-certificate-code" className="sr-only">Sertifika numarası</label><input id="homepage-certificate-code" value={certificateCode} onChange={(event) => setCertificateCode(event.target.value)} placeholder="Sertifika numaranızı girin" autoComplete="off" className="min-w-0 flex-1 rounded-md border border-slate-300 bg-white/80 px-3 py-2 text-[11px] uppercase text-slate-900 outline-none focus:border-amber-600"/><button type="submit" className="inline-flex items-center justify-center rounded-md bg-amber-600 px-4 py-2 text-[11px] font-bold text-white hover:bg-amber-700">DOĞRULA</button></form></div></section>
      <section className="relative z-10 mx-auto max-w-[1600px] px-4 pb-6 lg:px-8"><div className="rounded-2xl border border-slate-200 bg-white/90 p-4 shadow-xl backdrop-blur-md sm:p-5 lg:grid lg:grid-cols-[auto_1fr_auto] lg:items-center"><h3 className="font-display text-base tracking-[0.08em] text-slate-950">POPÜLER ŞEHİRLER</h3><ul className="flex flex-wrap justify-center gap-3 sm:gap-4">{POPULAR_CITIES.map(c=><li key={c.code}><button type="button" onClick={() => navigate({ to: "/turkiye-haritasi", search: { city: c.slug } })} className="block cursor-pointer text-center"><div className="mx-auto grid h-11 w-11 items-center overflow-hidden rounded-full border border-amber-600/60 bg-slate-100 sm:h-12 sm:w-12"><img src={c.image} alt={`${c.name} şehir manzarası`} loading="lazy" width={96} height={96} className="h-full w-full object-cover"/></div><p className="mt-1.5 text-[10px] tracking-[0.08em] text-slate-600">{c.name}</p></button></li>)}</ul><Link to="/turkiye-haritasi" className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border border-amber-600/60 px-5 py-2 text-[11px] font-bold text-amber-700">TÜM ŞEHİRLER <ArrowRight className="h-4 w-4"/></Link></div></section>
      <TrustBar />
    </main>
    <SiteFooter />
  </div>;
}
