import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Boxes, Check, Globe, Headphones, Layers, Lock, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { TrustBar } from "@/components/TrustBar";
import { CertificateTemplatePreview } from "@/components/CertificateTemplatePreview";
import { CITY_IMAGES } from "@/lib/cityImages";

export const Route = createFileRoute("/ana-sayfa")({ headers: () => ({ "Cache-Control": "no-store, no-cache, must-revalidate" }), head: () => ({ meta: [{ title: "MySkyParcel — Kişiye Özel Hediye, Dijital Hediye ve Gökyüzü Parseli" }, { name: "description", content: "Kişiye özel hediye, sevgiliye farklı hediye ve dijital hediye arayanlar için MySkyParcel: gökyüzünde sembolik parsel ve kişiye özel dijital sertifika." }], links: [{ rel: "canonical", href: "https://myskyparcel.com/ana-sayfa" }] }), component: Index });
const SKY_PARCEL_MODEL = { cityCount: 81, layersPerCity: 10, sectorsPerCity: 1_000, parcelsPerCity: 1_000_000, totalParcels: 81_000_000 } as const;
const STATS = [{ icon: Globe, big: "81 MİLYON", title: "TOPLAM GÖKYÜZÜ PARSELİ", text: "81 il × 1.000.000 parsel uzun vadeli hedef" }, { icon: Layers, big: "10", title: "KATMAN / İL", text: "Her il için 10 katman" }, { icon: ShieldCheck, big: "1.000", title: "SEKTÖR / İL", text: "Her il için 1.000 sektör" }, { icon: Boxes, big: "1.000.000", title: "PARSEL / İL", text: "Her il için 1.000.000 parsel" }, { icon: Headphones, big: "DESTEK", title: "DESTEK EKİBİ", text: "İletişim kanalları üzerinden bize ulaşabilirsiniz" }, { icon: Lock, big: "", title: "GÜVENLİ ALTYAPI", text: "Güvenlik ve ödeme altyapısı ayrıca doğrulanmalıdır" }];
const CERTIFICATE_PACKAGES = [
  { id: "digital", name: "DİJİTAL PARSEL SERTİFİKA", price: 149, features: ["Dijital sertifika", "Parsel kodu ve kayıt bilgileri"] },
  { id: "elite", name: "ÖZEL PARSEL SERTİFİKA", price: 349, features: ["Özel tasarım sertifika", "A4 fiziksel baskı", "Dijital sertifika"] },
  { id: "premium", name: "PREMİUM PARSEL SERTİFİKA", price: 699, features: ["Premium tasarım sertifika", "Çerçeveli baskı", "Dijital sertifika"] },
] as const;
const SOLD_PARCEL_BASE_COUNT = 32_960;
const SOLD_PARCEL_START_AT = new Date("2026-09-19T05:00:00+03:00").getTime();
const SOLD_PARCEL_HOUR_MS = 60 * 60 * 1000;

const POPULAR_CITIES = [{ name: "İSTANBUL", slug: "istanbul", code: "IST", image: CITY_IMAGES.IST }, { name: "ANKARA", slug: "ankara", code: "ANK", image: CITY_IMAGES.ANK }, { name: "İZMİR", slug: "izmir", code: "IZM", image: CITY_IMAGES.IZM }, { name: "ANTALYA", slug: "antalya", code: "ANT", image: CITY_IMAGES.ANT }, { name: "BURSA", slug: "bursa", code: "BUR", image: CITY_IMAGES.BUR }, { name: "KAYSERİ", slug: "kayseri", code: "KAY", image: CITY_IMAGES.KAY }, { name: "GAZİANTEP", slug: "gaziantep", code: "GZT", image: CITY_IMAGES.GZT }] as const;
function Index() {
  const navigate = useNavigate(); const [certificateCode, setCertificateCode] = useState(""); const [soldParcelCount, setSoldParcelCount] = useState(() => SOLD_PARCEL_BASE_COUNT + Math.max(0, Math.floor((Date.now() - SOLD_PARCEL_START_AT) / SOLD_PARCEL_HOUR_MS)) * 11); const parcelModelCheck = SKY_PARCEL_MODEL.cityCount * SKY_PARCEL_MODEL.parcelsPerCity === SKY_PARCEL_MODEL.totalParcels;
  useEffect(() => { const updateSoldParcelCount = () => setSoldParcelCount(SOLD_PARCEL_BASE_COUNT + Math.max(0, Math.floor((Date.now() - SOLD_PARCEL_START_AT) / SOLD_PARCEL_HOUR_MS)) * 10); updateSoldParcelCount(); const timer = window.setInterval(updateSoldParcelCount, 60_000); return () => window.clearInterval(timer); }, []);
  function handleCertificateSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!certificateCode.trim()) return; navigate({ to: "/sertifika-dogrula", search: { code: certificateCode.trim() } }); }
  return <div className="starfield min-h-screen"><SiteHeader /><main>
    <section className="hero-sky-parcels relative min-h-[312px] overflow-hidden bg-cover bg-center bg-no-repeat sm:min-h-[344px] lg:min-h-[376px]" style={{ backgroundImage: "url('/hero-background.jpg')" }}><div className="relative mx-auto max-w-[1600px] px-4 py-4 sm:py-5 lg:px-8"><div className="min-w-0 max-w-3xl"><h1 className="break-words font-display text-3xl leading-[1.05] font-bold drop-shadow-lg sm:text-4xl lg:text-5xl">GÖKYÜZÜNDE<br /><span className="text-gradient-gold">SANA ÖZEL</span><br />SEMBOLİK BİR YER</h1><Link to="/turkiye-haritasi" className="btn-gold mt-3 inline-flex max-w-full items-center gap-2 rounded-md px-4 py-2 text-[10px] sm:px-5 sm:text-xs"><Sparkles className="h-4 w-4 shrink-0" /> GÖKYÜZÜ HARİTASINA GİT</Link><div className="mt-4 rounded-xl border border-gold/50 bg-black/35 px-4 py-3 text-center shadow-xl backdrop-blur-sm"><p className="text-[9px] font-semibold tracking-[0.14em] text-gold sm:text-[10px]">SATILAN PARSEL</p><p className="mt-1 font-display text-4xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">{soldParcelCount.toLocaleString("tr-TR")}</p></div></div></div></section>
    <section className="mx-auto max-w-[1600px] px-4 pt-4 sm:pt-5 lg:px-8"><div className="panel grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{STATS.map((s) => <div key={s.title} className="flex min-w-0 items-start gap-3"><s.icon className="mt-0.5 h-5 w-5 shrink-0 text-gold" /><div className="min-w-0">{s.big && <p className="font-display text-lg font-bold">{s.big}</p>}<p className="text-[11px] font-semibold tracking-[0.08em]">{s.title}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{s.text}</p></div></div>)}</div>{!parcelModelCheck && <p className="mt-2 text-center text-[10px] text-muted-foreground">Parsel model verisi henüz doğrulanmadı.</p>}</section>
    <section className="mx-auto max-w-[1600px] px-4 py-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{CERTIFICATE_PACKAGES.map((p) => <article key={p.id} className="panel flex min-w-0 flex-col p-5"><h3 className="font-display text-lg">{p.name}</h3><ul className="mt-3 space-y-1.5 text-xs">{p.features.map((f)=><li key={f} className="flex items-start gap-2 text-muted-foreground"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-gold"/><span>{f}</span></li>)}</ul><CertificateTemplatePreview tier={p.id} className="mt-5"/><p className="mt-4 font-display text-2xl text-gold">{p.price.toLocaleString("tr-TR")} <span className="text-base">TL</span></p><Link to="/paketler" className="btn-gold mt-3 inline-flex min-h-10 items-center justify-center rounded-md px-5 py-2 text-[11px]">HEMEN İNCELE</Link></article>)}</div></section>
    <section className="mx-auto max-w-[1600px] px-4 pb-6 lg:px-8"><div className="panel p-4 sm:p-5"><h3 className="font-display text-base">SERTİFİKA DOĞRULA</h3><p className="mt-1.5 text-xs text-muted-foreground">Sertifika numaranızı girerek geçerliliğini kontrol edebilirsiniz.</p><form onSubmit={handleCertificateSubmit} className="mt-3 flex flex-col gap-2 sm:flex-row"><label htmlFor="homepage-certificate-code" className="sr-only">Sertifika numarası</label><input id="homepage-certificate-code" value={certificateCode} onChange={(event) => setCertificateCode(event.target.value)} placeholder="Sertifika numaranızı girin" autoComplete="off" className="min-w-0 flex-1 rounded-md border border-input bg-background/60 px-3 py-2 text-[11px] uppercase outline-none focus:border-gold"/><button type="submit" className="btn-gold inline-flex items-center justify-center rounded-md px-4 py-2 text-[11px]">DOĞRULA</button></form></div></section>
    <section className="mx-auto max-w-[1600px] px-4 pb-6 lg:px-8"><div className="panel grid gap-4 p-4 sm:p-5 lg:grid-cols-[auto_1fr_auto] lg:items-center"><h3 className="font-display text-base tracking-[0.08em]">POPÜLER ŞEHİRLER</h3><ul className="flex flex-wrap justify-center gap-3 sm:gap-4">{POPULAR_CITIES.map(c=><li key={c.code}><button type="button" onClick={() => navigate({ to: "/turkiye-haritasi", search: { city: c.slug } })} className="block cursor-pointer text-center"><div className="mx-auto grid h-11 w-11 items-center overflow-hidden rounded-full border border-gold/60 bg-navy sm:h-12 sm:w-12"><img src={c.image} alt={`${c.name} şehir manzarası`} loading="lazy" width={96} height={96} className="h-full w-full object-cover"/></div><p className="mt-1.5 text-[10px] tracking-[0.08em] text-muted-foreground">{c.name}</p></button></li>)}</ul><Link to="/turkiye-haritasi" className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border border-gold/60 px-5 py-2 text-[11px] text-gold">TÜM ŞEHİRLER <ArrowRight className="h-4 w-4"/></Link></div></section><TrustBar /></main><SiteFooter /></div>;
}
