import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";

export const Route = createFileRoute("/cerez-politikasi")({
  head: () => ({ meta: [{ title: "Çerez Politikası — MySkyParcel" }, { name: "description", content: "MySkyParcel Çerez Politikası." }] }),
  component: CerezPolitikasi,
});

function CerezPolitikasi() {
  return <div className="starfield min-h-screen"><SiteHeader /><main className="mx-auto max-w-4xl px-4 py-12 lg:px-8"><article className="panel p-6 sm:p-10"><h1 className="font-display text-3xl font-bold sm:text-4xl">ÇEREZ POLİTİKASI</h1><p className="mt-3 text-xs text-muted-foreground">Son güncelleme: 24 Ağustos 2026</p><div className="mt-6 space-y-6 text-sm leading-7 text-muted-foreground"><section><h2 className="font-display text-lg text-gold">1. Çerezler Nedir?</h2><p className="mt-2">Çerezler, internet sitelerinin tarayıcı veya cihaz üzerinde belirli bilgileri saklamasını sağlayan küçük veri dosyalarıdır. Teknik olarak çerezlerden farklı olan localStorage gibi tarayıcı depolama mekanizmaları da kullanıcı oturumu veya tercihlerin korunması amacıyla kullanılabilir.</p></section><section><h2 className="font-display text-lg text-gold">2. MySkyParcel'de Kullanım</h2><p className="mt-2">MySkyParcel'de üçüncü taraf reklam veya Google Analytics/gtag tabanlı bir izleme kodu kullanılmamaktadır. Site ziyaret istatistikleri için teknik ziyaret oturumu kimliği tarayıcının localStorage alanında tutulabilir ve Supabase altyapısındaki site istatistik hizmetine sayfa yolu ile birlikte gönderilebilir. Bu mekanizma site güvenliği, teknik işletim ve toplu ziyaret istatistikleri amacıyla kullanılır.</p></section><section><h2 className="font-display text-lg text-gold">3. Gerekli Teknolojiler</h2><p className="mt-2">Üyelik, kimlik doğrulama, güvenlik ve uygulamanın temel işlevleri için kullanılan oturum/kimlik doğrulama teknolojileri gerekli olabilir. Ödeme işlemleri ödeme kuruluşunun kendi güvenli ortamında yürütüldüğünde, ödeme kuruluşu kendi çerez ve benzeri teknolojilerine ilişkin bilgilendirmeyi ayrıca sunabilir.</p></section><section><h2 className="font-display text-lg text-gold">4. Tercihler ve Kontrol</h2><p className="mt-2">Tarayıcınızın ayarlarından çerezleri ve site depolama verilerini yönetebilir veya silebilirsiniz. Gerekli teknolojilerin devre dışı bırakılması üyelik, güvenlik veya bazı site işlevlerinin çalışmamasına neden olabilir.</p></section><section><h2 className="font-display text-lg text-gold">5. Üçüncü Taraf Hizmetleri</h2><p className="mt-2">MySkyParcel'in ödeme, barındırma, kimlik doğrulama veya teknik altyapı için kullandığı üçüncü taraf hizmetlerin kendi teknik depolama ve çerez uygulamaları bulunabilir. Bu hizmetlerin kendi politika ve koşulları ayrıca uygulanabilir.</p></section><section><h2 className="font-display text-lg text-gold">6. İletişim</h2><p className="mt-2">Çerezler ve kişisel verilerle ilgili sorularınız için <strong className="text-foreground">Mehmet Kanuşağı / MySkyParcel</strong> ile iletişime geçebilirsiniz: incememet3296@gmail.com · 0541 615 97 43.</p></section></div></article></main><SiteFooter /></div>;
}
