import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Boxes, Globe, Headphones, Layers, Lock, Play, ShieldCheck, Sparkles } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { TrustBar } from "@/components/TrustBar";
import { CITY_IMAGES } from "@/lib/cityImages";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "MySkyParcel — Gökyüzünde Sana Özel Sembolik Bir Yer" }, { name: "description", content: "81 il ve 81 milyon benzersiz gökyüzü parseli fikri." }] }), component: Index });
const SKY_PARCEL_MODEL = { cityCount: 81, layersPerCity: 10, sectorsPerCity: 1_000, parcelsPerCity: 1_000_000, totalParcels: 81_000_000 } as const;
const STATS = [{ icon: Globe, big: "81 MİLYON", title: "TOPLAM GÖKYÜZÜ PARSELİ", text: "81 il × 1.000.000 parsel uzun vadeli hedef" }, { icon: Layers, big: "10", title: "KATMAN / İL", text: "Her il için 10 katman" }, { icon: ShieldCheck, big: "1.000", title: "SEKTÖR / İL", text: "Her il için 1.000 sektör" }, { icon: Boxes, big: "1.000.000", title: "PARSEL / İL", text: "Her il için 1.000.000 parsel" }, { icon: Headphones, big: "DESTEK", title: "DESTEK EKİBİ", text: "İletişim kanalları üzerinden bize ulaşabilirsiniz" }, { icon: Lock, big: "", title: "GÜVENLİ ALTYAPI", text: "Güvenlik ve ödeme altyapısı ayrıca doğrulanmalıdır" }];
const POPULAR_CITIES = [{ name: "İSTANBUL", slug: "istanbul", code: "IST", image: CITY_IMAGES.IST }, { name: "ANKARA", slug: "ankara", code: "ANK", image: CITY_IMAGES.ANK }, { name: "İZMİR", slug: "izmir", code: "IZM", image: CITY_IMAGES.IZM }, { name: "ANTALYA", slug: "antalya", code: "ANT", image: CITY_IMAGES.ANT }, { name: "BURSA", slug: "bursa", code: "BUR", image: CITY_IMAGES.BUR }, { name: "KAYSERİ", slug: "kayseri", code: "KAY", image: CITY_IMAGES.KAY }, { name: "GAZİANTEP", slug: "gaziantep", code: "GZT", image: CITY_IMAGES.GZT }] as const;
function Index() {
  const navigate = useNavigate(); const parcelModelCheck = SKY_PARCEL_MODEL.cityCount * SKY_PARCEL_MODEL.parcelsPerCity === SKY_PARCEL_MODEL.totalParcels;
  return <div className="starfield min-h-screen"><SiteHeader /><main>
    <section className="hero-sky-parcels relative min-h-[312px] overflow-hidden bg-cover bg-center bg-no-repeat sm:min-h-[344px] lg:min-h-[376px]" style={{ backgroundImage: "url('/hero-background.jpg')" }}><div className="relative mx-auto max-w-[1600px] px-4 py-4 sm:py-5 lg:px-8"><div className="min-w-0 max-w-3xl"><span className="inline-block max-w-full rounded-md border border-gold/60 bg-background/20 px-3 py-1 tracking-[0.1em] text-[8px] leading-4 text-gold backdrop-blur-[2px] sm:px-4 sm:text-[9px]">HER İL İÇİN {SKY_PARCEL_MODEL.layersPerCity} KATMAN · {SKY_PARCEL_MODEL.sectorsPerCity.toLocaleString("tr-TR")} SEKTÖR · {SKY_PARCEL_MODEL.parcelsPerCity.toLocaleString("tr-TR")} PARSEL<br /><strong>TOPLAM {SKY_PARCEL_MODEL.totalParcels.toLocaleString("tr-TR")} GÖKYÜZÜ PARSELİ</strong></span><h1 className="mt-2 break-words font-display text-3xl leading-[1.05] font-bold drop-shadow-lg sm:text-4xl lg:text-5xl">GÖKYÜZÜNDE<br /><span className="text-gradient-gold">SANA ÖZEL</span><br />SEMBOLİK BİR YER</h1><p className="mt-2 max-w-lg text-xs font-medium text-black drop-shadow sm:text-sm">MySkyParcel ile gökyüzünde sana özel bir parsel seçebilir, benzersiz sertifikanla bu anı ölümsüzleştirebilirsin.</p><div className="mt-2 flex max-w-full flex-wrap gap-2"><Link to="/gokyuzu-haritasi" search={{ city: "istanbul" }} className="btn-gold inline-flex max-w-full items-center gap-2 rounded-md px-4 py-2 text-[10px] sm:px-5 sm:text-xs"><Sparkles className="h-4 w-4 shrink-0" /> GÖKYÜZÜ HARİTASINA GİT</Link><button type="button" disabled className="inline-flex items-center gap-2 rounded-md border border-border bg-background/20 px-4 py-2 text-[10px] opacity-70"><Play className="h-4 w-4" /> VİDEOYU İZLE</button></div><div className="mt-3 max-w-3xl rounded-xl border border-cyan-300/20 bg-slate-950/45 px-3 py-2 text-left shadow-lg backdrop-blur-sm"><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-cyan-100/95 sm:text-[10px]">81 MİLYON BENZERSİZ PARSEL</p><p className="mt-0.5 text-[9px] leading-4 font-semibold text-white sm:text-xs">Her parsel kendine özel bir parsel koduyla oluşturulur. Bir parsel yalnızca bir kişi tarafından satın alınabilir; satın alınan parsel sahibinin hesabına kaydedilir ve aynı parsel yeniden üretilemez.</p></div></div></div></section>
    <section className="mx-auto max-w-[1600px] px-4 pt-4 sm:pt-5 lg:px-8"><div className="panel grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{STATS.map((s) => <div key={s.title} className="flex min-w-0 items-start gap-3"><s.icon className="mt-0.5 h-5 w-5 shrink-0 text-gold" /><div className="min-w-0">{s.big && <p className="font-display text-lg font-bold">{s.big}</p>}<p className="text-[11px] font-semibold tracking-[0.08em]">{s.title}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{s.text}</p></div></div>)}</div>{!parcelModelCheck && <p className="mt-2 text-center text-[10px] text-muted-foreground">Parsel model verisi henüz doğrulanmadı.</p>}</section>
    <section className="mx-auto max-w-[1600px] px-4 pb-6 lg:px-8"><div className="panel grid gap-4 p-4 sm:p-5 lg:grid-cols-[auto_1fr_auto] lg:items-center"><h3 className="font-display text-base tracking-[0.08em]">POPÜLER ŞEHİRLER</h3><ul className="flex flex-wrap justify-center gap-3 sm:gap-4">{POPULAR_CITIES.map(c=><li key={c.code}><button type="button" onClick={() => navigate({ to: "/gokyuzu-haritasi", search: { city: c.slug } })} className="block cursor-pointer text-center"><div className="mx-auto grid h-11 w-11 place-items-center overflow-hidden rounded-full border border-gold/60 bg-navy sm:h-12 sm:w-12"><img src={c.image} alt={`${c.name} şehir manzarası`} loading="lazy" width={96} height={96} className="h-full w-full object-cover"/></div><p className="mt-1.5 text-[10px] tracking-[0.08em] text-muted-foreground">{c.name}</p></button></li>)}</ul><Link to="/gokyuzu-haritasi" search={{ city: "istanbul" }} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border border-gold/60 px-5 py-2 text-[11px] text-gold">TÜM ŞEHİRLER <ArrowRight className="h-4 w-4"/></Link></div></section><TrustBar /></main><SiteFooter /></div>;
}