import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Boxes, Check, Globe, Headphones, Layers, Lock, Play, ShieldCheck, Sparkles } from "lucide-react";
import { useState, type FormEvent } from "react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { TrustBar } from "@/components/TrustBar";
import { CITY_IMAGES } from "@/lib/cityImages";
import { CERTIFICATE_TEMPLATE_IMAGE as templateImage } from "@/lib/certificateTemplate";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "MySkyParcel — Gökyüzünde Sana Özel Sembolik Bir Yer" }, { name: "description", content: "Her il için 10 katman, 1.000 sektör ve 1.000.000 parsel. Uzun vadeli hedef: 81 milyon gökyüzü parseli." }, { property: "og:title", content: "MySkyParcel — Gökyüzünde Sana Özel Bir Yer" }, { property: "og:description", content: "Sembolik gökyüzü parselini seç, dijital veya çerçeveli sertifikanı al." }] }), component: Index });
const SKY_PARCEL_MODEL = { cityCount: 81, layersPerCity: 10, sectorsPerCity: 1_000, parcelsPerCity: 1_000_000, totalParcels: 81_000_000 } as const;
const STATS = [{ icon: Globe, big: "81 MİLYON", title: "TOPLAM GÖKYÜZÜ PARSELİ", text: "81 il × 1.000.000 parsel uzun vadeli hedef" }, { icon: Layers, big: "10", title: "KATMAN / İL", text: "Her il için 10 katman" }, { icon: ShieldCheck, big: "1.000", title: "SEKTÖR / İL", text: "Her il için 1.000 sektör" }, { icon: Boxes, big: "1.000.000", title: "PARSEL / İL", text: "Her il için 1.000.000 parsel" }, { icon: Headphones, big: "DESTEK", title: "DESTEK EKİBİ", text: "İletişim kanalları üzerinden bize ulaşabilirsiniz" }, { icon: Lock, big: "", title: "GÜVENLİ ALTYAPI", text: "Güvenlik ve ödeme altyapısı ayrıca doğrulanmalıdır" }];
const CERTIFICATE_PACKAGES = [
  { id: "digital", name: "DİJİTAL", price: 199, features: ["Dijital sertifika", "Parsel kodu ve koordinatlar", "QR doğrulama", "E-posta ile anında teslim"] },
  { id: "elite", name: "ELİT", price: 499, features: ["Özel tasarım sertifika", "Dijital sertifika", "Parsel kodu ve koordinatlar", "QR doğrulama", "E-posta ile anında teslim", "Posta yoluyla gönderim"] },
  { id: "premium", name: "PREMİUM", price: 999, features: ["Özel tasarım sertifika", "Çerçeveli baskı (A4)", "Dijital sertifika", "Parsel kodu ve koordinatlar", "QR doğrulama", "Posta yoluyla gönderim"] },
] as const;
const POPULAR_CITIES = [{ name: "İSTANBUL", slug: "istanbul", code: "IST", image: CITY_IMAGES.IST }, { name: "ANKARA", slug: "ankara", code: "ANK", image: CITY_IMAGES.ANK }, { name: "İZMİR", slug: "izmir", code: "IZM", image: CITY_IMAGES.IZM }, { name: "ANTALYA", slug: "antalya", code: "ANT", image: CITY_IMAGES.ANT }, { name: "BURSA", slug: "bursa", code: "BUR", image: CITY_IMAGES.BUR }, { name: "KAYSERİ", slug: "kayseri", code: "KAY", image: CITY_IMAGES.KAY }, { name: "GAZİANTEP", slug: "gaziantep", code: "GZT", image: CITY_IMAGES.GZT }] as const;
function Index() {
  const navigate = useNavigate(); const [certificateCode, setCertificateCode] = useState(""); const parcelModelCheck = SKY_PARCEL_MODEL.cityCount * SKY_PARCEL_MODEL.parcelsPerCity === SKY_PARCEL_MODEL.totalParcels;
  function handleCertificateSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); navigate({ to: "/sertifika-dogrula", search: { code: certificateCode.trim() } }); }
  return <div className="starfield min-h-screen"><SiteHeader /><main>
    <section className="hero-sky-parcels relative min-h-[560px] overflow-hidden bg-cover bg-center bg-no-repeat sm:min-h-[620px] lg:min-h-[700px]" style={{ backgroundImage: "url('/hero-background.jpg')" }}><div className="relative mx-auto max-w-[1600px] px-4 py-10 sm:py-14 lg:px-8 xl:py-20"><div className="min-w-0 max-w-3xl"><span className="inline-block max-w-full rounded-md border border-gold/60 bg-background/20 px-3 py-2 text-[9px] leading-5 tracking-[0.1em] text-gold backdrop-blur-[2px] sm:px-4 sm:text-[10px] sm:tracking-[0.12em]">HER İL İÇİN {SKY_PARCEL_MODEL.layersPerCity} KATMAN · {SKY_PARCEL_MODEL.sectorsPerCity.toLocaleString("tr-TR")} SEKTÖR · {SKY_PARCEL_MODEL.parcelsPerCity.toLocaleString("tr-TR")} PARSEL<br /><strong>TOPLAM {SKY_PARCEL_MODEL.totalParcels.toLocaleString("tr-TR")} GÖKYÜZÜ PARSELİ</strong></span><h1 className="mt-5 break-words font-display text-3xl leading-[1.1] font-bold drop-shadow-lg sm:mt-6 sm:text-5xl lg:text-6xl">GÖKYÜZÜNDE<br /><span className="text-gradient-gold">SANA ÖZEL</span><br />SEMBOLİK BİR YER</h1><p className="mt-4 max-w-lg text-sm text-foreground/85 drop-shadow sm:mt-5 sm:text-base">MySkyParcel ile gökyüzünde sana özel bir parsel seçebilir, benzersiz sertifikanla bu anı ölümsüzleştirebilirsin.</p><div className="mt-6 flex max-w-full flex-wrap gap-3 sm:mt-8"><Link to="/gokyuzu-haritasi" className="btn-gold inline-flex max-w-full items-center gap-2 rounded-md px-5 py-3 text-[11px] sm:px-6 sm:text-xs"><Sparkles className="h-4 w-4 shrink-0" /> GÖKYÜZÜ HARİTASINA GİT</Link><button type="button" disabled aria-disabled="true" title="Video kaynağı sonraki entegrasyonda eklenecek" className="inline-flex max-w-full items-center gap-2 rounded-md border border-border bg-background/20 px-5 py-3 text-[11px] tracking-[0.06em] transition-colors hover:border-gold hover:text-gold disabled:cursor-not-allowed disabled:opacity-70 sm:px-6 sm:text-xs"><Play className="h-4 w-4 shrink-0" /> VİDEOYU İZLE</button></div></div></div></section>
    <section className="mx-auto max-w-[1600px] px-4 py-6 sm:py-8 lg:px-8"><div className="panel grid gap-5 p-5 sm:grid-cols-2 sm:gap-6 sm:p-6 lg:grid-cols-3 xl:grid-cols-6">{STATS.map((s) => <div key={s.title} className="flex min-w-0 items-start gap-3"><s.icon className="mt-1 h-6 w-6 shrink-0 text-gold" /><div className="min-w-0">{s.big && <p className="font-display text-xl font-bold">{s.big}</p>}<p className="text-[11px] font-semibold tracking-[0.08em]">{s.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{s.text}</p></div></div>)}</div>{!parcelModelCheck && <p className="mt-2 text-center text-[10px] text-muted-foreground">Parsel model verisi henüz doğrulanmadı.</p>}</section>
    <section className="mx-auto grid max-w-[1600px] gap-6 px-4 pb-8 lg:px-8 xl:grid-cols-[3fr_1fr]"><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{CERTIFICATE_PACKAGES.map((p) => <article key={p.id} className="panel flex min-w-0 flex-col p-5 sm:p-6"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><div className="min-w-0 min-h-0 sm:min-h-[248px]"><h3 className="font-display text-lg">{p.name}</h3><ul className="mt-4 space-y-2 text-xs">{p.features.map((f)=><li key={f} className="flex items-start gap-2 text-muted-foreground"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-gold"/><span>{f}</span></li>)}</ul></div><div className="flex aspect-[3/2] min-h-0 w-full items-center justify-center overflow-hidden rounded-lg bg-[#06162f] p-1.5 sm:h-auto sm:aspect-auto sm:p-2 xl:aspect-[3/2]"><img src={templateImage} alt={`${p.name} Gökyüzü Sertifikası şablonu`} loading="lazy" decoding="async" width={1000} height={667} className="h-full w-full object-contain object-center" /></div></div><p className="mt-5 font-display text-2xl text-gold sm:mt-6 sm:text-3xl">{p.price.toLocaleString("tr-TR")} <span className="text-base">TL</span></p><Link to="/paketler" className="btn-gold mt-4 inline-flex min-h-11 items-center justify-center rounded-md px-5 py-2.5 text-[11px] sm:mt-auto">HEMEN İNCELE</Link></article>)}</div><div className="grid content-start gap-6"><div className="panel p-5 sm:p-6"><h3 className="font-display text-base">SERTİFİKA DOĞRULA</h3><p className="mt-2 text-xs text-muted-foreground">Parsel kodunuzu girerek sertifikanızın geçerliliğini kontrol edebilirsiniz.</p><form onSubmit={handleCertificateSubmit} className="mt-4 flex flex-col gap-2 sm:flex-row"><label htmlFor="homepage-certificate-code" className="sr-only">Sertifika numarası</label><input id="homepage-certificate-code" value={certificateCode} onChange={(event) => setCertificateCode(event.target.value)} aria-label="Sertifika numarası" placeholder="Sertifika numaranızı girin (Örn: SP-GZT-0004207)" autoComplete="off" className="min-w-0 w-full rounded-md border border-input bg-background/60 px-3 py-2 text-[11px] uppercase outline-none focus:border-gold"/><button type="submit" className="btn-gold inline-flex w-full shrink-0 items-center justify-center rounded-md px-4 py-2 text-[11px] sm:w-auto">DOĞRULA</button></form></div><div className="panel p-5 sm:p-6"><h3 className="font-display text-base">GÜVENLİ ALIŞVERİŞ</h3><p className="mt-2 text-xs text-muted-foreground">Güvenlik ve ödeme altyapısı yayın öncesi ayrıca doğrulanmalıdır.</p></div></div></section>
    <section className="mx-auto max-w-[1600px] px-4 pb-8 lg:px-8"><div className="panel grid gap-6 p-5 sm:p-6 lg:grid-cols-[auto_1fr_auto] lg:items-center"><h3 className="font-display text-base tracking-[0.08em]">POPÜLER ŞEHİRLER</h3><ul className="flex flex-wrap justify-center gap-4 sm:gap-5">{POPULAR_CITIES.map(c=><li key={c.code}><button type="button" onClick={() => navigate({ to: "/gokyuzu-haritasi", search: { city: c.slug } })} className="block cursor-pointer text-center"><div className="mx-auto grid h-12 w-12 place-items-center overflow-hidden rounded-full border border-gold/60 bg-navy transition-transform duration-200 hover:scale-105 sm:h-14 sm:w-14"><img src={c.image} alt={`${c.name} şehir manzarası`} loading="lazy" width={96} height={96} className="h-full w-full object-cover opacity-100"/></div><p className="mt-2 text-[10px] tracking-[0.08em] text-muted-foreground">{c.name}</p></button></li>)}</ul><Link to="/gokyuzu-haritasi" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md border border-gold/60 px-5 py-2.5 text-[11px] tracking-[0.08em] text-gold">TÜM ŞEHİRLER <ArrowRight className="h-4 w-4"/></Link></div></section><TrustBar /></main><SiteFooter /></div>;
}
