import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";

export const Route = createFileRoute("/kullanim-sartlari")({
  head: () => ({ meta: [{ title: "Kullanım Şartları — MySkyParcel" }] }),
  component: KullanimSartlari,
});

function KullanimSartlari() {
  return <div className="starfield min-h-screen"><SiteHeader /><main className="mx-auto max-w-4xl px-4 py-12 lg:px-8"><article className="panel p-6 sm:p-10"><h1 className="font-display text-3xl font-bold sm:text-4xl">KULLANIM ŞARTLARI</h1><div className="mt-6 space-y-6 text-sm leading-7 text-muted-foreground"><section><h2 className="font-display text-lg text-gold">1. Hizmetin Niteliği</h2><p className="mt-2">MySkyParcel üzerinde sunulan gökyüzü parselleri tamamen <strong className="text-foreground">sembolik ve dijital koleksiyon amaçlıdır</strong>. Bir gökyüzü parselinin edinilmesi; gerçek bir arazi, taşınmaz veya gökyüzü üzerinde mülkiyet, tapu, kullanım, tasarruf, imar ya da başka herhangi bir ayni hak sağlamaz. Sertifika, yalnızca platform üzerindeki sembolik koleksiyon kaydını temsil eder ve resmi tapu veya mülkiyet belgesi niteliğinde değildir.</p></section><section><h2 className="font-display text-lg text-gold">2. Parsel ve Sertifika Hizmetleri</h2><p className="mt-2">Sunulan dijital ve fiziksel sertifikalar, sembolik dijital koleksiyon deneyimini belgelemek amacıyla hazırlanır. Fiziksel gönderimler, teslimat bilgilerinin doğru ve eksiksiz verilmesine bağlıdır. Sertifika veya parsel kodu gerçek taşınmaz mülkiyeti veya resmi bir hak oluşturmaz.</p></section><section><h2 className="font-display text-lg text-gold">3. Ödeme, İptal ve Tüketici Hakları</h2><p className="mt-2">Ödeme işlemleri yetkili ödeme altyapıları üzerinden gerçekleştirilir. İptal, iade, cayma ve diğer tüketici hakları yürürlükteki mevzuat ve satın alınan ürün veya hizmetin koşullarına tabidir.</p></section><section><h2 className="font-display text-lg text-gold">4. Platform İçeriği</h2><p className="mt-2">Platformdaki parsel numaraları, koordinatlar, harita gösterimleri, sertifikalar ve benzeri bilgiler dijital koleksiyon deneyiminin parçalarıdır ve gerçek bir coğrafi mülkiyet veya resmi kayıt anlamına gelmez.</p></section><section><h2 className="font-display text-lg text-gold">5. Değişiklikler</h2><p className="mt-2">MySkyParcel, hizmetlerin veya bu şartların mevzuata uygun şekilde güncellenmesi hakkını saklı tutar.</p></section></div><p className="mt-10 border-t border-border pt-5 text-xs text-muted-foreground">Son güncelleme: 10 Ağustos 2026</p></article></main><SiteFooter /></div>;
}
