import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, CloudDownload, Heart, Lock, ShieldCheck, Star } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { CERTIFICATE_TEMPLATE_IMAGES, type CertificateTier } from "@/lib/certificateTemplate";

export const Route = createFileRoute("/paketler")({ head: () => ({ meta: [{ title: "Dijital Sertifika — MySkyParcel" }, { name: "description", content: "MySkyParcel Dijital, Elit ve Premium sertifika seçeneklerini ve özelliklerini inceleyin." }, { property: "og:title", content: "Dijital Sertifika — MySkyParcel" }, { property: "og:description", content: "Üç farklı MySkyParcel sertifika seçeneğinin kapsamını inceleyin." }] }), component: Paketler });

type Plan = { name: string; tier: CertificateTier; price: string; popular: boolean; description: string; features: string[] };
const PLANS: Plan[] = [
  { name: "DİJİTAL PARSEL SERTİFİKASI", tier: "digital", price: "199", popular: false, description: "Parselinizi dijital ortamda saklamak ve paylaşmak isteyenler için temel sertifika seçeneğidir.", features: ["Kişiye özel dijital sertifika", "Parsel kodu ve koordinat bilgileri", "Sertifika numarası", "QR doğrulama bilgisi", "Dijital teslim", "E-posta ile teslim"] },
  { name: "ELİT PARSEL SERTİFİKASI", tier: "elite", price: "499", popular: true, description: "Dijital sertifikaya ek olarak kaliteli fiziksel baskı isteyenler için hazırlanmış sertifika seçeneğidir.", features: ["Tüm Dijital sertifika özellikleri", "Elit tasarım", "A4 kuşe kâğıt baskı", "Fiziksel ürün gönderimi", "QR doğrulama", "E-posta ile dijital teslim", "Kişiselleştirilmiş parsel bilgileri"] },
  { name: "PREMİUM PARSEL SERTİFİKASI", tier: "premium", price: "999", popular: false, description: "Daha özel bir sunum isteyenler için premium dokulu baskı ve çerçeveli fiziksel sertifika deneyimi sunar.", features: ["Tüm Elit sertifika özellikleri", "Premium tasarım", "A4 premium dokulu kâğıt", "Çerçeveli A4 baskı", "Fiziksel ürün gönderimi", "QR doğrulama", "Kişiselleştirilmiş parsel bilgileri"] },
];

const BENEFITS = [
  { icon: Star, title: "KİŞİYE ÖZEL", text: "Sertifika üzerinde ilgili kullanıcı ve parsel kayıtlarına göre kişiselleştirilmiş bilgiler kullanılır." },
  { icon: ShieldCheck, title: "DOĞRULANABİLİR", text: "Sertifika numarası ve QR doğrulama bilgileri, platformdaki kayıtla eşleşmeyi kontrol etmek için kullanılır." },
  { icon: CloudDownload, title: "DİJİTAL & FİZİKSEL", text: "Seçilen pakete göre dijital teslim ve fiziksel baskı seçeneklerinden yararlanabilirsiniz." },
  { icon: Lock, title: "GÜVENLİ KAYIT", text: "Sertifika talepleri ve parsel ilişkileri kullanıcı hesabı üzerinden yönetilir." },
  { icon: Heart, title: "ANLAMLI HEDİYE", text: "Dijital bir parsel deneyimini kişisel bir hatıra ve sertifika sunumuna dönüştürmek için tasarlanmıştır." },
];

function Paketler() {
  return <div className="starfield min-h-screen"><SiteHeader /><main className="mx-auto max-w-[1600px] px-4 py-10 sm:py-14 lg:px-8"><div className="text-center"><p className="text-xs font-semibold tracking-[0.2em] text-gold">DİJİTAL SERTİFİKA</p><h1 className="mt-3 font-display text-3xl font-bold sm:text-5xl">SERTİFİKA SEÇENEKLERİ</h1><p className="mx-auto mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">MySkyParcel parseliniz için üç farklı sertifika seçeneğinden ihtiyacınıza uygun olanı seçebilirsiniz. Sertifikalar dijital parsel kaydını ve seçilen hizmet paketinin kapsamını gösterir; gerçek taşınmaz tapusu veya resmi mülkiyet belgesi değildir.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{PLANS.map((p) => <article key={p.name} className={`panel relative flex h-full min-w-0 flex-col p-5 sm:p-7 ${p.popular ? "border-gold/70" : ""}`}>{p.popular && <span className="btn-gold absolute -top-3 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full px-4 py-1 text-[10px]">EN POPÜLER</span>}<h2 className="text-center font-display text-lg sm:text-xl">{p.name}</h2><p className="mt-3 min-h-12 text-center text-xs leading-5 text-muted-foreground">{p.description}</p><p className="mt-3 text-center font-display text-3xl text-gold sm:text-4xl">{p.price} <span className="text-lg">TL</span></p><button type="button" aria-label={`${p.name} görselini büyüt`} onClick={() => window.open(CERTIFICATE_TEMPLATE_IMAGES[p.tier], "_blank", "noopener,noreferrer")} className="group relative mt-5 flex aspect-[3/2] w-full cursor-zoom-in items-center justify-center overflow-hidden rounded-lg bg-[#06162f] p-1.5 sm:mt-6 sm:p-2"><img src={CERTIFICATE_TEMPLATE_IMAGES[p.tier]} alt={`${p.name} şablonu — büyütmek için tıklayın`} loading="eager" fetchPriority="high" decoding="async" width={768} height={512} className="block h-full w-full object-contain object-center transition-transform duration-200 group-hover:scale-[1.02]" /></button><ul className="mt-5 space-y-3 text-sm sm:mt-6">{p.features.map((f) => <li key={f} className="flex items-start gap-2 text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-gold" /><span>{f}</span></li>)}</ul><Link to="/gokyuzu-haritasi" search={{ city: "istanbul" }} className="btn-gold mt-6 flex min-h-11 items-center justify-center gap-3 rounded-md py-3 text-sm sm:mt-auto">PARSELİ SEÇ <ArrowRight className="h-4 w-4" /></Link></article>)}</div><div className="panel mt-10 grid gap-6 p-5 sm:grid-cols-2 sm:p-7 lg:grid-cols-5">{BENEFITS.map((b) => <div key={b.title} className="flex min-w-0 items-start gap-3"><b.icon className="mt-0.5 h-6 w-6 shrink-0 text-gold" /><div className="min-w-0"><p className="text-xs font-semibold tracking-[0.06em]">{b.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{b.text}</p></div></div>)}</div></main><SiteFooter /></div>;
}
