import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, CloudDownload, Heart, Lock, ShieldCheck, Star } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { CERTIFICATE_TEMPLATE_IMAGES, type CertificateTier } from "@/lib/certificateTemplate";

export const Route = createFileRoute("/paketler")({ head: () => ({ meta: [{ title: "Paketlerimiz — MySkyParcel" }, { name: "description", content: "Dijital Parsel Sertifika 199 TL, Elit Parsel Sertifika 499 TL, Premium Parsel Sertifika 999 TL. Gökyüzü parselini seç, sana uygun seçeneği belirle." }, { property: "og:title", content: "Paketlerimiz — MySkyParcel" }, { property: "og:description", content: "Gökyüzü parseli seçenekleri ve parsel sahipliğini belgeleyen sertifika seçenekleri." }] }), component: Paketler });

const PLANS: Array<{ name: string; tier: CertificateTier; price: string; popular: boolean; features: string[] }> = [
  { name: "DİJİTAL PARSEL SERTİFİKA", tier: "digital", price: "199", popular: false, features: ["Dijital parsel sertifikası", "Parsel kodu ve koordinatlar", "QR doğrulama", "E-posta ile anında teslim"] },
  { name: "ELİT PARSEL SERTİFİKA", tier: "elite", price: "499", popular: true, features: ["Elit tasarım parsel sertifikası", "Kaliteli A4 Kuşe Kâğıt Baskı", "Dijital parsel sertifikası", "Parsel kodu ve koordinatlar", "QR doğrulama", "E-posta ile anında teslim", "Posta yoluyla gönderim"] },
  { name: "PREMİUM PARSEL SERTİFİKA", tier: "premium", price: "999", popular: false, features: ["Premium tasarım parsel sertifikası", "A4 Premium Dokulu Kâğıt", "Çerçeveli baskı (A4)", "Dijital parsel sertifikası", "Parsel kodu ve koordinatlar", "QR doğrulama", "Posta yoluyla gönderim"] },
];

const BENEFITS = [{ icon: Star, title: "BENZERSİZ PARSEL", text: "Milyonlarca sembolik parsel içinden sana özel olanı seç." }, { icon: ShieldCheck, title: "PARSEL SAHİPLİK SERTİFİKASI", text: "Seçtiğin parseli belgeleyen kişiye özel dijital sertifikanı oluştur." }, { icon: CloudDownload, title: "DİJİTAL & FİZİKSEL", text: "Parsel sertifikanı dijital olarak al, istersen fiziksel baskıyı kapına getirelim." }, { icon: Lock, title: "GÜVENLİ & ŞEFFAF", text: "Parsel seçim ve sipariş süreçleri için güvenli altyapı." }, { icon: Heart, title: "ANLAMLI BİR HEDİYE", text: "Sevdiklerin için gökyüzünde sembolik ve kişiye özel bir parsel seç." }];

function Paketler() { return <div className="starfield min-h-screen"><SiteHeader /><main className="mx-auto max-w-[1600px] px-4 py-10 sm:py-14 lg:px-8"><div className="text-center"><h1 className="font-display text-3xl font-bold sm:text-5xl">PARSEL PAKETLERİMİZ</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">Gökyüzünde parselini seç. Anlamlı bir hediye ile sevdiklerine unutulmaz bir deneyim yaşat.<br />Dijital, Elit ve Premium olmak üzere 3 farklı parsel statüsünden sana en uygun olanı seç, gökyüzündeki yerini kendine özel bir anıya dönüştür.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{PLANS.map((p) => <article key={p.name} className={`panel relative flex h-full min-w-0 flex-col p-5 sm:p-7 ${p.popular ? "border-gold/70" : ""}`}>{p.popular && <span className="btn-gold absolute -top-3 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full px-4 py-1 text-[10px]">EN POPÜLER</span>}<h2 className="text-center font-display text-lg sm:text-xl">{p.name}</h2><p className="mt-2 text-center text-xs text-muted-foreground">Parselini seç, sertifika seçeneğini belirle</p><p className="mt-2 text-center font-display text-3xl text-gold sm:text-4xl">{p.price} <span className="text-lg">TL</span></p><button type="button" aria-label={`${p.name} görselini büyüt`} onClick={() => window.open(CERTIFICATE_TEMPLATE_IMAGES[p.tier], "_blank", "noopener,noreferrer")} className="group relative mt-5 flex aspect-[3/2] w-full cursor-zoom-in items-center justify-center overflow-hidden rounded-lg bg-[#06162f] p-1.5 sm:mt-6 sm:p-2"><img src={CERTIFICATE_TEMPLATE_IMAGES[p.tier]} alt={`${p.name} şablonu — büyütmek için tıklayın`} loading="eager" fetchPriority="high" decoding="async" width={768} height={512} className="block h-full w-full object-contain object-center transition-transform duration-200 group-hover:scale-[1.02]" /></button><ul className="mt-5 space-y-3 text-sm sm:mt-6">{p.features.map((f) => <li key={f} className="flex items-start gap-2 text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-gold" /><span>{f}</span></li>)}</ul><Link to="/gokyuzu-haritasi" className="btn-gold mt-6 flex min-h-11 items-center justify-center gap-3 rounded-md py-3 text-sm sm:mt-auto">PARSELİ SEÇ <ArrowRight className="h-4 w-4" /></Link></article>)}</div><div className="panel mt-10 grid gap-6 p-5 sm:grid-cols-2 sm:p-7 lg:grid-cols-5">{BENEFITS.map((b) => <div key={b.title} className="flex min-w-0 items-start gap-3"><b.icon className="mt-0.5 h-6 w-6 shrink-0 text-gold" /><div className="min-w-0"><p className="text-xs font-semibold tracking-[0.06em]">{b.title}</p><p className="mt-1 text-xs text-muted-foreground">{b.text}</p></div></div>)}</div></main><SiteFooter /></div>; }
