import { createFileRoute, Navigate } from "@tanstack/react-router";
import { Award, RefreshCw, Sparkles } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { UserSidebar } from "@/components/UserSidebar";
import { SECURITY_TRUST, TrustBar } from "@/components/TrustBar";
import { CertificateArtwork, CERTIFICATE_TEMPLATES } from "@/components/CertificateArtwork";
import { CERTIFICATE_TEMPLATE_FALLBACK } from "@/lib/certificateTemplate";
import { supabaseBrowser } from "@/lib/supabaseBrowser";
import { useAuth } from "@/hooks/useAuth";
import { useCallback, useEffect, useState } from "react";

export const Route = createFileRoute("/sertifikalarim")({ head: () => ({ meta: [{ title: "Sertifikalarım — MySkyParcel" }, { name: "description", content: "MySkyParcel dijital sertifika taleplerini ve sertifika geçmişini görüntüle." }] }), component: Sertifikalarim });
type Certificate = { id: string; parcel_id: string; parcel?: { parcel_number?: string | null } | null; tier: "digital" | "elite" | "premium"; status: "requested" | "approved" | "issued" | "rejected" | "revoked"; certificate_number: string | null; requested_at: string; issued_at: string | null };
type OwnedParcel = { id: string; parcel_number: string; tier: "digital" | "elite" | "premium"; status: string };
const TIER_LABELS = { digital: "Dijital", elite: "Elit", premium: "Premium" } as const;
function getUserDisplayName(user: NonNullable<ReturnType<typeof useAuth>["user"]>) { const metadata = user.user_metadata as Record<string, unknown> | undefined; const fullName = typeof metadata?.full_name === "string" ? metadata.full_name.trim() : ""; if (fullName) return fullName; const name = typeof metadata?.name === "string" ? metadata.name.trim() : ""; if (name) return name; return user.email?.split("@")[0] || "MySkyParcel Koleksiyoncusu"; }
function Sertifikalarim() {
  const { user, loading: authLoading } = useAuth(); const [certificates, setCertificates] = useState<Certificate[]>([]); const [ownedParcels, setOwnedParcels] = useState<OwnedParcel[]>([]); const [loading, setLoading] = useState(true); const [requestingParcel, setRequestingParcel] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const loadCertificates = useCallback(async () => { if (!user || !supabaseBrowser) { setCertificates([]); setOwnedParcels([]); setLoading(false); return; } setLoading(true); setError(null); const [{ data: certificateData, error: certificateError }, { data: parcelData, error: parcelError }] = await Promise.all([supabaseBrowser.from("certificate_requests").select("id,parcel_id,tier,status,certificate_number,requested_at,issued_at,parcel:parcels(parcel_number)").eq("user_id", user.id).order("requested_at", { ascending: false }), supabaseBrowser.from("parcels").select("id,parcel_number,tier,status").eq("owner_id", user.id).eq("status", "sold").order("parcel_number", { ascending: true })]); if (certificateError) { console.error("Certificate query failed", certificateError); setError("Sertifika kayıtları yüklenemedi."); } else setCertificates((certificateData as Certificate[]) ?? []); if (parcelError) console.error("Owned parcel query failed", parcelError); else setOwnedParcels((parcelData as OwnedParcel[]) ?? []); setLoading(false); }, [user]);
  useEffect(() => { void loadCertificates(); }, [loadCertificates]);
  async function requestCertificate(parcel: OwnedParcel) { if (!supabaseBrowser || !user) return; setMessage(null); setError(null); setRequestingParcel(parcel.id); try { const { data, error: rpcError } = await supabaseBrowser.rpc("request_certificate_for_owned_parcel", { p_parcel_id: parcel.id }); if (rpcError) throw rpcError; const result = data as Certificate; setMessage(result.status === "issued" ? `${TIER_LABELS[parcel.tier]} sertifikanız sunucu tarafında oluşturuldu.` : `${TIER_LABELS[parcel.tier]} sertifika talebiniz alındı ve güvenli sunucu akışına aktarıldı.`); await loadCertificates(); } catch (err) { console.error("Certificate request failed", err); const code = err instanceof Error ? err.message : String(err); if (code.includes("parcel_not_owned")) setMessage("Bu parselin sahibi değilsiniz veya parsel satış durumunda değil."); else if (code.includes("invalid_parcel_tier")) setMessage("Parselin sertifika seviyesi geçersiz."); else setError("Sertifika talebi oluşturulamadı. Lütfen tekrar deneyin."); } finally { setRequestingParcel(null); } }
  if (authLoading) return <div className="starfield min-h-screen" aria-busy="true" />; if (!user) return <Navigate to="/giris" replace />;
  const displayName = getUserDisplayName(user); const certificateParcelIds = new Set(certificates.filter((c) => c.status !== "revoked").map((c) => c.parcel_id));
  return <div className="starfield min-h-screen"><SiteHeader /><main className="mx-auto grid max-w-[1600px] gap-6 px-4 py-8 lg:grid-cols-[260px_1fr] lg:px-8"><UserSidebar active="/sertifikalarim" /><div className="min-w-0">
    <div className="panel flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="font-display text-3xl font-bold">SERTİFİKALARIM</h1><p className="mt-2 text-xs text-muted-foreground">Sahibi olduğunuz parsel için sertifika talebi güvenli sunucu tarafı doğrulamasından geçer.</p></div><button type="button" onClick={() => void loadCertificates()} className="rounded-md border border-input px-3 py-2 text-xs hover:bg-accent" aria-label="Sertifikaları yenile"><RefreshCw className="mr-2 inline h-3.5 w-3.5" /> Yenile</button></div>
    {message && <div className="panel mt-6 border-gold/30 p-4 text-sm text-gold" role="status">{message}</div>}{error && <div className="panel mt-6 p-6 text-sm text-red-300" role="alert">{error}</div>}
    <section className="panel mt-6 p-5"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5 text-gold" /><div><h2 className="font-display text-xl">SERTİFİKA ŞABLONLARIMIZ</h2><p className="mt-1 text-xs text-muted-foreground">Sertifika tasarımları istemci tarafında yalnızca görüntülenir; resmi sertifika kaydı sunucu tarafında güvenli RPC ile oluşturulur.</p></div></div><div className="mt-5 grid gap-5 lg:grid-cols-3">{CERTIFICATE_TEMPLATES.map((template) => <div key={template.tier} className="overflow-hidden rounded-xl border border-gold/20 bg-background/30"><img src={template.src} alt={`${template.label} boş şablonu`} onError={(event) => { const img = event.currentTarget; if (img.dataset.fallbackApplied === "true") return; img.dataset.fallbackApplied = "true"; img.src = CERTIFICATE_TEMPLATE_FALLBACK; }} className="block aspect-[1600/1067] w-full object-cover" loading="lazy" /><div className="p-3"><p className="font-display text-sm">{template.label}</p><p className="mt-1 text-[11px] text-muted-foreground">Görüntüleme şablonu • Resmi veri sunucudan gelir</p></div></div>)}</div></section>
    {!loading && !error && ownedParcels.length > 0 && <section className="panel mt-6 p-5"><div className="flex items-center gap-3"><Sparkles className="h-5 w-5 text-gold" /><div><h2 className="font-display text-xl">PARSELLERİNİZ İÇİN SERTİFİKA TALEBİ</h2><p className="mt-1 text-xs text-muted-foreground">Parsel sahipliği ve sertifika üretimi sunucu tarafında doğrulanır.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{ownedParcels.map((parcel) => { const alreadyIssued = certificateParcelIds.has(parcel.id); return <div key={parcel.id} className="rounded-xl border border-gold/20 bg-background/30 p-4"><p className="font-display text-lg">{parcel.parcel_number}</p><p className="mt-1 text-xs text-gold">{TIER_LABELS[parcel.tier]} Gökyüzü Sertifikası</p><button type="button" onClick={() => void requestCertificate(parcel)} disabled={alreadyIssued || requestingParcel === parcel.id} className="btn-gold mt-4 w-full rounded-md py-2.5 text-xs disabled:cursor-not-allowed disabled:opacity-50">{requestingParcel === parcel.id ? "GÜVENLİ AKIŞ ÇALIŞIYOR..." : alreadyIssued ? "SERTİFİKA KAYDI MEVCUT" : "SERTİFİKA TALEP ET"}</button></div>; })}</div></section>}
    {loading && <div className="panel mt-6 p-6 text-sm text-muted-foreground">Sertifikalar yükleniyor...</div>}{!loading && !error && certificates.length === 0 && <div className="panel mt-6 p-8 text-center"><Award className="mx-auto h-12 w-12 text-gold" /><h2 className="mt-4 font-display text-xl">Henüz sertifika yok</h2><p className="mx-auto mt-2 max-w-lg text-sm text-muted-foreground">Sahibi olduğunuz satılmış bir parsel varsa yukarıdaki güvenli sertifika talep akışını kullanabilirsiniz.</p></div>}{!loading && !error && certificates.length > 0 && <ul className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{certificates.map((certificate) => { const parcelNumber = certificate.parcel?.parcel_number || certificate.parcel_id; return <li key={certificate.id} className="panel overflow-hidden p-4"><CertificateArtwork tier={certificate.tier} name={displayName} parcelCode={parcelNumber} certificateNumber={certificate.certificate_number} issuedAt={certificate.issued_at} /><div className="p-2 pt-4"><p className="font-display text-lg">{TIER_LABELS[certificate.tier]} Sertifika</p><p className="text-xs text-gold">Parsel: {parcelNumber}</p><p className="mt-2 text-[11px] text-muted-foreground">Durum: {certificate.status} · Talep: {new Date(certificate.requested_at).toLocaleDateString("tr-TR")}</p>{certificate.certificate_number && <p className="mt-1 text-[11px] text-muted-foreground">Sertifika No: {certificate.certificate_number}</p>}</div></li>; })}</ul>}
  </div></main><TrustBar items={SECURITY_TRUST} /><SiteFooter /></div>;
}
