import { useEffect, useState } from "react";
import { supabaseBrowser } from "@/lib/supabaseBrowser";
import { CertificateArtwork } from "@/components/CertificateArtwork";

type Row = Record<string, any>;
const TIER_LABELS = { digital: "Dijital", elite: "Elit", premium: "Premium" } as const;
const TIER_IMAGES = { digital: "/sertifikalar/standart-sablon.jpg", elite: "/sertifikalar/elit-sablon.jpg", premium: "/sertifikalar/premium-sablon.jpg" } as const;

export function AdminCertificateOverride() {
  const [parcelQuery, setParcelQuery] = useState(""); const [userQuery, setUserQuery] = useState(""); const [parcels, setParcels] = useState<Row[]>([]); const [users, setUsers] = useState<Row[]>([]); const [parcelId, setParcelId] = useState(""); const [userId, setUserId] = useState(""); const [tier, setTier] = useState("digital"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [certificates, setCertificates] = useState<Row[]>([]); const [selectedCertificate, setSelectedCertificate] = useState<Row | null>(null); const [certificateName, setCertificateName] = useState(""); const [certificateParcel, setCertificateParcel] = useState(""); const [certificateLatitude, setCertificateLatitude] = useState<number | null>(null); const [certificateLongitude, setCertificateLongitude] = useState<number | null>(null);

  async function loadCertificates() { if (!supabaseBrowser) return; const { data, error: rpcError } = await supabaseBrowser.rpc("admin_list_certificates", { p_limit: 100, p_offset: 0 }); if (!rpcError) setCertificates(((data ?? []) as Row[]).filter((certificate) => certificate.admin_issued === true)); }
  useEffect(() => { void loadCertificates(); }, []);
  async function searchParcels() { if (!supabaseBrowser) return; setError(""); setMessage(""); const { data, error } = await supabaseBrowser.rpc("admin_search_parcels_for_certificate", { p_query: parcelQuery.trim() || null }); if (error) setError(error.message); else setParcels((data ?? []) as Row[]); }
  async function searchUsers() { if (!supabaseBrowser) return; setError(""); setMessage(""); const { data, error } = await supabaseBrowser.rpc("admin_search_users_for_certificate", { p_query: userQuery.trim() || null }); if (error) setError(error.message); else setUsers((data ?? []) as Row[]); }
  async function createCertificate() { if (!supabaseBrowser || !parcelId || !userId) return; setBusy(true); setError(""); setMessage(""); const { error } = await supabaseBrowser.rpc("admin_create_certificate_for_parcel", { p_parcel_id: parcelId, p_user_id: userId, p_tier: tier }); if (error) setError(error.message); else { setMessage("Sertifika oluşturuldu. Parsel yönetici hesabına tahsis edildi ve artık başka bir kullanıcı tarafından satın alınamaz."); setParcelId(""); await searchParcels(); await loadCertificates(); } setBusy(false); }
  async function openCertificate(certificate: Row) { setSelectedCertificate(certificate); setCertificateName(""); setCertificateParcel(""); setCertificateLatitude(null); setCertificateLongitude(null); if (!supabaseBrowser) return; const [{ data: profile }, { data: parcel }] = await Promise.all([supabaseBrowser.from("profiles").select("full_name").eq("id", certificate.user_id).maybeSingle(), supabaseBrowser.from("parcels").select("parcel_number,latitude,longitude").eq("id", certificate.parcel_id).maybeSingle()]); setCertificateName(profile?.full_name?.trim() || "Ad Soyad"); setCertificateParcel(parcel?.parcel_number || certificate.parcel_id || "—"); setCertificateLatitude(typeof parcel?.latitude === "number" ? parcel.latitude : null); setCertificateLongitude(typeof parcel?.longitude === "number" ? parcel.longitude : null); }

  return <div className="space-y-5">
    <div className="panel p-5"><h2 className="font-semibold">Admin Sertifika Baskısı</h2><p className="mt-2 text-xs text-muted-foreground">Admin, gerçek bir parseli seçip mevcut bir kullanıcı adına Dijital, Elit veya Premium sertifika oluşturabilir. Sertifika oluşturulduğunda parsel admin hesabına tahsis edilir, satılmış olarak kilitlenir ve başka bir kullanıcı tarafından satın alınamaz. Sipariş veya ödeme kaydı oluşturulmaz.</p>
      {error && <div role="alert" className="mt-4 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-xs text-destructive">{error}</div>}{message && <div role="status" className="mt-4 rounded-md border border-gold/30 p-3 text-xs text-gold">{message}</div>}
      <div className="mt-5 grid gap-5 lg:grid-cols-2">
        <section className="rounded-lg border border-border p-4"><h3 className="text-sm font-semibold">1. Parsel seç</h3><form onSubmit={(e) => { e.preventDefault(); void searchParcels(); }} className="mt-3 flex gap-2"><input className="min-w-0 flex-1 rounded-md border bg-background p-2 text-sm" placeholder="Parsel numarası" value={parcelQuery} onChange={(e) => setParcelQuery(e.target.value)} /><button className="btn-gold rounded-md px-3 py-2 text-xs">Ara</button></form><div className="mt-3 max-h-64 space-y-2 overflow-auto">{parcels.map((p) => <button key={p.parcel_id} type="button" onClick={() => setParcelId(p.parcel_id)} className={`w-full rounded-md border p-3 text-left text-xs ${parcelId === p.parcel_id ? "border-gold bg-accent" : "border-border"}`}><div className="font-semibold">{p.parcel_number}</div><div className="mt-1 text-muted-foreground">Durum: {p.status} · Tier: {p.tier || "—"}</div><div className="text-muted-foreground">Sahibi: {p.owner_name || "—"}</div></button>)}</div></section>
        <section className="rounded-lg border border-border p-4"><h3 className="text-sm font-semibold">2. Sertifika sahibi seç</h3><form onSubmit={(e) => { e.preventDefault(); void searchUsers(); }} className="mt-3 flex gap-2"><input className="min-w-0 flex-1 rounded-md border bg-background p-2 text-sm" placeholder="Ad veya e-posta" value={userQuery} onChange={(e) => setUserQuery(e.target.value)} /><button className="btn-gold rounded-md px-3 py-2 text-xs">Ara</button></form><div className="mt-3 max-h-64 space-y-2 overflow-auto">{users.map((u) => <button key={u.user_id} type="button" onClick={() => setUserId(u.user_id)} className={`w-full rounded-md border p-3 text-left text-xs ${userId === u.user_id ? "border-gold bg-accent" : "border-border"}`}><div className="font-semibold">{u.full_name || "İsimsiz kullanıcı"}</div><div className="mt-1 text-muted-foreground">{u.email}</div></button>)}</div></section>
      </div>
      <div className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><div><label className="mb-1 block text-xs text-muted-foreground">Seçilen parsel</label><input readOnly className="w-full rounded-md border bg-muted p-2 text-sm" value={parcelId} placeholder="Parsel seçilmedi" /></div><div><label className="mb-1 block text-xs text-muted-foreground">Sertifika statüsü</label><select className="w-full rounded-md border bg-background p-2 text-sm" value={tier} onChange={(e) => setTier(e.target.value)}><option value="digital">Dijital Parsel Sertifika</option><option value="elite">Elit Parsel Sertifika</option><option value="premium">Premium Parsel Sertifika</option></select></div><button disabled={busy || !parcelId || !userId} onClick={() => void createCertificate()} className="btn-gold rounded-md px-5 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-50">{busy ? "OLUŞTURULUYOR..." : "SERTİFİKAYI OLUŞTUR"}</button></div>
    </div>
    <div className="panel p-5"><h2 className="font-semibold">Oluşturulan Admin Sertifikaları</h2><p className="mt-1 text-xs text-muted-foreground">Bir sertifikaya tıklayınca gerçek sertifika şablonu, parsel koordinatları, dinamik bilgiler ve PDF / YAZDIR seçenekleri açılır.</p>{!certificates.length && <p className="mt-4 text-sm text-muted-foreground">Henüz admin tarafından oluşturulmuş sertifika yok.</p>}{certificates.length > 0 && <div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{certificates.map((certificate) => <button key={certificate.id} type="button" onClick={() => void openCertificate(certificate)} className="overflow-hidden rounded-xl border border-gold/20 bg-background/30 text-left transition hover:border-gold hover:shadow-lg"><div className="aspect-[1600/1067] overflow-hidden"><img src={TIER_IMAGES[certificate.tier as keyof typeof TIER_IMAGES]} alt={`${TIER_LABELS[certificate.tier as keyof typeof TIER_LABELS] || certificate.tier} sertifika`} className="h-full w-full object-cover" /></div><div className="p-3"><p className="font-semibold text-gold">{certificate.certificate_number || "Sertifika"}</p><p className="mt-1 text-xs">{TIER_LABELS[certificate.tier as keyof typeof TIER_LABELS] || certificate.tier}</p><p className="mt-1 text-[11px] text-muted-foreground">Sertifikayı görmek için tıklayın</p></div></button>)}</div>}</div>
    {selectedCertificate && <div className="fixed inset-0 z-50 overflow-auto bg-black/80 p-4 sm:p-8" role="dialog" aria-modal="true" aria-label="Sertifika önizleme"><div className="mx-auto max-w-6xl rounded-xl bg-background p-4 shadow-2xl sm:p-6"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="font-display text-xl font-semibold">{TIER_LABELS[selectedCertificate.tier as keyof typeof TIER_LABELS] || selectedCertificate.tier} Parsel Sertifikası</h2><p className="mt-1 text-xs text-muted-foreground">{certificateParcel}</p></div><button type="button" onClick={() => setSelectedCertificate(null)} className="rounded-md border border-border px-3 py-2 text-xs hover:border-gold">Kapat</button></div><CertificateArtwork tier={selectedCertificate.tier} name={certificateName} parcelCode={certificateParcel} certificateNumber={selectedCertificate.certificate_number} issuedAt={selectedCertificate.issued_at || selectedCertificate.requested_at} cityName={certificateParcel.includes("-") ? certificateParcel.split("-")[0] : undefined} latitude={certificateLatitude} longitude={certificateLongitude} /></div></div>}
  </div>;
}
