import { Camera, Compass, LocateFixed, RefreshCw, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { supabaseBrowser } from "@/lib/supabaseBrowser";

type Gps={latitude:number;longitude:number;accuracy:number|null};
type Point=[number,number];
type Parcel={id:string;parcel_number:string;polygon:Point[];latitude:number;longitude:number;distance:number;bearing:number};
type Orientation={heading:number|null;pitch:number;roll:number;absolute:boolean;source:string};
const R=6371000, SEARCH=5000;
const norm=(n:number)=>((n%360)+360)%360;
const rad=(n:number)=>n*Math.PI/180;
const hav=(a:Gps,b:{latitude:number;longitude:number})=>{const p1=rad(a.latitude),p2=rad(b.latitude),d1=p2-p1,d2=rad(b.longitude-a.longitude);const h=Math.sin(d1/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(h)))};
const bearing=(a:Gps,b:{latitude:number;longitude:number})=>{const p1=rad(a.latitude),p2=rad(b.latitude),dl=rad(b.longitude-a.longitude);return norm(Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))*180/Math.PI)};
function centroid(p:Point[]):Point{if(p.length<3)return p[0]??[0,0];let a=0,x=0,y=0;for(let i=0;i<p.length-1;i++){const [x1,y1]=p[i],[x2,y2]=p[i+1],f=x1*y2-x2*y1;a+=f;x+=(x1+x2)*f;y+=(y1+y2)*f}if(Math.abs(a)<1e-12)return p[0];return[x/(3*a),y/(3*a)]}
function parseGeometry(raw:unknown):Point[]{if(!raw)return[];if(typeof raw==='object'){const v=raw as any,g=v.type==='Feature'?v.geometry:v;if(g?.type==='Polygon'&&Array.isArray(g.coordinates?.[0]))return g.coordinates[0].map((p:any)=>[+p[0],+p[1]] as Point).filter(p=>p.every(Number.isFinite))}const s=String(raw).trim();if(/^POLYGON/i.test(s)){const b=s.replace(/^POLYGON\s*\(\(/i,'').replace(/\)\)\s*$/,'');return b.split(',').map(q=>q.trim().split(/\s+/).slice(0,2).map(Number) as Point).filter(p=>p.every(Number.isFinite))}if(s.startsWith('{'))try{return parseGeometry(JSON.parse(s))}catch{return[]}return[]}
function readOrientation(e:DeviceOrientationEvent){const v=e as DeviceOrientationEvent&{webkitCompassHeading?:number};let h:number|null=null;if(typeof v.webkitCompassHeading==='number')h=norm(v.webkitCompassHeading);else if(typeof e.alpha==='number')h=norm(360-e.alpha);const hasTilt=typeof e.beta==='number'||typeof e.gamma==='number';if(h===null&&!hasTilt)return null;const a=window.screen.orientation?.angle??0;if(h!==null&&!v.webkitCompassHeading){if(a===90)h=norm(h+90);else if(a===180)h=norm(h+180);else if(a===270)h=norm(h-90)}return{heading:h,pitch:typeof e.beta==='number'?e.beta-90:0,roll:typeof e.gamma==='number'?e.gamma:0,absolute:e.absolute===true||e.type==='deviceorientationabsolute',source:v.webkitCompassHeading?'iOS pusula':e.absolute?'Android mutlak pusula':h!==null?'Telefon yön sensörü':'Hareket sensörü'} }
async function sensorPermission(){const D=window.DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<PermissionState>};const M=(window as any).DeviceMotionEvent as {requestPermission?:()=>Promise<PermissionState>}|undefined;try{if(typeof D.requestPermission==='function'&&(await D.requestPermission())!=='granted')return false;if(typeof M?.requestPermission==='function'&&(await M.requestPermission())!=='granted')return false;return true}catch{return false}}
function enu(origin:Gps,p:Point){const lat=rad(origin.latitude),east=rad(p[0]-origin.longitude)*R*Math.cos(lat),north=rad(p[1]-origin.latitude)*R;return new THREE.Vector3(east,0,-north)}

export function SkyScanExperienceV10(){
 const video=useRef<HTMLVideoElement>(null),mount=useRef<HTMLDivElement>(null),stream=useRef<MediaStream|null>(null),watch=useRef<number|null>(null),gpsRef=useRef<Gps|null>(null),lastLoadedGps=useRef<Gps|null>(null),loadingRef=useRef(false),sceneRef=useRef<{scene:THREE.Scene;camera:THREE.PerspectiveCamera;renderer:THREE.WebGLRenderer;root:THREE.Group;labels:THREE.Group;raf:number}|null>(null),orientationRef=useRef<Orientation>({heading:null,pitch:0,roll:0,absolute:false,source:'Sensör başlatılıyor'});
 const[orientation,setOrientation]=useState<Orientation>(orientationRef.current),[gps,setGps]=useState<Gps|null>(null),[parcels,setParcels]=useState<Parcel[]>([]),[started,setStarted]=useState(false),[cameraOn,setCameraOn]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[status,setStatus]=useState('Hazır'),[sensorState,setSensorState]=useState('Sensör başlatılıyor');
 const load=useCallback(async(pos:Gps)=>{if(loadingRef.current)return;loadingRef.current=true;setLoading(true);setError(null);setStatus('Parseller yükleniyor…');try{const city=await supabaseBrowser.from('cities').select('id').eq('slug','gaziantep').eq('is_active',true).maybeSingle();if(city.error||!city.data)throw city.error??new Error('Gaziantep ili bulunamadı.');const dLat=SEARCH/111320,dLon=SEARCH/Math.max(111320*Math.cos(rad(pos.latitude)),1);const q=await supabaseBrowser.from('sky_scan_parcels').select('id,parcel_id,parcel_number,latitude,longitude,parcels!sky_scan_parcels_parcel_id_fkey(geometry)').eq('city_id',city.data.id).gte('latitude',pos.latitude-dLat).lte('latitude',pos.latitude+dLat).gte('longitude',pos.longitude-dLon).lte('longitude',pos.longitude+dLon).limit(2000);if(q.error)throw q.error;const rows=(q.data??[]).map((r:any)=>{const poly=parseGeometry(r.parcels?.geometry);const c=poly.length>=3?centroid(poly):[+r.longitude,+r.latitude] as Point;const t={latitude:c[1],longitude:c[0]};return{id:String(r.parcel_id??r.id),parcel_number:String(r.parcel_number??'—'),polygon:poly,latitude:t.latitude,longitude:t.longitude,distance:hav(pos,t),bearing:bearing(pos,t)}}).filter((p:Parcel)=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)&&p.distance<=SEARCH).sort((a:Parcel,b:Parcel)=>a.distance-b.distance).slice(0,150);setParcels(rows);lastLoadedGps.current=pos;setStatus(rows.length?`${rows.length} parsel bulundu`:'Parsel bulunamadı');if(!rows.length)setError('Bu konumun 5 km çevresinde parsel bulunamadı.')}catch(e){setError(e instanceof Error?e.message:'Parseller alınamadı.');setStatus('Parsel sorgusu tamamlanamadı')}finally{loadingRef.current=false;setLoading(false)}},[]);
 const buildScene=useCallback((pos:Gps,items:Parcel[])=>{const el=mount.current;if(!el)return;sceneRef.current?.renderer.dispose();el.innerHTML='';const scene=new THREE.Scene(),cam=new THREE.PerspectiveCamera(65,el.clientWidth/Math.max(el.clientHeight,1),0.1,20000),renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.setClearColor(0,0);el.appendChild(renderer.domElement);const root=new THREE.Group(),labels=new THREE.Group();scene.add(root,labels);scene.add(new THREE.AmbientLight(0xffffff,1.8));items.forEach(parcel=>{if(parcel.polygon.length<3)return;const shape=new THREE.Shape();parcel.polygon.forEach((p,i)=>{const v=enu(pos,p);if(i===0)shape.moveTo(v.x,v.z);else shape.lineTo(v.x,v.z)});shape.closePath();const mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshBasicMaterial({color:0x22d3ee,transparent:true,opacity:.28,side:THREE.DoubleSide,depthWrite:false}));mesh.rotation.x=Math.PI;root.add(mesh);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:0x67e8f9,transparent:true,opacity:.95}));edges.rotation.copy(mesh.rotation);root.add(edges);const c=enu(pos,[parcel.longitude,parcel.latitude]);const text=document.createElement('canvas');text.width=320;text.height=80;const ctx=text.getContext('2d')!;ctx.fillStyle='rgba(0,0,0,.72)';ctx.roundRect(8,8,304,64,14);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 28px sans-serif';ctx.fillText(parcel.parcel_number,20,40);ctx.font='20px sans-serif';ctx.fillText(`${Math.round(parcel.distance)} m`,20,66);const tex=new THREE.CanvasTexture(text),sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));sp.position.set(c.x,3,c.z);sp.scale.set(10,2.5,1);labels.add(sp)});const resize=()=>{cam.aspect=el.clientWidth/Math.max(el.clientHeight,1);cam.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};window.addEventListener('resize',resize);let raf=0;const tick=()=>{raf=requestAnimationFrame(tick);const o=orientationRef.current;const h=o.heading===null?0:rad(o.heading);const pitch=rad(o.pitch);const roll=rad(o.roll);cam.rotation.order='YXZ';cam.rotation.set(pitch,-h,-roll);renderer.render(scene,cam)};tick();sceneRef.current={scene,camera:cam,renderer,root,labels,raf}},[]);
 useEffect(()=>{if(gps&&parcels.length&&mount.current)buildScene(gps,parcels)},[gps,parcels,buildScene]);
 const start=useCallback(async()=>{setStarted(true);setSensorState('Sensör izni kontrol ediliyor…');setStatus('Kamera, GPS ve sensörler başlatılıyor…');
  const initSensors=async()=>{const allowed=await sensorPermission();if(!allowed){setSensorState('Sensör izni verilmedi');return;}let orientationSeen=false,motionSeen=false;const onOrientation=(ev:Event)=>{const r=readOrientation(ev as DeviceOrientationEvent);if(!r)return;orientationSeen=true;orientationRef.current=r;setOrientation(r);setSensorState(r.heading!==null?(r.absolute?'Android mutlak pusula aktif':'Pusula + IMU aktif'):'Hareket sensörü aktif · pusula verisi bekleniyor')};const onMotion=()=>{motionSeen=true;if(!orientationSeen)setSensorState('Hareket sensörü aktif · pusula verisi bekleniyor')};window.addEventListener('deviceorientationabsolute',onOrientation,true);window.addEventListener('deviceorientation',onOrientation,true);window.addEventListener('devicemotion',onMotion,true);const cleanup=()=>{window.removeEventListener('deviceorientationabsolute',onOrientation,true);window.removeEventListener('deviceorientation',onOrientation,true);window.removeEventListener('devicemotion',onMotion,true)};(window as any).__skyScanSensorCleanup=cleanup;setSensorState('Sensör dinleniyor…');setTimeout(()=>{if(!orientationSeen&&!motionSeen)setSensorState('Sensör verisi alınamadı')},4000)};
  void initSensors();
  if(navigator.geolocation){watch.current=navigator.geolocation.watchPosition(p=>{const n={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:Number.isFinite(p.coords.accuracy)?p.coords.accuracy:null};const previous=gpsRef.current;gpsRef.current=n;setGps(n);const previousLoad=lastLoadedGps.current;const moved=previousLoad?hav(previousLoad,n):Infinity;const accuracyImproved=previous?.accuracy!=null&&n.accuracy!=null&&n.accuracy+10<previous.accuracy;if(!previousLoad||moved>100||accuracyImproved)void load(n)},e=>{setError(e.code===1?'Konum izni verilmedi.':'GPS verisi alınamadı.');setStatus('GPS alınamadı')},{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
  try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play();setCameraOn(true)}}catch(e){setError(e instanceof Error?e.message:'Kamera açılamadı.');setStatus('Kamera açılamadı')}
 },[load]);
 const stop=useCallback(()=>{if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;(window as any).__skyScanSensorCleanup?.();stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;sceneRef.current&&cancelAnimationFrame(sceneRef.current.raf);sceneRef.current?.renderer.dispose();sceneRef.current=null;loadingRef.current=false;lastLoadedGps.current=null;setStarted(false);setCameraOn(false);setSensorState('Sensör başlatılıyor')},[]);
 useEffect(()=>()=>stop(),[stop]);
 const sensorLabel=orientation.heading!==null?(orientation.absolute?'Mutlak pusula aktif':'Pusula + IMU aktif'):sensorState;
 return <div className="relative h-[100dvh] w-full overflow-hidden bg-black text-white"><video ref={video} playsInline muted className="absolute inset-0 h-full w-full object-cover"/><div ref={mount} className="pointer-events-none absolute inset-0 z-10"/><div className="absolute inset-x-0 top-0 z-20 p-3"><div className="mx-auto max-w-xl rounded-2xl bg-black/60 p-3 backdrop-blur-md"><div className="flex items-center justify-between"><div className="font-semibold flex items-center gap-2"><Camera className="h-5 w-5"/> 3B Sky Scan AR</div><button onClick={stop} className="rounded-full p-2"><X className="h-5 w-5"/></button></div><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><span>GPS: {gps?`${gps.accuracy?Math.round(gps.accuracy):'—'} m`:'—'}</span><span>Heading: {orientation.heading===null?'—':`${Math.round(orientation.heading)}°`}</span><span>Parsel: {parcels.length}</span></div><div className="mt-2 text-xs opacity-80">{parcels.length?`${parcels.length} parsel hazır · ${sensorLabel}`:status}<div className="mt-1 opacity-70">Sensör: {sensorLabel}</div></div>{error&&<div className="mt-2 rounded-xl bg-red-500/20 p-2 text-xs">{error}</div>}</div></div>{!started&&<div className="absolute inset-x-4 bottom-8 z-30 mx-auto max-w-xl"><button onClick={start} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-white px-5 py-4 font-bold text-black shadow-xl"><LocateFixed className="h-5 w-5"/> Gerçek AR taramasını başlat</button></div>}{started&&<div className="absolute bottom-4 left-3 right-3 z-20 flex items-center justify-between"><div className="rounded-full bg-black/60 px-4 py-2 text-sm backdrop-blur">{loading?'Parseller yükleniyor…':`${parcels.length} parsel hazır · ${sensorLabel}`}</div><button onClick={()=>gps&&load(gps)} className="rounded-full bg-black/60 p-3 backdrop-blur"><RefreshCw className="h-5 w-5"/></button></div>}<div className="absolute left-1/2 top-1/2 z-20 -translate-x-1/2 -translate-y-1/2 opacity-50"><Compass className="h-8 w-8"/></div></div>
}