import { Camera, Compass, LocateFixed, RefreshCw, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { supabaseBrowser } from "@/lib/supabaseBrowser";

type Gps={latitude:number;longitude:number;accuracy:number|null};
type Point=[number,number];
type Parcel={id:string;parcel_number:string;latitude:number;longitude:number;distance:number;bearing:number;polygon:Point[]};
type Orientation={heading:number|null;absolute:boolean;source:string;pitch:number|null};

const R=5000,E=6371000,FOV=110,VFOV=70;
const norm=(x:number)=>((x%360)+360)%360;
const rad=(x:number)=>x*Math.PI/180;
const delta=(target:number,heading:number)=>((target-heading+540)%360)-180;
const distance=(a:Gps,b:{latitude:number;longitude:number})=>{const p=rad(a.latitude),q=rad(b.latitude),dp=q-p,dl=rad(b.longitude-a.longitude),h=Math.sin(dp/2)**2+Math.cos(p)*Math.cos(q)*Math.sin(dl/2)**2;return 2*E*Math.asin(Math.min(1,Math.sqrt(h)))};
const bearing=(a:Gps,b:{latitude:number;longitude:number})=>{const p=rad(a.latitude),q=rad(b.latitude),dl=rad(b.longitude-a.longitude);return norm(Math.atan2(Math.sin(dl)*Math.cos(q),Math.cos(p)*Math.sin(q)-Math.sin(p)*Math.cos(q)*Math.cos(dl))*180/Math.PI)};
const direction=(x:number)=>["K","KD","D","GD","G","GB","B","KB"][Math.round(norm(x)/45)%8];
const pointIn=(p:Point,ring:Point[])=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const[xi,yi]=ring[i],[xj,yj]=ring[j];const hit=((yi>p[1])!==(yj>p[1]))&&p[0]<(xj-xi)*(p[1]-yi)/((yj-yi)||Number.EPSILON)+xi;if(hit)inside=!inside}return inside};
const centroid=(ring:Point[]):Point=>{if(ring.length<3)return ring[0]??[0,0];let area=0,cx=0,cy=0;for(let i=0;i<ring.length-1;i++){const[x1,y1]=ring[i],[x2,y2]=ring[i+1],f=x1*y2-x2*y1;area+=f;cx+=(x1+x2)*f;cy+=(y1+y2)*f}if(Math.abs(area)<1e-12){const pts=ring.slice(0,-1);return pts.reduce((s,p)=>[s[0]+p[0],s[1]+p[1]],[0,0]).map(v=>v/Math.max(pts.length,1)) as Point}return[cx/(3*area),cy/(3*area)]};
const representative=(ring:Point[]):Point=>{const c=centroid(ring);if(pointIn(c,ring))return c;const pts=ring.slice(0,-1);const a=pts.reduce((s,p)=>[s[0]+p[0],s[1]+p[1]],[0,0]).map(v=>v/Math.max(pts.length,1)) as Point;return pointIn(a,ring)?a:(pts[0]??c)};
const parseGeometry=(raw:any):Point[]=>{if(!raw)return[];if(typeof raw==="object"){const g=raw.type==="Feature"?raw.geometry:raw;if(g?.type==="Polygon"&&Array.isArray(g.coordinates?.[0]))return g.coordinates[0].map((p:number[])=>[Number(p[0]),Number(p[1])] as Point).filter(p=>p.every(Number.isFinite))}const s=String(raw).trim();if(/^POLYGON/i.test(s)){const body=s.replace(/^POLYGON\s*\(\(/i,"").replace(/\)\)\s*$/i,"");return body.split(",").map(v=>v.trim().split(/\s+/).slice(0,2).map(Number) as Point).filter(p=>p.every(Number.isFinite))}if(s.startsWith("{")){try{return parseGeometry(JSON.parse(s))}catch{return[]}}return[]};
const readOrientation=(e:DeviceOrientationEvent)=>{const x=e as DeviceOrientationEvent&{webkitCompassHeading?:number};if(typeof x.webkitCompassHeading==="number"&&Number.isFinite(x.webkitCompassHeading))return{heading:norm(x.webkitCompassHeading),absolute:true,source:"iOS pusula"};if(typeof e.alpha!=="number"||!Number.isFinite(e.alpha))return null;let h=norm(360-e.alpha);const a=screen.orientation?.angle??0;if(a===90)h=norm(h+90);else if(a===180)h=norm(h+180);else if(a===270)h=norm(h-90);return{heading:h,absolute:e.absolute===true||e.type==="deviceorientationabsolute",source:e.absolute===true||e.type==="deviceorientationabsolute"?"Android mutlak pusula":"Telefon yön sensörü"}};
async function requestSensorPermission(){const D=window.DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<PermissionState>};if(typeof D.requestPermission==="function"&&(await D.requestPermission())!=="granted")return false;return true}

export function SkyScanExperienceV10(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),watch=useRef<number|null>(null),gpsRef=useRef<Gps|null>(null),lastFetch=useRef(0),seq=useRef(0);
 const[o,setO]=useState<Orientation>({heading:null,absolute:false,source:"Bekleniyor",pitch:null});
 const[gps,setGps]=useState<Gps|null>(null),[parcels,setParcels]=useState<Parcel[]>([]),[loading,setLoading]=useState(false),[started,setStarted]=useState(false),[camera,setCamera]=useState(false),[status,setStatus]=useState("Başlatılmayı bekliyor"),[error,setError]=useState<string|null>(null);
 const load=useCallback(async(p:Gps,force=false)=>{const now=Date.now();if(!force&&now-lastFetch.current<4000)return;lastFetch.current=now;const token=++seq.current;setLoading(true);setError(null);const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),9000);try{const city=await supabaseBrowser.from("cities").select("id").eq("slug","gaziantep").eq("is_active",true).maybeSingle().abortSignal(controller.signal);if(city.error||!city.data)throw city.error??new Error("Gaziantep ili bulunamadı.");const latD=R/111320,lonD=R/Math.max(111320*Math.cos(rad(p.latitude)),1);const q=await supabaseBrowser.from("sky_scan_parcels").select("id,parcel_id,parcel_number,latitude,longitude,parcels!sky_scan_parcels_parcel_id_fkey(geometry)").eq("city_id",city.data.id).gte("latitude",p.latitude-latD).lte("latitude",p.latitude+latD).gte("longitude",p.longitude-lonD).lte("longitude",p.longitude+lonD).limit(2000).abortSignal(controller.signal);if(q.error)throw q.error;const rows=(q.data??[]).map((x:any)=>{const polygon=parseGeometry(x.parcels?.geometry);const fallback={latitude:Number(x.latitude),longitude:Number(x.longitude)};const rep=polygon.length>=3?representative(polygon):[fallback.longitude,fallback.latitude] as Point;const target={latitude:Number(rep[1]),longitude:Number(rep[0])};return{id:String(x.parcel_id??x.id),parcel_number:String(x.parcel_number??"—"),...target,polygon,distance:distance(p,target),bearing:bearing(p,target)}}).filter(x=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)&&x.distance<=R).sort((a,b)=>a.distance-b.distance).slice(0,300);if(token===seq.current){setParcels(rows);if(!rows.length)setError("Bu konumun 5 km çevresinde Sky Scan parseli bulunamadı.")}}catch(e){if(token===seq.current)setError(e instanceof DOMException&&e.name==="AbortError"?"Parsel sorgusu zaman aşımına uğradı.":e instanceof Error?e.message:"Parseller alınamadı.")}finally{clearTimeout(timer);if(token===seq.current)setLoading(false)}},[]);
 const startSensors=useCallback(async()=>{setStatus("Pusula başlatılıyor…");if(!(await requestSensorPermission())){setStatus("Sensör izni verilmedi");return}let absoluteLocked=false,received=false;const onOrientation=(ev:Event)=>{const e=ev as DeviceOrientationEvent,x=readOrientation(e);if(!x)return;if(absoluteLocked&&!x.absolute)return;if(x.absolute)absoluteLocked=true;received=true;const beta=typeof e.beta==="number"&&Number.isFinite(e.beta)?e.beta-90:null;setO({heading:x.heading,absolute:x.absolute||absoluteLocked,source:x.source,pitch:beta});setStatus(x.absolute||absoluteLocked?"Pusula aktif":"Telefon yön sensörü aktif")};window.addEventListener("deviceorientationabsolute",onOrientation,true);window.addEventListener("deviceorientation",onOrientation,true);const cleanup=()=>{window.removeEventListener("deviceorientationabsolute",onOrientation,true);window.removeEventListener("deviceorientation",onOrientation,true)};window.setTimeout(()=>{if(!received)setStatus("Pusula verisi alınamadı — hedefler yön sensörü bekliyor")},6000);return cleanup},[]);
 const sensorCleanup=useRef<(()=>void)|null>(null);
 const start=useCallback(async()=>{setStarted(true);sensorCleanup.current?.();sensorCleanup.current=await startSensors();if(navigator.geolocation)watch.current=navigator.geolocation.watchPosition(pos=>{const p={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:Number.isFinite(pos.coords.accuracy)?pos.coords.accuracy:null};gpsRef.current=p;setGps(p);void load(p)},e=>setError(e.code===1?"Konum izni verilmedi.":"GPS verisi alınamadı."),{enableHighAccuracy:true,maximumAge:2000,timeout:15000});try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:false});stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play();setCamera(true)}}catch(e){setError(e instanceof Error?e.message:"Kamera açılamadı.")}},[load,startSensors]);
 const stop=useCallback(()=>{if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;sensorCleanup.current?.();sensorCleanup.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setStarted(false);setCamera(false)},[]);
 useEffect(()=>()=>stop(),[stop]);
 const projected=useMemo(()=>parcels.map(p=>{const dx=o.heading===null?null:delta(p.bearing,o.heading);if(dx!==null&&Math.abs(dx)>FOV/2)return null;const x=dx===null?50:50+dx/(FOV/2)*43;const elevation=-(Math.atan2(1.6,Math.max(p.distance,1))*180/Math.PI);const y=o.pitch===null?55:50-(elevation-o.pitch)/(VFOV/2)*40;return{...p,x,y,depth:Math.min(1,p.distance/R),dx}}).filter(Boolean) as Array<Parcel&{x:number;y:number;depth:number;dx:number|null}> ,[parcels,o.heading,o.pitch]);
 const polygonLines=useMemo(()=>projected.map(p=>{if(p.polygon.length<3||!gps)return null;const points=p.polygon.map(([lng,lat])=>{const b=bearing(gps,{latitude:lat,longitude:lng}),dd=distance(gps,{latitude:lat,longitude:lng}),dx=o.heading===null?0:delta(b,o.heading);const elevation=-(Math.atan2(1.6,Math.max(dd,1))*180/Math.PI);const x=50+Math.max(-FOV/2,Math.min(FOV/2,dx))/(FOV/2)*43;const y=o.pitch===null?55:50-(elevation-o.pitch)/(VFOV/2)*40;return[x,y] as Point});return{...p,points}},[projected,gps,o.heading,o.pitch]);
 const near=parcels[0],nearDelta=near&&o.heading!==null?delta(near.bearing,o.heading):null;
 return <main className="fixed inset-0 z-[70] overflow-hidden bg-black text-white"><video ref={video} muted playsInline autoPlay className="absolute inset-0 h-full w-full object-cover"/>
 {!started&&<div className="absolute inset-0 z-50 grid place-items-center bg-black/55"><button onClick={start} className="rounded-full border border-white/30 bg-white px-8 py-4 text-lg font-black text-black shadow-2xl">Gökyüzünü Tara</button></div>}
 <div className="pointer-events-none absolute inset-0 z-20 bg-[radial-gradient(ellipse_at_center,transparent_35%,rgba(0,0,0,.18)_70%,rgba(0,0,0,.55))]"/>
 <div className="pointer-events-none absolute left-0 right-0 top-[48%] z-20 border-t border-white/20"/><div className="pointer-events-none absolute left-1/2 top-[48%] z-20 h-24 w-px -translate-x-1/2 bg-white/20"/><div className="pointer-events-none absolute left-1/2 top-[48%] z-20 h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/70"/>
 <div className="absolute left-3 right-3 top-3 z-40 flex items-start justify-between"><div className="rounded-2xl border border-white/15 bg-black/45 px-3 py-2 text-xs backdrop-blur-md"><b>GÖKYÜZÜ TARAMA</b><div className="mt-1 flex gap-3 opacity-80"><span><Camera size={12} className="mr-1 inline"/>{camera?"Kamera":"—"}</span><span><LocateFixed size={12} className="mr-1 inline"/>{gps?`±${Math.round(gps.accuracy??0)}m`:"GPS…"}</span><span><Compass size={12} className="mr-1 inline"/>{o.heading===null?"Pusula…":`${Math.round(o.heading)}°`}</span></div></div><button onClick={stop} className="pointer-events-auto rounded-full border border-white/20 bg-black/50 p-2 backdrop-blur-md"><X size={18}/></button></div>
 {started&&<div className="pointer-events-none absolute inset-x-0 top-[11%] z-30 text-center"><div className="text-[10px] font-bold tracking-[.25em] text-white/60">{o.heading===null?"DÜNYA HEDEFLERİ YÜKLENİYOR":status.toUpperCase()}</div><div className="mt-1 text-xs text-white/75">{loading?"Parseller taranıyor…":`${parcels.length} parsel · 5 km çevre`}</div></div>}
 <svg className="pointer-events-none absolute inset-0 z-[28] h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none">{polygonLines.map((p,i)=>p&&<polygon key={`${p.id}-${i}`} points={p.points.map(([x,y])=>`${Math.max(2,Math.min(98,x))},${Math.max(15,Math.min(85,y))}`).join(" ")} fill="none" stroke="rgba(125,211,252,.8)" strokeWidth="0.18" vectorEffect="non-scaling-stroke"/>)}</svg>
 <div className="pointer-events-none absolute inset-0 z-30">{projected.map((p,i)=><div key={p.id} className="absolute -translate-x-1/2 -translate-y-1/2 transition-all duration-200" style={{left:`${Math.max(5,Math.min(95,p.x))}%`,top:`${Math.max(22,Math.min(78,p.y))}%`,transform:`translate(-50%,-50%) scale(${1.15-p.depth*.55})`}}><div className="relative flex flex-col items-center"><div className="absolute top-1/2 h-px w-20 -translate-y-1/2 bg-cyan-200/20"/><div className="h-3 w-3 rounded-full border border-cyan-100 bg-cyan-300/50 shadow-[0_0_22px_rgba(125,211,252,.9)]"/><div className="mt-1 whitespace-nowrap rounded-full border border-cyan-100/35 bg-black/30 px-2 py-1 text-[9px] font-bold tracking-wide backdrop-blur-sm"><span>{p.parcel_number}</span><span className="ml-1 font-normal opacity-80">{Math.round(p.distance)}m · {direction(p.bearing)}</span></div>{i<5&&<div className="mt-0.5 text-[8px] text-cyan-100/70">{Math.round(p.bearing)}°</div>}</div></div>)}</div>
 {parcels.length>0&&<div className="pointer-events-none absolute bottom-[13%] left-1/2 z-30 -translate-x-1/2 text-center"><div className="text-[10px] font-bold tracking-[.2em] text-white/55">{near?`${near.parcel_number} · ${Math.round(near.distance)} m · ${direction(near.bearing)}`:""}</div>{nearDelta!==null&&<div className="mt-1 text-sm font-black">{Math.abs(nearDelta)<10?"HEDEF ÖNÜNDE":nearDelta>0?`SAĞA → ${Math.round(Math.abs(nearDelta))}°`:`SOLA ← ${Math.round(Math.abs(nearDelta))}°`}</div>}</div>}
 <div className="pointer-events-none absolute bottom-4 left-1/2 z-40 -translate-x-1/2 rounded-full border border-white/15 bg-black/40 px-4 py-2 text-[9px] text-white/65 backdrop-blur-md">K 0° · KD 45° · D 90° · GD 135° · G 180° · GB 225° · B 270° · KB 315°</div>
 {error&&<div className="absolute left-1/2 top-20 z-50 -translate-x-1/2 rounded-xl bg-red-950/70 px-3 py-2 text-xs">{error}</div>}
 {started&&o.heading===null&&<div className="pointer-events-none absolute left-1/2 top-[66%] z-40 -translate-x-1/2 rounded-full border border-white/20 bg-black/45 px-4 py-2 text-[10px] text-white/75 backdrop-blur-md">Telefonu yavaşça döndür · yön sensörü aranıyor</div>}
 <button onClick={()=>gpsRef.current&&void load(gpsRef.current,true)} className="pointer-events-auto absolute bottom-4 right-3 z-50 rounded-full border border-white/20 bg-black/45 p-2 backdrop-blur-md"><RefreshCw size={16}/></button>
 </main>;
}
