import { Camera, Compass, Crosshair, MapPin, Navigation, ShoppingCart, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { bearingDegrees, distanceMeters, formatDistance, normalizeAngle, type GeoPoint } from "@/components/sky-scan/geo";
import { SkyScan3DLayer } from "@/components/sky-scan/SkyScan3DLayer";
import { supabaseBrowser } from "@/lib/supabaseBrowser";

type LocationState = GeoPoint & { accuracy: number; altitude: number | null };
type Parcel = { id:string; parcel_number:string; status:string; price:number|string|null; tier:string; tier_price:number|string|null; city_name:string; city_slug:string; latitude:number; longitude:number };
type Nearby = Parcel & { distance:number; bearing:number; altitude:number; east:number; north:number };
type OrientationLike = DeviceOrientationEvent & { webkitCompassHeading?: number };
type Projected = Nearby & { left:number; top:number; scale:number; opacity:number; depth:number; angle:number; targetPitch:number };
type MotionLike = DeviceMotionEvent;
type Projected3DHit = { id:string; x:number; y:number; visible:boolean };
const MAX_RANGE=8000,MIN_REFRESH_METERS=25,REFRESH_MS=2500,FETCH_LIMIT=300,MIN_VISIBLE=25,DEFAULT_FOV=110,EARTH_RADIUS=6371000,SKY_ENTER=7,SKY_EXIT=4;
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));const rad=(n:number)=>n*Math.PI/180;const deg=(n:number)=>n*180/Math.PI;
function haversine(a:GeoPoint,b:GeoPoint){return distanceMeters(a,b)}
function enu(a:GeoPoint,b:GeoPoint){const lat=rad((a.latitude+b.latitude)/2);return {east:rad(b.longitude-a.longitude)*EARTH_RADIUS*Math.cos(lat),north:rad(b.latitude-a.latitude)*EARTH_RADIUS}}
function stableAltitude(id:string){let h=2166136261;for(let i=0;i<id.length;i++)h=Math.imul(h^id.charCodeAt(i),16777619);return 150+(Math.abs(h)%351)}
function parcelScale(d:number){return clamp(2.05/Math.sqrt(d/1000+.65),.48,1.9)}
function pose(event:DeviceOrientationEvent){const alpha=rad(event.alpha??0),beta=rad(event.beta??0),gamma=rad(event.gamma??0),screenAngle=typeof screen!=="undefined"&&screen.orientation?Number(screen.orientation.angle)||0:0,ca=Math.cos(alpha),sa=Math.sin(alpha),sb=Math.sin(beta),cg=Math.cos(gamma),sg=Math.sin(gamma),x=ca*sg-sa*sb*cg,y=sb,z=ca*cg+sa*sb*sg;let heading=normalizeAngle(deg(Math.atan2(x,-z))-screenAngle);if(!Number.isFinite(heading))heading=0;return {heading,pitch:clamp(deg(Math.asin(clamp(y,-1,1))),-89,89)}}
function project(p:Nearby,l:LocationState,heading:number,pitch:number,fov:number,w:number,h:number):Projected|null{const rel=normalizeAngle(p.bearing-heading),verticalFov=clamp(fov*(h/Math.max(1,w)),72,105),targetPitch=deg(Math.atan2(p.altitude-(l.altitude??0),Math.max(30,p.distance))),relPitch=targetPitch-pitch;if(Math.abs(rel)>fov*.5||Math.abs(relPitch)>verticalFov*.5)return null;const uncertainty=clamp(l.accuracy/Math.max(50,p.distance),0,.75);return {...p,left:50+(rel/fov)*100,top:50-(relPitch/verticalFov)*100,scale:parcelScale(p.distance),opacity:clamp(.98-uncertainty*.35-p.distance/MAX_RANGE*.16,.42,.98),depth:Math.hypot(p.east,p.north,p.altitude-(l.altitude??0)),angle:rel,targetPitch}}
function money(value:number|string|null){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(n):"—"}
function directionLabel(degValue:number){const d=normalizeAngle(degValue);if(d<22.5||d>=337.5)return "K";if(d<67.5)return "KD";if(d<112.5)return "D";if(d<157.5)return "GD";if(d<202.5)return "G";if(d<247.5)return "GB";if(d<292.5)return "B";return "KB"}

export function SkyScanExperienceV4(){
  const rootRef=useRef<HTMLDivElement|null>(null),videoRef=useRef<HTMLVideoElement|null>(null),streamRef=useRef<MediaStream|null>(null),lastFetchRef=useRef<GeoPoint|null>(null),lastFetchAt=useRef(0),requestSeq=useRef(0),sensorMode=useRef<"absolute"|"relative"|null>(null),relativeBase=useRef<number|null>(null),absoluteGraceUntil=useRef(0);
  const [location,setLocation]=useState<LocationState|null>(null),[locationError,setLocationError]=useState<string|null>(null),[nearby,setNearby]=useState<Nearby[]>([]),[parcelLoading,setParcelLoading]=useState(false),[parcelError,setParcelError]=useState<string|null>(null),[heading,setHeading]=useState<number|null>(null),[pitch,setPitch]=useState<number|null>(null),[roll,setRoll]=useState(0),[cameraStarted,setCameraStarted]=useState(false),[cameraReady,setCameraReady]=useState(false),[cameraError,setCameraError]=useState<string|null>(null),[orientationStarted,setOrientationStarted]=useState(false),[orientationError,setOrientationError]=useState<string|null>(null),[sensorTick,setSensorTick]=useState(0),[selected,setSelected]=useState<Nearby|null>(null),[selected3DPosition,setSelected3DPosition]=useState<Projected3DHit|null>(null),[skyMode,setSkyMode]=useState(false),[fov,setFov]=useState(DEFAULT_FOV);
  useEffect(()=>{if(!navigator.geolocation){setLocationError("Bu cihaz konum bilgisini desteklemiyor.");return}const id=navigator.geolocation.watchPosition(p=>setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:Math.max(1,p.coords.accuracy||999),altitude:typeof p.coords.altitude==="number"?p.coords.altitude:null}),e=>setLocationError(e.message||"Konum alınamadı."),{enableHighAccuracy:true,maximumAge:1000,timeout:15000});return()=>navigator.geolocation.clearWatch(id)},[]);
  const fetchParcels=useCallback(async(l:LocationState,force=false)=>{if(!supabaseBrowser)return;const now=Date.now(),moved=lastFetchRef.current?haversine(lastFetchRef.current,l):Infinity;if(!force&&moved<MIN_REFRESH_METERS&&now-lastFetchAt.current<REFRESH_MS)return;const seq=++requestSeq.current;lastFetchRef.current={latitude:l.latitude,longitude:l.longitude};lastFetchAt.current=now;setParcelLoading(true);setParcelError(null);const radii=[1800,3500,5500,MAX_RANGE];let rows:Nearby[]=[];let lastError:string|null=null;for(const radiusMeters of radii){const latDelta=radiusMeters/111320,lngDelta=radiusMeters/(111320*Math.max(.2,Math.cos(rad(l.latitude))));const {data,error}=await supabaseBrowser.rpc("sky_scan_parcels",{p_min_lat:l.latitude-latDelta,p_min_lng:l.longitude-lngDelta,p_max_lat:l.latitude+latDelta,p_max_lng:l.longitude+lngDelta,p_limit:FETCH_LIMIT});if(seq!==requestSeq.current)return;if(error){lastError=error.message||"Yakındaki parseller alınamadı.";continue}rows=(data??[] as Parcel[]).map(p=>{const xy=enu(l,p);return {...p,distance:distanceMeters(l,p),bearing:bearingDegrees(l,p),altitude:(l.altitude??0)+stableAltitude(p.id),east:xy.east,north:xy.north}}).filter(p=>p.distance<=radiusMeters).sort((a,b)=>a.distance-b.distance);if(rows.length>=MIN_VISIBLE||radiusMeters===MAX_RANGE)break}if(seq!==requestSeq.current)return;if(!rows.length&&lastError){setParcelError(lastError);setNearby([]);setParcelLoading(false);return}setNearby(rows.slice(0,FETCH_LIMIT));setParcelLoading(false)},[]);
  useEffect(()=>{if(location)void fetchParcels(location,true)},[location?.latitude,location?.longitude,location?.accuracy,fetchParcels]);useEffect(()=>{if(!location)return;const timer=window.setInterval(()=>void fetchParcels(location),REFRESH_MS);return()=>window.clearInterval(timer)},[location,fetchParcels]);
  useEffect(()=>{if(!orientationStarted)return;let absoluteSeen=false,got=false;absoluteGraceUntil.current=Date.now()+700;const markSensor=()=>{got=true;setSensorTick(Date.now());setOrientationError(null)};const accept=(e:DeviceOrientationEvent,absolute:boolean)=>{const x=e as OrientationLike,hasAlpha=typeof e.alpha==="number",hasTilt=typeof e.beta==="number"&&typeof e.gamma==="number";if(!hasTilt)return;if(absolute){absoluteSeen=true;sensorMode.current="absolute";const raw=typeof x.webkitCompassHeading==="number"&&Number.isFinite(x.webkitCompassHeading)?x.webkitCompassHeading:pose(e).heading;setHeading(normalizeAngle(raw))}else if(!absoluteSeen&&sensorMode.current!=="absolute"&&Date.now()>=absoluteGraceUntil.current&&hasAlpha){sensorMode.current="relative";const raw=pose(e).heading;if(relativeBase.current===null)relativeBase.current=raw;setHeading(normalizeAngle(raw-relativeBase.current))}const q=pose(e);setPitch(v=>v===null?q.pitch:v*.8+q.pitch*.2);setRoll(clamp((e.gamma??0)*.25,-20,20));markSensor()};const onAbs=(e:Event)=>accept(e as DeviceOrientationEvent,true),onRel=(e:Event)=>accept(e as DeviceOrientationEvent,false),onMotion=(e:Event)=>{const a=(e as MotionLike).accelerationIncludingGravity;if([a?.x,a?.y,a?.z].some(v=>typeof v==="number"&&Math.abs(v)>.05))markSensor()};window.addEventListener("deviceorientationabsolute",onAbs,true);window.addEventListener("deviceorientation",onRel,true);window.addEventListener("devicemotion",onMotion,true);const timer=window.setTimeout(()=>{if(!got)setOrientationError("Sensör verisi alınamadı. Kamera açık kalacak; veri geldiğinde tarama otomatik başlayacak.")},3500);return()=>{window.removeEventListener("deviceorientationabsolute",onAbs,true);window.removeEventListener("deviceorientation",onRel,true);window.removeEventListener("devicemotion",onMotion,true);window.clearTimeout(timer)}},[orientationStarted]);
  useEffect(()=>{const p=pitch??-90;setSkyMode(v=>v?p>=SKY_EXIT:p>=SKY_ENTER)},[pitch]);
  const startCamera=useCallback(async()=>{if(!window.isSecureContext)throw new Error("Kamera yalnızca HTTPS bağlantısında çalışır.");const video=videoRef.current;if(!navigator.mediaDevices?.getUserMedia||!video)throw new Error("Bu tarayıcı kamera erişimini desteklemiyor.");const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920,min:1280},height:{ideal:1080,min:720},frameRate:{ideal:30,max:60}},audio:false});streamRef.current=stream;video.srcObject=stream;video.muted=true;video.playsInline=true;await video.play();setFov(DEFAULT_FOV);setCameraReady(true)},[]);
  const startScan=useCallback(async()=>{setCameraError(null);setOrientationError(null);setCameraReady(false);setSelected(null);setSelected3DPosition(null);sensorMode.current=null;relativeBase.current=null;absoluteGraceUntil.current=Date.now()+700;setHeading(null);setPitch(null);setOrientationStarted(false);try{await startCamera();setCameraStarted(true)}catch(e){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCameraError(e instanceof Error?e.message:"Kamera başlatılamadı.");setCameraStarted(false);setCameraReady(false);return}const req=(DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<PermissionState>}).requestPermission;if(req){try{if((await req())!=="granted")setOrientationError("Yön sensörü izni verilmedi. Kamera çalışır; izin verilince parseller yerleşir.")}catch{setOrientationError("Yön sensörü izni alınamadı. Kamera çalışır; sensör verisi geldiğinde tarama devam eder.")}}setOrientationStarted(true);if(location)void fetchParcels(location,true)},[fetchParcels,location,startCamera]);
  const stopScan=useCallback(()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current){videoRef.current.pause();videoRef.current.srcObject=null}setCameraStarted(false);setCameraReady(false);setOrientationStarted(false);setHeading(null);setPitch(null);setSkyMode(false);setSelected(null);setSelected3DPosition(null)},[]);useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop())},[]);
  const projected=useMemo(()=>{if(!location||!cameraReady||!skyMode||heading===null||pitch===null)return[];const r=rootRef.current?.getBoundingClientRect();return nearby.map(p=>project(p,location,heading,pitch,fov,r?.width??window.innerWidth,r?.height??window.innerHeight)).filter(Boolean) as Projected[]},[cameraReady,fov,heading,location,nearby,pitch,roll,sensorTick,skyMode]);
  const threeParcels=useMemo(()=>nearby.slice(0,100).map(p=>({id:p.id,east:p.east,north:p.north,altitude:p.altitude,distance:p.distance})),[nearby]);
  const selectById=useCallback((id:string)=>{const parcel=nearby.find(p=>p.id===id);if(parcel){setSelected(parcel);setSelected3DPosition(null)}},[nearby]);
  const handle3DProjection=useCallback((hit:Projected3DHit|null)=>{setSelected3DPosition(hit)},[]);
  const nearest=nearby[0]??null;const visibleCount=projected.length;const status=parcelLoading?"Parseller yenileniyor…":parcelError?"Parsel verisi alınamadı":skyMode?`${visibleCount} parsel görünür`:"Gökyüzüne yöneltin";const buy=()=>{if(selected?.status==="available")window.location.href=`/parsel-satin-al?parcels=${encodeURIComponent(selected.id)}`};
  const selectedCardStyle=selected&&selected3DPosition?.id===selected.id&&selected3DPosition.visible?{left:`${clamp((selected3DPosition.x/window.innerWidth)*100,6,94)}%`,top:`${clamp((selected3DPosition.y/window.innerHeight)*100+3,16,76)}%`,transform:"translate(-50%,0)"}:{ };
  const offscreen=useMemo(()=>{if(!location||heading===null)return[];return nearby.filter(p=>Math.abs(normalizeAngle(p.bearing-heading))>fov*.5).slice(0,5)},[fov,heading,location,nearby]);
  return <main ref={rootRef} className="fixed inset-0 overflow-hidden bg-slate-950 text-white"><video ref={videoRef} className={`absolute inset-0 z-0 h-full w-full object-cover ${cameraStarted?"block":"hidden"}`} playsInline muted autoPlay/>
    {!cameraStarted&&<div className="absolute inset-0 z-30 flex items-center justify-center px-6"><div className="w-full max-w-sm rounded-3xl border border-white/15 bg-slate-950/90 p-7 text-center shadow-2xl"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-cyan-300/10"><Camera className="h-8 w-8 text-cyan-200"/></div><p className="mt-5 text-[10px] font-bold uppercase tracking-[.28em] text-cyan-300">MySkyParcel AR</p><h1 className="mt-2 text-2xl font-bold">Gökyüzünü Tara</h1><p className="mt-3 text-sm leading-6 text-white/65">GPS, pusula, jiroskop ve gerçek kamera görüntüsüyle yakındaki parselleri gökyüzünde göster.</p><button onClick={startScan} className="mt-6 w-full rounded-2xl bg-cyan-300 px-5 py-3.5 text-sm font-bold text-slate-950">Kamerayı ve AR taramayı başlat</button>{locationError&&<p className="mt-3 text-xs text-amber-200">{locationError}</p>}{cameraError&&<p className="mt-3 text-xs text-red-200">{cameraError}</p>}</div></div>}
    {cameraStarted&&<><SkyScan3DLayer parcels={threeParcels} heading={heading} pitch={pitch} fov={fov} visible={cameraReady&&skyMode} selectedId={selected?.id??null} onSelect={selectById} onProjectSelected={handle3DProjection}/><div className="pointer-events-none absolute inset-0 z-20 bg-[radial-gradient(circle_at_center,transparent_35%,rgba(2,6,23,.24)_100%)]"/><div className="absolute left-3 right-3 top-3 z-50 flex items-center justify-between"><div className="flex items-center gap-2 rounded-full border border-white/20 bg-slate-950/60 px-3 py-2 backdrop-blur"><Crosshair className="h-4 w-4 text-cyan-200"/><span className="text-xs font-semibold">Gökyüzünü Tara</span></div><button onClick={stopScan} className="rounded-full border border-white/20 bg-slate-950/60 p-2"><X className="h-5 w-5"/></button></div>{orientationError&&<div className="absolute left-3 right-3 top-16 z-50 rounded-xl border border-amber-300/25 bg-black/70 px-3 py-2 text-center text-[11px] text-amber-100">{orientationError}</div>}
      {cameraReady&&skyMode&&projected.map(p=><button key={p.id} onClick={()=>setSelected(p)} className="absolute z-30 -translate-x-1/2 -translate-y-1/2" style={{left:`${clamp(p.left,3,97)}%`,top:`${clamp(p.top,10,82)}%`,opacity:p.opacity,transform:`translateZ(${Math.min(180,p.depth*.055)}px) scale(${p.scale}) rotateZ(${roll*.12}deg)`,perspective:"900px",transformStyle:"preserve-3d"}}><span className="relative block h-[74px] w-[74px]" style={{transformStyle:"preserve-3d",transform:"rotateX(8deg) rotateY(-18deg)"}}><span className="absolute inset-[10px] rounded-[9px] border border-cyan-100/90 bg-cyan-300/25 shadow-[0_0_32px_rgba(34,211,238,.45)]"/><span className="absolute inset-[18px] rounded-full bg-white/20 blur-md"/><span className="absolute left-1/2 top-[10px] h-[54px] w-[27px] origin-left rounded-r-[9px] border border-cyan-100/50 bg-sky-700/50" style={{transform:"rotateY(90deg)"}}/><span className="absolute bottom-[10px] left-[10px] h-[27px] w-[54px] origin-bottom rounded-b-[9px] border border-cyan-100/35 bg-slate-900/70" style={{transform:"rotateX(90deg)"}}/><span className="absolute inset-0 flex items-center justify-center text-[9px] font-black text-white drop-shadow-[0_2px_5px_rgba(0,0,0,.9)]">P-{p.parcel_number}</span><span className="absolute left-1/2 top-0 -translate-x-1/2 -translate-y-full pb-1"><span className="block rounded-lg border border-white/20 bg-slate-950/85 px-2 py-1 text-center shadow-lg backdrop-blur"><b className="block text-[10px] text-white">{money(p.price??p.tier_price)}</b><span className="block text-[8px] text-cyan-200">{formatDistance(p.distance)} · {directionLabel(p.bearing)}</span></span></span><span className="absolute left-1/2 top-full mt-1 -translate-x-1/2 whitespace-nowrap rounded-full border border-cyan-200/20 bg-slate-950/80 px-2 py-1 text-[8px] font-semibold text-white/90 shadow-lg backdrop-blur">{p.city_name} · {formatDistance(p.distance)}</span></span></button>)}
      {cameraReady&&!skyMode&&<div className="pointer-events-none absolute inset-x-4 top-[42%] z-30 flex justify-center"><div className="rounded-2xl border border-white/20 bg-slate-950/55 px-5 py-3 text-center"><div className="text-sm font-semibold">☁️ Gökyüzüne yöneltin</div><div className="mt-1 text-xs text-white/65">Telefonu yukarı kaldırın</div></div></div>}
      {cameraReady&&heading!==null&&offscreen.length>0&&<div className="pointer-events-none absolute inset-x-0 top-[46%] z-35 flex justify-between px-2">{offscreen.slice(0,2).map(p=>{const delta=normalizeAngle(p.bearing-heading);const right=delta>0;return <div key={p.id} className={`rounded-2xl border border-white/15 bg-slate-950/75 px-3 py-2 shadow-xl backdrop-blur ${right?"ml-auto":"mr-auto"}`}><Navigation className="mx-auto h-5 w-5 text-cyan-200" style={{transform:`rotate(${right?0:180}deg)`}}/><div className="mt-1 text-[8px] font-bold">P-{p.parcel_number} · {formatDistance(p.distance)}</div></div>})}</div>}
      {selected&&<div className="absolute z-50 w-[calc(100%-1.5rem)] max-w-md rounded-3xl border border-white/15 bg-slate-950/92 p-4 shadow-2xl backdrop-blur-xl" style={selectedCardStyle}><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-300">{selected.tier||"Premium"}</p><h2 className="mt-1 text-lg font-bold">P-{selected.parcel_number}</h2><p className="text-xs text-white/65">{selected.city_name} · {formatDistance(selected.distance)} · {Math.round(selected.bearing)}°</p><p className="mt-1 text-xl font-black text-white">{money(selected.price??selected.tier_price)}</p></div><button onClick={()=>{setSelected(null);setSelected3DPosition(null)}} className="rounded-full bg-white/10 p-2"><X className="h-4 w-4"/></button></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>window.location.href=`/parsel-satin-al?parcels=${encodeURIComponent(selected.id)}`} className="rounded-xl border border-white/15 bg-white/10 px-3 py-2.5 text-xs font-bold">Parseli İncele</button><button disabled={selected.status!=="available"} onClick={buy} className="rounded-xl bg-cyan-300 px-3 py-2.5 text-xs font-bold text-slate-950 disabled:opacity-40"><ShoppingCart className="mr-1 inline h-4 w-4"/>Satın Al</button></div></div>}
      <div className="absolute bottom-0 left-0 right-0 z-40 px-3 pb-3"><div className="mx-auto max-w-2xl rounded-[28px] border border-white/15 bg-slate-950/78 px-3 py-3 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between"><div className="min-w-[72px] text-center"><MapPin className="mx-auto h-5 w-5 text-cyan-200"/><p className="text-[9px] text-white/55">Görüşte</p><p className="text-base font-black">{visibleCount}</p></div><div className="relative flex h-[74px] w-[74px] items-center justify-center rounded-full border border-cyan-300/35 bg-slate-900/45"><div className="absolute inset-1 rounded-full border border-white/10"/><Navigation className="h-7 w-7 text-cyan-100 transition-transform" style={{transform:`rotate(${heading??0}deg)`}}/><span className="absolute -top-1 rounded-full bg-cyan-300 px-2 py-0.5 text-[8px] font-black text-slate-950">{heading===null?"—":`${Math.round(heading)}° ${directionLabel(heading)}`}</span></div><div className="min-w-[88px] text-center"><Compass className="mx-auto h-5 w-5 text-cyan-200"/><p className="text-[9px] text-white/55">En yakın</p><p className="text-base font-black">{nearest?formatDistance(nearest.distance):"—"}</p><p className="text-[8px] text-cyan-200">{nearest?`${directionLabel(nearest.bearing)} · ${Math.round(nearest.bearing)}°`:parcelLoading?"taranıyor":"bekleniyor"}</p></div></div><div className="mt-2 flex items-center justify-center gap-2 text-[8px] text-white/50"><span>GPS ±{location?Math.round(location.accuracy):"—"}m</span><span>•</span><span>FOV {Math.round(fov)}°</span><span>•</span><span>{status}</span></div></div></div>
    </>}
  </main>;
}
