import { Camera, Compass, LocateFixed, RefreshCw, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { supabaseBrowser } from "@/lib/supabaseBrowser";

type Gps={latitude:number;longitude:number;accuracy:number|null;heading:number|null};
type Point=[number,number];
type Parcel={id:string;parcel_number:string;polygon:Point[];latitude:number;longitude:number;distance:number;bearing:number};
type Orientation={heading:number|null;pitch:number;roll:number;absolute:boolean;source:string};
type XrState={renderer:THREE.WebGLRenderer;session:any;scene:THREE.Scene;root:THREE.Group;labels:THREE.Group;referenceSpace:any;calibrationYaw:number};
const R=6371000,SEARCH=5000;
const norm=(n:number)=>((n%360)+360)%360,rad=(n:number)=>n*Math.PI/180;
const angleDelta=(a:number,b:number)=>((a-b+540)%360)-180;
const hav=(a:Gps,b:{latitude:number;longitude:number})=>{const p1=rad(a.latitude),p2=rad(b.latitude),d1=p2-p1,d2=rad(b.longitude-a.longitude),h=Math.sin(d1/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(h)))};
const bearing=(a:Gps,b:{latitude:number;longitude:number})=>{const p1=rad(a.latitude),p2=rad(b.latitude),dl=rad(b.longitude-a.longitude);return norm(Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))*180/Math.PI)};
function centroid(p:Point[]):Point{if(p.length<3)return p[0]??[0,0];let a=0,x=0,y=0;for(let i=0;i<p.length-1;i++){const [x1,y1]=p[i],[x2,y2]=p[i+1],f=x1*y2-x2*y1;a+=f;x+=(x1+x2)*f;y+=(y1+y2)*f}return Math.abs(a)<1e-12?p[0]:[x/(3*a),y/(3*a)]}
function parseGeometry(raw:unknown):Point[]{if(!raw)return[];if(typeof raw==='object'){const v=raw as any,g=v.type==='Feature'?v.geometry:v;if(g?.type==='Polygon'&&Array.isArray(g.coordinates?.[0]))return g.coordinates[0].map((p:any)=>[+p[0],+p[1]] as Point).filter(p=>p.every(Number.isFinite))}const s=String(raw).trim();if(/^POLYGON/i.test(s)){const b=s.replace(/^POLYGON\s*\(\(/i,'').replace(/\)\)\s*$/,'');return b.split(',').map(q=>q.trim().split(/\s+/).slice(0,2).map(Number) as Point).filter(p=>p.every(Number.isFinite))}if(s.startsWith('{'))try{return parseGeometry(JSON.parse(s))}catch{}return[]}
function orientation(e:DeviceOrientationEvent):Orientation|null{const v=e as DeviceOrientationEvent&{webkitCompassHeading?:number};let h:number|null=typeof v.webkitCompassHeading==='number'?norm(v.webkitCompassHeading):e.absolute&&typeof e.alpha==='number'?norm(360-e.alpha):null;if(h===null&&typeof e.beta!=='number'&&typeof e.gamma!=='number')return null;const a=window.screen.orientation?.angle??0;if(h!==null&&!v.webkitCompassHeading){if(a===90)h=norm(h+90);else if(a===180)h=norm(h+180);else if(a===270)h=norm(h-90)}return{heading:h,pitch:typeof e.beta==='number'?e.beta-90:0,roll:typeof e.gamma==='number'?e.gamma:0,absolute:e.absolute===true||e.type==='deviceorientationabsolute',source:v.webkitCompassHeading?'iOS pusula':e.absolute?'Mutlak pusula':h!==null?'Pusula':'Eğim sensörü'}}
async function permissions(){try{const D=window.DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<PermissionState>};const M=(window as any).DeviceMotionEvent as {requestPermission?:()=>Promise<PermissionState>}|undefined;if(typeof D.requestPermission==='function'&&(await D.requestPermission())!=='granted')return false;if(typeof M?.requestPermission==='function'&&(await M.requestPermission())!=='granted')return false;return true}catch{return false}}
function enu(o:Gps,p:Point){const east=rad(p[0]-o.longitude)*R*Math.cos(rad(o.latitude)),north=rad(p[1]-o.latitude)*R;return new THREE.Vector3(east,0,-north)}

export function SkyScanExperienceV10(){
 const video=useRef<HTMLVideoElement>(null),mount=useRef<HTMLDivElement>(null),watch=useRef<number|null>(null),stream=useRef<MediaStream|null>(null),gpsRef=useRef<Gps|null>(null),lastLoad=useRef<Gps|null>(null),busy=useRef(false),sceneRef=useRef<{renderer:THREE.WebGLRenderer;raf:number}|null>(null),xrRef=useRef<XrState|null>(null),oRef=useRef<Orientation>({heading:null,pitch:0,roll:0,absolute:false,source:'Sensör aranıyor'});
 const[o,setO]=useState(oRef.current),[gps,setGps]=useState<Gps|null>(null),[parcels,setParcels]=useState<Parcel[]>([]),[started,setStarted]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[status,setStatus]=useState('Hazır'),[sensor,setSensor]=useState('Pusula sensörü aranıyor…');
 const load=useCallback(async(pos:Gps)=>{if(busy.current)return;busy.current=true;setLoading(true);setError(null);try{const city=await supabaseBrowser.from('cities').select('id').eq('slug','gaziantep').eq('is_active',true).maybeSingle();if(city.error||!city.data)throw city.error??new Error('Gaziantep bulunamadı');const dLat=SEARCH/111320,dLon=SEARCH/Math.max(111320*Math.cos(rad(pos.latitude)),1);const q=await supabaseBrowser.from('sky_scan_parcels').select('id,parcel_id,parcel_number,latitude,longitude,parcels!sky_scan_parcels_parcel_id_fkey(geometry)').eq('city_id',city.data.id).gte('latitude',pos.latitude-dLat).lte('latitude',pos.latitude+dLat).gte('longitude',pos.longitude-dLon).lte('longitude',pos.longitude+dLon).limit(2000);if(q.error)throw q.error;const rows=(q.data??[]).map((r:any)=>{const poly=parseGeometry(r.parcels?.geometry);const c=poly.length>=3?centroid(poly):[Number(r.longitude),Number(r.latitude)] as Point;const t={latitude:c[1],longitude:c[0]};return{id:String(r.parcel_id??r.id),parcel_number:String(r.parcel_number??'—'),polygon:poly,latitude:t.latitude,longitude:t.longitude,distance:hav(pos,t),bearing:bearing(pos,t)}}).filter((p:Parcel)=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)&&p.distance<=SEARCH).sort((a:Parcel,b:Parcel)=>a.distance-b.distance).slice(0,150);setParcels(rows);lastLoad.current=pos;setStatus(`${rows.length} parsel bulundu`);if(!rows.length)setError('5 km çevresinde parsel bulunamadı')}catch(e){setError(e instanceof Error?e.message:'Parseller alınamadı');setStatus('Parsel sorgusu tamamlanamadı')}finally{busy.current=false;setLoading(false)}},[]);
 const addParcels=useCallback((scene:THREE.Scene,root:THREE.Group,labels:THREE.Group,pos:Gps,items:Parcel[])=>{root.clear();labels.clear();items.forEach(p=>{const target=enu(pos,[p.longitude,p.latitude]);if(p.polygon.length>=3){const shape=new THREE.Shape();p.polygon.forEach((pt,i)=>{const v=enu(pos,pt);if(i)shape.lineTo(v.x,v.z);else shape.moveTo(v.x,v.z)});shape.closePath();const m=new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshBasicMaterial({color:0x22d3ee,transparent:true,opacity:.38,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;root.add(m);const e=new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:1}));e.rotation.copy(m.rotation);root.add(e)}const marker=new THREE.Mesh(new THREE.CircleGeometry(3.5,24),new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide,depthTest:false}));marker.position.set(target.x,1.5,target.z);marker.rotation.x=-Math.PI/2;root.add(marker);const c=document.createElement('canvas');c.width=420;c.height=90;const x=c.getContext('2d')!;x.fillStyle='rgba(0,0,0,.85)';x.fillRect(4,4,412,82);x.fillStyle='#fff';x.font='bold 30px sans-serif';x.fillText(p.parcel_number,16,40);x.font='22px sans-serif';x.fillText(`${Math.round(p.distance)} m · ${Math.round(p.bearing)}°`,16,72);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.position.set(target.x,7,target.z);s.scale.set(14,3,1);labels.add(s)});},[]);
 const draw=useCallback((pos:Gps,items:Parcel[])=>{if(xrRef.current)return;const el=mount.current;if(!el)return;sceneRef.current&&cancelAnimationFrame(sceneRef.current.raf);sceneRef.current?.renderer.dispose();el.innerHTML='';const scene=new THREE.Scene(),cam=new THREE.PerspectiveCamera(70,el.clientWidth/Math.max(el.clientHeight,1),.1,30000),renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.setClearColor(0,0);el.appendChild(renderer.domElement);const root=new THREE.Group(),labels=new THREE.Group();scene.add(root,labels);addParcels(scene,root,labels,pos,items);const tick=()=>{const h=oRef.current.heading===null?0:rad(oRef.current.heading),pitch=rad(Math.max(-80,Math.min(80,oRef.current.pitch))),roll=rad(oRef.current.roll);cam.rotation.order='YXZ';cam.rotation.set(pitch,-h,-roll);renderer.render(scene,cam);const raf=requestAnimationFrame(tick);sceneRef.current={renderer,raf}};tick()},[addParcels]);
 useEffect(()=>{if(gps&&parcels.length)draw(gps,parcels)},[gps,parcels,draw]);
 const start=useCallback(async()=>{setStarted(true);setError(null);setStatus('Kamera ve GPS başlatılıyor…');void (async()=>{const granted=await permissions();if(!granted){setSensor('Sensör izni verilmedi');return}let seen=false;const on=(e:Event)=>{const r=orientation(e as DeviceOrientationEvent);if(!r)return;seen=true;if(r.absolute||oRef.current.heading===null||!oRef.current.absolute){oRef.current=r;setO(r)}setSensor(r.heading===null?'Hareket sensörü aktif · pusula aranıyor':r.absolute?'Mutlak pusula aktif':'Pusula aktif')};window.addEventListener('deviceorientationabsolute',on,true);window.addEventListener('deviceorientation',on,true);window.addEventListener('devicemotion',()=>{if(!seen)setSensor('Hareket sensörü aktif · pusula aranıyor')},true);setTimeout(()=>{if(!seen)setSensor('Sensör verisi alınamadı · kamera açık')},4000)})();if(navigator.geolocation)watch.current=navigator.geolocation.watchPosition(p=>{const n:Gps={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:Number.isFinite(p.coords.accuracy)?p.coords.accuracy:null,heading:Number.isFinite(p.coords.heading)&&p.coords.heading>=0?p.coords.heading:null};gpsRef.current=n;setGps(n);const old=lastLoad.current;if(!old||hav(old,n)>100||((n.accuracy??999)+10<(old.accuracy??999)))void load(n)},e=>setError(e.code===1?'Konum izni verilmedi':'GPS alınamadı'),{enableHighAccuracy:true,maximumAge:1000,timeout:15000});try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play()}}catch(e){setError(e instanceof Error?e.message:'Kamera açılamadı')}},[load]);
 const stop=useCallback(()=>{if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);stream.current?.getTracks().forEach(t=>t.stop());sceneRef.current&&cancelAnimationFrame(sceneRef.current.raf);sceneRef.current?.renderer.dispose();sceneRef.current=null;const xr=xrRef.current;if(xr){xr.session.end().catch(()=>{});xr.renderer.setAnimationLoop(null);xr.renderer.dispose();xrRef.current=null}setStarted(false)},[]);
 useEffect(()=>()=>stop(),[stop]);
 const nearest=parcels[0],dir=nearest&&o.heading!==null?angleDelta(nearest.bearing,o.heading):null,dirText=dir===null?'Yön bekleniyor':Math.abs(dir)<25?'DÜZ':dir>0&&dir<160?'SAĞ':dir<0&&dir>-160?'SOL':'ARKA';const label=o.heading!==null?(o.absolute?'Mutlak pusula aktif':'Pusula aktif'):sensor;
 return <div className="relative h-[100dvh] w-full overflow-hidden bg-black text-white"><video ref={video} playsInline muted className="absolute inset-0 h-full w-full object-cover"/><div ref={mount} className="pointer-events-none absolute inset-0 z-10"/><div className="absolute inset-x-0 top-0 z-20 p-3"><div className="mx-auto max-w-xl rounded-2xl bg-black/65 p-3"><div className="flex items-center justify-between"><b className="flex items-center gap-2"><Camera className="h-5 w-5"/>3B Sky Scan AR</b><button onClick={stop}><X className="h-5 w-5"/></button></div><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><span>GPS: {gps?`${Math.round(gps.accuracy??0)} m`:'—'}</span><span>Heading: {o.heading===null?'—':`${Math.round(o.heading)}°`}</span><span>Parsel: {parcels.length}</span></div><div className="mt-2 text-xs">GPS + sensör AR aktif · {`${parcels.length} parsel hazır · ${label}`}</div>{nearest&&<div className="mt-2 rounded-xl bg-black/70 p-2 text-sm">En yakın <b>{nearest.parcel_number}</b> · {Math.round(nearest.distance)} m · {dirText}</div>}{error&&<div className="mt-2 text-xs text-red-300">{error}</div>}</div></div>{!started&&<div className="absolute inset-x-4 bottom-8 z-30"><button onClick={start} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-white px-5 py-4 font-bold text-black"><LocateFixed className="h-5 w-5"/>GPS + sensör AR taramasını başlat</button></div>}{started&&<div className="absolute bottom-4 left-3 right-3 z-20 flex gap-2 justify-between"><div className="rounded-full bg-black/65 px-4 py-2 text-sm">{loading?'Parseller yükleniyor…':`${parcels.length} parsel hazır · ${label}`}</div><button onClick={()=>gps&&load(gps)} className="rounded-full bg-black/65 p-3"><RefreshCw className="h-5 w-5"/></button></div>}<div className="absolute left-1/2 top-1/2 z-20 -translate-x-1/2 -translate-y-1/2 opacity-60"><Compass className="h-8 w-8"/></div></div>;
}
