import React, { useCallback, useState } from "react";
import { CERTIFICATE_TEMPLATE_FALLBACK, CERTIFICATE_TEMPLATE_IMAGES, CERTIFICATE_TEMPLATE_LABELS } from "@/lib/certificateTemplate";

type Tier = "digital" | "elite" | "premium";
type Props = { tier: Tier; name?: string | null; parcelCode?: string | null; certificateNumber?: string | null; issuedAt?: string | null; cityName?: string | null };
const LABEL = CERTIFICATE_TEMPLATE_LABELS;
const dateTR = (v?: string | null) => { if (!v) return "—"; const d = new Date(v); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleDateString("tr-TR"); };
const verify = (n: string) => `${window.location.origin}/sertifika-dogrula?code=${encodeURIComponent(n)}`;
const qrUrl = (n: string) => { const base = import.meta.env.VITE_SUPABASE_URL as string | undefined; return base ? `${base.replace(/\/$/, "")}/functions/v1/certificate-qr?code=${encodeURIComponent(n)}` : ""; };
function loadImage(src: string, crossOrigin?: string) { return new Promise<HTMLImageElement>((resolve, reject) => { const i = new Image(); if (crossOrigin) i.crossOrigin = crossOrigin; i.onload = () => resolve(i); i.onerror = () => reject(new Error(`Image failed: ${src}`)); i.src = src; }); }
async function loadTemplate(tier: Tier) { try { return await loadImage(CERTIFICATE_TEMPLATE_IMAGES[tier]); } catch { return await loadImage(CERTIFICATE_TEMPLATE_FALLBACK); } }
function save(blob: Blob, name: string) { const u = URL.createObjectURL(blob), a = document.createElement("a"); a.href = u; a.download = name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(u), 1000); }
async function render(tier: Tier, name: string, parcel: string, date: string, number: string, city: string) {
  const bg = await loadTemplate(tier);
  const c = document.createElement("canvas"); c.width = bg.naturalWidth; c.height = bg.naturalHeight;
  const x = c.getContext("2d"); if (!x) throw Error("canvas"); x.drawImage(bg, 0, 0, c.width, c.height);
  const s = c.width / 1600; x.textAlign = "center"; x.textBaseline = "middle"; x.fillStyle = "#f5d47b"; x.shadowColor = "rgba(0,0,0,.75)"; x.shadowBlur = 4 * s;
  let fs = 48 * s; x.font = `italic ${fs}px Georgia,serif`; while (x.measureText(name).width > c.width * .56 && fs > 18) { fs -= 2; x.font = `italic ${fs}px Georgia,serif`; } x.fillText(name || "Ad Soyad", c.width / 2, c.height * .555); x.shadowBlur = 0;
  x.font = `${18 * s}px Arial,sans-serif`; x.fillStyle = "#fff"; x.fillText(parcel || "—", c.width * .36, c.height * .725); x.fillText(date || "—", c.width * .50, c.height * .725); x.fillText(number || "—", c.width * .64, c.height * .725);
  if (city) { x.font = `${16 * s}px Arial,sans-serif`; x.fillStyle = "rgba(255,255,255,.8)"; x.fillText(city, c.width / 2, c.height * .79); }
  const qr = qrUrl(number); if (qr) { try { const q = await loadImage(qr, "anonymous"), size = Math.round(c.width * .105), qx = c.width - size - Math.round(c.width * .035), qy = Math.round(c.height * .635); x.fillStyle = "#fff"; x.fillRect(qx - 6, qy - 6, size + 12, size + 12); x.drawImage(q, qx, qy, size, size); } catch (e) { console.warn("QR embedding failed", e); } }
  return c;
}

export function CertificateArtwork({ tier, name, parcelCode, certificateNumber, issuedAt, cityName }: Props) {
  const displayName = name?.trim() || "Ad Soyad";
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const make = useCallback(() => render(tier, displayName, parcelCode || "—", dateTR(issuedAt), certificateNumber || "—", cityName || ""), [tier, displayName, parcelCode, issuedAt, certificateNumber, cityName]);
  const download = useCallback(async (type: "png" | "jpg" | "pdf") => { if (!certificateNumber) return; setBusy(true); setError(null); try { const c = await make(); if (type === "pdf") { const w = window.open("", "_blank"); if (!w) throw Error("popup"); w.document.write(`<html><head><title>${certificateNumber}</title><style>@page{size:A4 landscape;margin:0}html,body{margin:0;height:100%}img{width:100%;height:100%;object-fit:contain}</style></head><body><img src="${c.toDataURL("image/png")}"></body></html>`); w.document.close(); setTimeout(() => w.print(), 500); } else { const b = await new Promise<Blob | null>(r => c.toBlob(r, type === "png" ? "image/png" : "image/jpeg", 1)); if (!b) throw Error(type); save(b, `${certificateNumber}-${tier}.${type}`); } } catch (e) { console.error(e); setError("Sertifika oluşturulamadı. Lütfen tekrar deneyin"); } finally { setBusy(false); } }, [certificateNumber, make, tier]);
  const templateSrc = CERTIFICATE_TEMPLATE_IMAGES[tier]; const verificationQr = certificateNumber ? qrUrl(certificateNumber) : "";
  return <article className="relative mx-auto w-full overflow-hidden rounded-xl bg-black shadow-2xl" aria-label={LABEL[tier]}><img src={templateSrc} alt={LABEL[tier]} onError={(event) => { const img = event.currentTarget; if (img.src.endsWith(CERTIFICATE_TEMPLATE_FALLBACK)) return; img.src = CERTIFICATE_TEMPLATE_FALLBACK; }} className="block aspect-[1600/1067] h-auto w-full object-cover"/><div className="pointer-events-none absolute inset-0"><div className="absolute left-[22%] right-[22%] top-[50%] flex h-[12%] items-center justify-center text-center"><span className="font-serif text-[clamp(15px,3vw,40px)] font-medium italic text-[#f5d47b] drop-shadow-[0_2px_4px_rgba(0,0,0,.8)]">{displayName}</span></div><div className="absolute left-[27%] right-[27%] top-[69%] grid grid-cols-3 gap-2 text-center text-[clamp(6px,.8vw,13px)] text-white"><div><span className="block text-white/60">PARSEL NO</span><strong>{parcelCode || "—"}</strong></div><div><span className="block text-white/60">TARİH</span><strong>{dateTR(issuedAt)}</strong></div><div><span className="block text-white/60">SERTİFİKA NO</span><strong>{certificateNumber || "—"}</strong></div></div>{cityName && <div className="absolute left-[25%] right-[25%] top-[63%] text-center text-[clamp(6px,.8vw,12px)] text-white/75">{cityName}</div>}{verificationQr && <img src={verificationQr} alt="Sertifika doğrulama QR kodu" className="absolute right-[3.5%] top-[64%] h-[11%] w-[11%] rounded bg-white p-1"/>}</div>{certificateNumber && <div className="relative z-10 flex flex-wrap justify-end gap-2 border-t border-white/10 bg-[#06162d] p-2"><button type="button" onClick={() => void download("png")} disabled={busy}>PNG</button><button type="button" onClick={() => void download("jpg")} disabled={busy}>JPG</button><button type="button" onClick={() => void download("pdf")} disabled={busy}>PDF / YAZDIR</button></div>}{busy && <div className="absolute inset-0 z-20 flex items-center justify-center bg-black/60 text-sm font-semibold text-gold">SERTİFİKA HAZIRLANIYOR...</div>}{error && <p className="absolute bottom-14 left-3 right-3 z-20 rounded bg-red-950/90 p-2 text-center text-xs text-red-200">{error}</p>}</article>;
}

export const CERTIFICATE_TEMPLATES = (Object.keys(CERTIFICATE_TEMPLATE_IMAGES) as Tier[]).map((tier) => ({ tier, label: LABEL[tier], src: CERTIFICATE_TEMPLATE_IMAGES[tier] }));
