import { useEffect, useRef, useState } from "react";
import type { Parcel } from "@/types/parcel";

type CityCenter = { lat: number; lng: number };
type ViewportBounds = { minLat: number; minLng: number; maxLat: number; maxLng: number };
type FocusTarget = { city: CityCenter; parcel: CityCenter; token: string };
type Props = { parcels: Parcel[]; selectedId: string | null; selectedIds?: Set<string>; multiSelect?: boolean; onSelect: (id: string | null) => void; onToggleSelect?: (id: string) => void; onViewportChange?: (bounds: ViewportBounds) => void; center: CityCenter; focusTarget?: FocusTarget | null };
const SCRIPT_ID = "myskyparcel-google-maps";
let mapsPromise: Promise<any> | null = null;
const TURKEY_CENTER = { lat: 39, lng: 35 };
function loadMaps(key: string) { if (typeof window === "undefined") return Promise.reject(new Error("browser")); if ((window as any).google?.maps) return Promise.resolve((window as any).google.maps); if (mapsPromise) return mapsPromise; mapsPromise = new Promise((resolve, reject) => { const s = document.createElement("script"); s.id = SCRIPT_ID; s.async = true; s.defer = true; s.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}`; s.onload = () => (window as any).google?.maps ? resolve((window as any).google.maps) : reject(new Error("Google Maps yüklenemedi.")); s.onerror = () => reject(new Error("Google Maps yüklenemedi.")); document.head.appendChild(s); }); return mapsPromise; }
const color = (p: Parcel) => p.status === "sold" ? "#ff1744" : p.tier === "premium" ? "#f6c453" : p.tier === "elite" ? "#b77cff" : "#55c9ff";
function grid(center: CityCenter, total: number, inner: number, outer: number) { if (!total) return []; const cos = Math.max(Math.cos(center.lat * Math.PI / 180), .2); let n = Math.max(2, Math.ceil(Math.sqrt(total))); const make = () => { const size = outer * 2 / n, ratio = inner / outer, a: any[] = []; for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) { const x0 = -outer + c * size, y0 = -outer + r * size, x1 = x0 + size, y1 = y0 + size, cx = (x0+x1)/2/outer, cy = (y0+y1)/2/outer; if (Math.max(Math.abs(cx), Math.abs(cy)) >= ratio) a.push({x0,y0,x1,y1}); } return a; }; let a = make(); while (a.length < total) { n++; a = make(); } const point = (x:number,y:number) => ({lat:center.lat+y,lng:center.lng+x/cos}); return a.slice(0,total).map(x => ({ path:[point(x.x0,x.y0),point(x.x1,x.y0),point(x.x1,x.y1),point(x.x0,x.y1)] })); }
export function FocusedGoogleParcelMap({ parcels, selectedId, selectedIds = new Set(), multiSelect = false, onSelect, onToggleSelect, onViewportChange, center, focusTarget }: Props) {
  const ref = useRef<HTMLDivElement|null>(null); const map = useRef<any>(null); const focused = useRef<string|null>(null); const [error,setError]=useState<string|null>(null); const [ready,setReady]=useState(false);
  useEffect(()=>{ const key=import.meta.env.VITE_GOOGLE_MAPS_API_KEY; if(!key){setError("Google Maps API anahtarı eksik.");return;} loadMaps(key).then((maps)=>{ if(!ref.current)return; map.current ||= new maps.Map(ref.current,{center,zoom:12,mapTypeId:"satellite",streetViewControl:false,fullscreenControl:false,mapTypeControl:false,gestureHandling:"greedy",clickableIcons:false}); setReady(true); }).catch(e=>setError(e.message)); },[]);
  useEffect(()=>{ if(!ready||!map.current||!focusTarget||focused.current===focusTarget.token)return; focused.current=focusTarget.token; map.current.setCenter(TURKEY_CENTER); map.current.setZoom(5); const a=window.setTimeout(()=>{map.current?.panTo(focusTarget.city);map.current?.setZoom(8);},900); const b=window.setTimeout(()=>{map.current?.panTo(focusTarget.parcel);map.current?.setZoom(15);},2200); return()=>{clearTimeout(a);clearTimeout(b)}; },[ready,focusTarget]);
  useEffect(()=>{ if(!ready||!map.current||!onViewportChange)return; const maps=(window as any).google.maps; const emit=()=>{const b=map.current.getBounds();if(!b)return;const ne=b.getNorthEast(),sw=b.getSouthWest();onViewportChange({minLat:sw.lat(),minLng:sw.lng(),maxLat:ne.lat(),maxLng:ne.lng()})}; const l=maps.event.addListener(map.current,"idle",()=>setTimeout(emit,100)); emit(); return()=>maps.event.removeListener(l); },[ready,onViewportChange]);
  useEffect(()=>{if(!ready||!map.current)return;const maps=(window as any).google.maps;const all:any[]=[];const configs:any[]=[["digital",.095,.165],["elite",.05,.08],["premium",.012,.035]];configs.forEach(([tier,inner,outer])=>{const ps=parcels.filter(p=>p.tier===tier),cells=grid(center,ps.length,inner,outer);ps.forEach((p,i)=>{const cell=cells[i];if(!cell)return;const paths=cell.path.map((x:any)=>new maps.LatLng(x.lat,x.lng));const c=color(p),sel=multiSelect?selectedIds.has(p.id):selectedId===p.id;const poly=new maps.Polygon({map:map.current,paths,strokeColor:sel?"#fff4b0":c,strokeOpacity:1,strokeWeight:sel?2.5:p.status==="sold"?2.5:1.1,fillColor:c,fillOpacity:sel?.17:p.status==="sold"?.08:.008,clickable:true,zIndex:sel?501:p.status==="sold"?500:21});poly.addListener("click",()=>multiSelect&&p.status==="available"?onToggleSelect?.(p.id):onSelect(p.id));all.push(poly);});});return()=>all.forEach(p=>p.setMap(null));},[ready,parcels,center.lat,center.lng,selectedId,selectedIds,multiSelect,onSelect,onToggleSelect]);
  return <div className="relative h-[500px] w-full overflow-hidden rounded-2xl border border-cyan-300/20 bg-[#071a2d] sm:h-[600px] lg:h-[670px]"><div ref={ref} className="absolute inset-0" aria-label="MySkyParcel parsel haritası"/>{error&&<div className="absolute inset-0 grid place-items-center bg-[#071a2d] p-6 text-center"><p className="text-xs text-white/70">{error}</p></div>}</div>;
}
