import { useEffect, useRef, useState } from "react";
import type { Parcel } from "@/types/parcel";

type CityCenter={lat:number;lng:number}; type ParcelWithGeometry=Parcel&{geometry?:unknown}; type ParcelZoomLevel=1|2|3|4; type ViewportBounds={minLat:number;minLng:number;maxLat:number;maxLng:number;zoom:number;zoomLevel:ParcelZoomLevel}; type Props={parcels:ParcelWithGeometry[];selectedId:string|null;onSelect:(id:string)=>void;onViewportChange?:(bounds:ViewportBounds)=>void;center:CityCenter}; type Maps=any; type Polygon=any; type Marker=any;
const SCRIPT_ID="myskyparcel-google-maps";
let mapsPromise:Promise<Maps>|null=null;
const MIN_PARCEL_ZOOM=8;
const MAX_PARCEL_ZOOM=20;
function getParcelZoomLevel(zoom:number):ParcelZoomLevel{if(zoom<=10)return 1;if(zoom<=12)return 2;if(zoom<=15)return 3;return 4}
function loadGoogleMaps(apiKey:string):Promise<Maps>{if(typeof window==="undefined")return Promise.reject(new Error("Google Maps browser ortamında yüklenebilir."));if((window as any).google?.maps)return Promise.resolve((window as any).google.maps);if(mapsPromise)return mapsPromise;mapsPromise=new Promise((resolve,reject)=>{const existing=document.getElementById(SCRIPT_ID) as HTMLScriptElement|null;const finish=()=>{const m=(window as any).google?.maps;if(m)resolve(m);else reject(new Error("Google Maps API yüklenemedi."))};if(existing){existing.addEventListener("load",finish,{once:true});existing.addEventListener("error",()=>reject(new Error("Google Maps script yüklenemedi.")),{once:true});return}const script=document.createElement("script");script.id=SCRIPT_ID;script.async=true;script.defer=true;script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(apiKey)}`;script.onload=finish;script.onerror=()=>reject(new Error("Google Maps script yüklenemedi."));document.head.appendChild(script)});return mapsPromise}
function statusColor(status:Parcel["status"]){return status==="sold"?"#ff1744":status==="reserved"?"#f6c453":"#58e6ff"} function tierColor(tier:Parcel["tier"]){return tier==="premium"?"#f6c453":tier==="elite"?"#b77cff":"#55c9ff"}
function point(c:CityCenter,r:number,a:number){const cos=Math.max(Math.cos(c.lat*Math.PI/180),.2);return{lat:c.lat+Math.sin(a)*r,lng:c.lng+Math.cos(a)*r/cos}} function sectorPath(c:CityCenter,r0:number,r1:number,a0:number,a1:number,maps:Maps){const path:any[]=[];for(let i=0;i<=8;i++){const a=a0+(a1-a0)*i/8,p=point(c,r1,a);path.push(new maps.LatLng(p.lat,p.lng))}for(let i=8;i>=0;i--){const a=a0+(a1-a0)*i/8,p=point(c,r0,a);path.push(new maps.LatLng(p.lat,p.lng))}return path}
function cornerIcon(maps:Maps,color:string,selected:boolean){const s=selected?14:9;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${s+14}" height="${s+14}" viewBox="0 0 ${s+14} ${s+14}"><defs><filter id="g"><feGaussianBlur stdDeviation="2.5"/></filter></defs><circle cx="${(s+14)/2}" cy="${(s+14)/2}" r="${s/2+3}" fill="${color}" opacity=".65" filter="url(#g)"/><circle cx="${(s+14)/2}" cy="${(s+14)/2}" r="${s/2}" fill="${color}" stroke="#fff" stroke-opacity=".8" stroke-width="${selected?1.8:1}"/></svg>`;return{url:`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`,scaledSize:new maps.Size(s+14,s+14),anchor:new maps.Point((s+14)/2,(s+14)/2)}}
export function GoogleParcelMap({parcels,selectedId,onSelect,onViewportChange,center}:Props){const mapRef=useRef<HTMLDivElement|null>(null),mapObj=useRef<any>(null),cells=useRef<Map<string,Polygon[]>>(new Map()),corners=useRef<Map<string,Marker>>(new Map()),layouts=useRef<Map<string,{r0:number;r1:number;start:number;end:number}>>(new Map()),selectRef=useRef(onSelect),viewportRef=useRef(onViewportChange),info=useRef<any>(null);const[error,setError]=useState<string|null>(null),[ready,setReady]=useState(false);useEffect(()=>{selectRef.current=onSelect},[onSelect]);useEffect(()=>{viewportRef.current=onViewportChange},[onViewportChange]);
useEffect(()=>{let cancelled=false;const key=import.meta.env.VITE_GOOGLE_MAPS_API_KEY;if(!key){setError("Google Maps API anahtarı eksik.");return}if(!mapRef.current)return;loadGoogleMaps(key).then(maps=>{if(cancelled||!mapRef.current)return;if(!mapObj.current)mapObj.current=new maps.Map(mapRef.current,{center,zoom:12,minZoom:MIN_PARCEL_ZOOM,maxZoom:MAX_PARCEL_ZOOM,mapTypeId:"satellite",streetViewControl:false,fullscreenControl:false,mapTypeControl:false,gestureHandling:"greedy",clickableIcons:false,backgroundColor:"#071a2d"});else mapObj.current.setCenter(center);setError(null);setReady(true)}).catch(e=>{console.error(e);if(!cancelled)setError("Google Maps yüklenemedi. API anahtarını kontrol edin.")});return()=>{cancelled=true}},[center.lat,center.lng]);
useEffect(()=>{if(!ready||!mapObj.current||!viewportRef.current)return;const maps=(window as any).google.maps,map=mapObj.current;const emit=()=>{const b=map.getBounds();if(!b)return;const ne=b.getNorthEast(),sw=b.getSouthWest(),zoom=map.getZoom()??12;viewportRef.current?.({minLat:sw.lat(),minLng:sw.lng(),maxLat:ne.lat(),maxLng:ne.lng(),zoom,zoomLevel:getParcelZoomLevel(zoom)})};const l=maps.event.addListener(map,"idle",emit);emit();return()=>maps.event.removeListener(l)},[ready]);
useEffect(()=>{if(!ready||!mapObj.current)return;const maps=(window as any).google.maps;cells.current.forEach(ps=>ps.forEach(p=>p.setMap(null)));cells.current.clear();corners.current.forEach(m=>m.setMap(null));corners.current.clear();layouts.current.clear();const configs=[{tier:"digital" as const,rows:10,inner:.055,outer:.115},{tier:"elite" as const,rows:6,inner:.030,outer:.055},{tier:"premium" as const,rows:4,inner:.008,outer:.030}];const cornerKeys=new Set<string>();configs.forEach(cfg=>{const items=parcels.filter(p=>p.tier===cfg.tier),rows=Array.from({length:cfg.rows},()=>[] as ParcelWithGeometry[]);items.forEach((p,i)=>rows[i%cfg.rows].push(p));rows.forEach((row,r)=>{if(!row.length)return;const r0=cfg.inner+(cfg.outer-cfg.inner)*r/cfg.rows,r1=cfg.inner+(cfg.outer-cfg.inner)*(r+1)/cfg.rows,count=row.length,step=2*Math.PI/count;row.forEach((p,i)=>{const a0=i*step,a1=(i+1)*step;layouts.current.set(p.id,{r0,r1,start:a0,end:a1});const paths=sectorPath(center,r0,r1,a0,a1,maps),sold=p.status==="sold",base=sold?statusColor(p.status):tierColor(p.tier),selected=p.id===selectedId;const glow=new maps.Polygon({map:mapObj.current,paths,geodesic:false,strokeColor:base,strokeOpacity:sold?0.95:selected?.65:.28,strokeWeight:sold?9:selected?7:3.5,fillColor:base,fillOpacity:sold?.16:selected?.12:.025,zIndex:sold?500:selected?300:20,clickable:true});const main=new maps.Polygon({map:mapObj.current,paths,geodesic:false,strokeColor:base,strokeOpacity:1,strokeWeight:sold?4:selected?2.8:1.6,fillColor:base,fillOpacity:sold?.08:selected?.18:.015,zIndex:sold?501:selected?301:21,clickable:true});const click=()=>selectRef.current(p.id);glow.addListener("click",click);main.addListener("click",click);cells.current.set(p.id,[glow,main]);const pts=[point(center,r0,a0),point(center,r1,a0),point(center,r0,a1),point(center,r1,a1)];pts.forEach(pt=>{const key=`${pt.lat.toFixed(8)}:${pt.lng.toFixed(8)}`;if(cornerKeys.has(key))return;cornerKeys.add(key);corners.current.set(`${p.id}:${key}`,new maps.Marker({map:mapObj.current,position:pt,icon:cornerIcon(maps,base,selected),clickable:false,zIndex:sold?2000:1000,optimized:true}))})})})});return()=>{cells.current.forEach(ps=>ps.forEach(p=>p.setMap(null)));corners.current.forEach(m=>m.setMap(null));cells.current.clear();corners.current.clear();layouts.current.clear()}},[parcels,ready,center.lat,center.lng,selectedId]);
useEffect(()=>{if(!ready||!mapObj.current||!selectedId)return;const maps=(window as any).google.maps,p=parcels.find(x=>x.id===selectedId),l=layouts.current.get(selectedId);if(!p||!l)return;const pos=point(center,(l.r0+l.r1)/2,(l.start+l.end)/2);if(!info.current)info.current=new maps.InfoWindow({disableAutoPan:true,pixelOffset:new maps.Size(0,-18)});info.current.setPosition(pos);info.current.setContent(`<div style="padding:10px 12px;background:#071223;color:white;border:2px solid ${statusColor(p.status)};border-radius:10px;font:600 12px system-ui;box-shadow:0 0 18px ${statusColor(p.status)}66"><b>${p.parcel_number}</b><br/>${p.status}</div>`);info.current.open({map:mapObj.current})},[selectedId,parcels,ready,center.lat,center.lng]);
useEffect(()=>()=>{info.current?.close();cells.current.forEach(ps=>ps.forEach(p=>p.setMap(null)));corners.current.forEach(m=>m.setMap(null));mapObj.current=null},[]);return <div className="relative h-[560px] w-full overflow-hidden rounded-2xl border border-cyan-300/20 bg-[#071a2d] sm:h-[680px] lg:h-[760px]"><div ref={mapRef} className="absolute inset-0" aria-label="MySkyParcel dairesel gökyüzü parsel haritası"/>{error&&<div className="absolute inset-0 grid place-items-center bg-[#071a2d] p-6 text-center"><div className="rounded-2xl border border-amber-200/20 bg-slate-950/85 p-6"><p className="text-sm font-semibold text-white">Google Maps hazır değil</p><p className="mt-2 text-xs text-white/60">{error}</p></div></div>}</div>}
