import { useEffect, useRef, useState } from "react";
import type { Parcel } from "@/types/parcel";

type CityCenter={lat:number;lng:number};
type ParcelWithGeometry=Parcel&{geometry?:unknown};
type ViewportBounds={minLat:number;minLng:number;maxLat:number;maxLng:number};
type Props={parcels:ParcelWithGeometry[];selectedId:string|null;onSelect:(id:string)=>void;onViewportChange?:(bounds:ViewportBounds)=>void;center:CityCenter};
type Maps=any; type Polygon=any; type Marker=any;
const SCRIPT_ID="myskyparcel-google-maps"; let mapsPromise:Promise<Maps>|null=null;
function loadGoogleMaps(apiKey:string):Promise<Maps>{if(typeof window==="undefined")return Promise.reject(new Error("Google Maps browser ortamında yüklenebilir."));if((window as any).google?.maps)return Promise.resolve((window as any).google.maps);if(mapsPromise)return mapsPromise;mapsPromise=new Promise((resolve,reject)=>{const existing=document.getElementById(SCRIPT_ID) as HTMLScriptElement|null;const finish=()=>{const m=(window as any).google?.maps;if(m)resolve(m);else reject(new Error("Google Maps API yüklenemedi."))};if(existing){existing.addEventListener("load",finish,{once:true});existing.addEventListener("error",()=>reject(new Error("Google Maps script yüklenemedi.")),{once:true});return}const script=document.createElement("script");script.id=SCRIPT_ID;script.async=true;script.defer=true;script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(apiKey)}`;script.onload=finish;script.onerror=()=>reject(new Error("Google Maps script yüklenemedi."));document.head.appendChild(script)});return mapsPromise}
function statusColor(status:Parcel["status"]){return status==="sold"?"#ff1744":status==="reserved"?"#f6c453":"#58e6ff"}
function tierColor(tier:Parcel["tier"]){return tier==="premium"?"#f6c453":tier==="elite"?"#b77cff":"#55c9ff"}
function point(c:CityCenter,r:number,a:number){const cos=Math.max(Math.cos(c.lat*Math.PI/180),.2);return{lat:c.lat+Math.sin(a)*r,lng:c.lng+Math.cos(a)*r/cos}}
function domeCell(center:CityCenter,index:number,total:number,inner:number,outer:number){const cols=Math.max(8,Math.ceil(Math.sqrt(Math.max(total,1)*1.45)));const rows=Math.max(8,Math.ceil(Math.max(total,1)/cols));const col=index%cols,row=Math.floor(index/cols);const u0=col/cols,u1=(col+1)/cols,v0=row/rows,v1=(row+1)/rows;const xy=(u:number,v:number)=>({x:u-.5,y:v-.5});const project=(u:number,v:number)=>{const q=xy(u,v),rad=Math.min(1,Math.sqrt(q.x*q.x+q.y*q.y)*2);const dome=Math.sqrt(Math.max(0,1-rad*rad));const ring=inner+(outer-inner)*(0.5+0.5*(1-dome));const scale=ring;const cos=Math.max(Math.cos(center.lat*Math.PI/180),.2);return{lat:center.lat+q.y*2*scale,lng:center.lng+q.x*2*scale/cos}};return{path:[project(u0,v0),project(u1,v0),project(u1,v1),project(u0,v1)],center:project((u0+u1)/2,(v0+v1)/2)}}
function cornerIcon(maps:Maps,color:string,selected:boolean){const s=selected?14:9;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${s+14}" height="${s+14}" viewBox="0 0 ${s+14} ${s+14}"><defs><filter id="g"><feGaussianBlur stdDeviation="2.5"/></filter></defs><circle cx="${(s+14)/2}" cy="${(s+14)/2}" r="${s/2+3}" fill="${color}" opacity=".65" filter="url(#g)"/><circle cx="${(s+14)/2}" cy="${(s+14)/2}" r="${s/2}" fill="${color}" stroke="#fff" stroke-opacity=".8" stroke-width="${selected?1.8:1}"/></svg>`;return{url:`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`,scaledSize:new maps.Size(s+14,s+14),anchor:new maps.Point((s+14)/2,(s+14)/2)}}
export function GoogleParcelMap({parcels,selectedId,onSelect,onViewportChange,center}:Props){const mapRef=useRef<HTMLDivElement|null>(null),mapObj=useRef<any>(null),cells=useRef<Map<string,Polygon[]>>(new Map()),corners=useRef<Map<string,Marker>>(new Map()),layouts=useRef<Map<string,{position:{lat:number;lng:number}}>>(new Map()),selectRef=useRef(onSelect),viewportRef=useRef(onViewportChange),info=useRef<any>(null);const[error,setError]=useState<string|null>(null),[ready,setReady]=useState(false);useEffect(()=>{selectRef.current=onSelect},[onSelect]);useEffect(()=>{viewportRef.current=onViewportChange},[onViewportChange]);
useEffect(()=>{let cancelled=false;const key=import.meta.env.VITE_GOOGLE_MAPS_API_KEY;if(!key){setError("Google Maps API anahtarı eksik.");return}if(!mapRef.current)return;loadGoogleMaps(key).then(maps=>{if(cancelled||!mapRef.current)return;if(!mapObj.current)mapObj.current=new maps.Map(mapRef.current,{center,zoom:12,mapTypeId:"satellite",streetViewControl:false,fullscreenControl:false,mapTypeControl:false,gestureHandling:"greedy",clickableIcons:false,backgroundColor:"#071a2d"});else mapObj.current.setCenter(center);setError(null);setReady(true)}).catch(e=>{console.error(e);if(!cancelled)setError("Google Maps yüklenemedi. API anahtarını kontrol edin.")});return()=>{cancelled=true}},[center.lat,center.lng]);
useEffect(()=>{if(!ready||!mapObj.current||!viewportRef.current)return;const maps=(window as any).google.maps,map=mapObj.current;const emit=()=>{const b=map.getBounds();if(!b)return;const ne=b.getNorthEast(),sw=b.getSouthWest();viewportRef.current?.({minLat:sw.lat(),minLng:sw.lng(),maxLat:ne.lat(),maxLng:ne.lng()})};const l=maps.event.addListener(map,"idle",emit);emit();return()=>maps.event.removeListener(l)},[ready]);
useEffect(()=>{if(!ready||!mapObj.current)return;const maps=(window as any).google.maps;cells.current.forEach(ps=>ps.forEach(p=>p.setMap(null)));cells.current.clear();corners.current.forEach(m=>m.setMap(null));corners.current.clear();layouts.current.clear();const configs=[{tier:"digital" as const,inner:.030,outer:.090},{tier:"elite" as const,inner:.012,outer:.030},{tier:"premium" as const,inner:.002,outer:.012}];const cornerKeys=new Set<string>();configs.forEach(cfg=>{const items=parcels.filter(p=>p.tier===cfg.tier),total=items.length;items.forEach((p,i)=>{const cell=domeCell(center,i,total,cfg.inner,cfg.outer);layouts.current.set(p.id,{position:cell.center});const paths=cell.path.map(x=>new maps.LatLng(x.lat,x.lng)),sold=p.status==="sold",base=sold?statusColor(p.status):tierColor(p.tier),selected=p.id===selectedId;const glow=new maps.Polygon({map:mapObj.current,paths,geodesic:false,strokeColor:base,strokeOpacity:sold?.95:selected?.65:.28,strokeWeight:sold?7:selected?5:2.5,fillColor:base,fillOpacity:sold?.16:selected?.12:.025,zIndex:sold?500:selected?300:20,clickable:true});const main=new maps.Polygon({map:mapObj.current,paths,geodesic:false,strokeColor:base,strokeOpacity:1,strokeWeight:sold?3:selected?2.2:1.2,fillColor:base,fillOpacity:sold?.08:selected?.18:.015,zIndex:sold?501:selected?301:21,clickable:true});const click=()=>selectRef.current(p.id);glow.addListener("click",click);main.addListener("click",click);cells.current.set(p.id,[glow,main]);cell.path.forEach(pt=>{const key=`${pt.lat.toFixed(8)}:${pt.lng.toFixed(8)}`;if(cornerKeys.has(key))return;cornerKeys.add(key);corners.current.set(`${p.id}:${key}`,new maps.Marker({map:mapObj.current,position:pt,icon:cornerIcon(maps,base,selected),clickable:false,zIndex:sold?2000:1000,optimized:true}))})})});return()=>{cells.current.forEach(ps=>ps.forEach(p=>p.setMap(null)));corners.current.forEach(m=>m.setMap(null));cells.current.clear();corners.current.clear();layouts.current.clear()}},[parcels,ready,center.lat,center.lng,selectedId]);
useEffect(()=>{if(!ready||!mapObj.current||!selectedId)return;const maps=(window as any).google.maps,p=parcels.find(x=>x.id===selectedId),l=layouts.current.get(selectedId);if(!p||!l)return;if(!info.current)info.current=new maps.InfoWindow({disableAutoPan:true,pixelOffset:new maps.Size(0,-18)});info.current.setPosition(l.position);info.current.setContent(`<div style="padding:10px 12px;background:#071223;color:white;border:2px solid ${statusColor(p.status)};border-radius:10px;font:600 12px system-ui;box-shadow:0 0 18px ${statusColor(p.status)}66"><b>${p.parcel_number}</b><br/>${p.status}</div>`);info.current.open({map:mapObj.current})},[selectedId,parcels,ready,center.lat,center.lng]);
useEffect(()=>()=>{info.current?.close();cells.current.forEach(ps=>ps.forEach(p=>p.setMap(null)));corners.current.forEach(m=>m.setMap(null));mapObj.current=null},[]);return <div className="relative h-[560px] w-full overflow-hidden rounded-2xl border border-cyan-300/20 bg-[#071a2d] sm:h-[680px] lg:h-[760px]"><div ref={mapRef} className="absolute inset-0" aria-label="MySkyParcel kubbe parsel haritası"/>{error&&<div className="absolute inset-0 grid place-items-center bg-[#071a2d] p-6 text-center"><div className="rounded-2xl border border-amber-200/20 bg-slate-950/85 p-6"><p className="text-sm font-semibold text-white">Google Maps hazır değil</p><p className="mt-2 text-xs text-white/60">{error}</p></div></div>}</div>}
