import { useEffect, useMemo, useRef } from "react";
import type { MouseEvent, PointerEvent, WheelEvent } from "react";
import type { Parcel, ParcelTier } from "@/types/parcel";

type Props={parcels:Parcel[];selectedId:string|null;onSelect:(id:string)=>void};
type P={x:number;y:number;z:number};
type C={parcel:Parcel;sector:number;row:number;depth:number;center:P;points:P[]};
type L={parcel:Parcel;sector:number;row:number};
type S={yaw:number;pitch:number;zoom:number;dragging:boolean;moved:boolean;lastX:number;lastY:number;vx:number;vy:number};
const SECTORS=100,ROWS=10,VISIBLE=60,PHI0=.05,PHI1=Math.PI*.5;
const G="rgba(151,214,255,.82)",SEL:Record<ParcelTier,string>={digital:"rgba(55,157,255,.84)",elite:"rgba(172,94,255,.88)",premium:"rgba(255,191,48,.92)"},GLOW:Record<ParcelTier,string>={digital:"rgba(82,184,255,1)",elite:"rgba(193,108,255,1)",premium:"rgba(255,201,70,1)"};
const sp=(t:number,p:number):P=>{const s=Math.sin(p);return{x:s*Math.cos(t),y:Math.cos(p),z:s*Math.sin(t)}};
const rot=(p:P,y:number,x:number):P=>{const cy=Math.cos(y),sy=Math.sin(y),a=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy,cp=Math.cos(x),sp=Math.sin(x);return{x:a,y:p.y*cp-z*sp,z:p.y*sp+z*cp}};
const proj=(p:P,r:number,cx:number,cy:number):P=>({x:cx+p.x*r,y:cy-p.y*r,z:p.z});
function code(s:string){const a=s.match(/-S(\d{1,3})-/i),b=s.match(/-P(\d{1,2})$/i);return{sector:a?Math.max(1,Math.min(SECTORS,+a[1]))-1:null,row:b?Math.max(1,Math.min(ROWS,+b[1]))-1:null}}
function layout(ps:Parcel[]):L[]{const out:L[]=[],used=new Set<string>();for(const p of ps){const q=code(String(p.parcel_number||""));if(q.sector==null||q.row==null)continue;const k=`${q.row}:${q.sector}`;if(used.has(k))continue;used.add(k);out.push({parcel:p,sector:q.sector,row:q.row})}let i=0;for(const p of ps){if(out.some(x=>x.parcel.id===p.id))continue;while(i<ROWS*SECTORS&&used.has(`${Math.floor(i/SECTORS)}:${i%SECTORS}`))i++;if(i>=ROWS*SECTORS)break;const row=Math.floor(i/SECTORS),sector=i%SECTORS;used.add(`${row}:${sector}`);out.push({parcel:p,sector,row});i++}return out}
function inside(x:number,y:number,ps:P[]){let ok=false;for(let i=0,j=ps.length-1;i<ps.length;j=i++){const a=ps[i],b=ps[j],hit=a.y>y!==b.y>y&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x;if(hit)ok=!ok}return ok}
function visible(cs:C[],yaw:number){const out:C[]=[];const facing=Math.PI/2-yaw;for(let row=0;row<ROWS;row++){const rs=cs.filter(c=>c.row===row).map(c=>{const t=-Math.PI+2*Math.PI*(c.sector+.5)/SECTORS,d=Math.abs(Math.atan2(Math.sin(t-facing),Math.cos(t-facing)));return{c,d}}).sort((a,b)=>a.d-b.d);for(const x of rs.slice(0,6))out.push(x.c)}return out.slice(0,VISIBLE)}

export function SkyParcelGlobe({parcels,selectedId,onSelect}:Props){
 const canvasRef=useRef<HTMLCanvasElement|null>(null),selectedRef=useRef(selectedId),layoutRef=useRef<L[]>([]),hitRef=useRef<C[]>([]);
 const stateRef=useRef<S>({yaw:0,pitch:.08,zoom:1,dragging:false,moved:false,lastX:0,lastY:0,vx:0,vy:0}),lay=useMemo(()=>layout(parcels),[parcels]);
 useEffect(()=>{selectedRef.current=selectedId},[selectedId]);useEffect(()=>{layoutRef.current=lay},[lay]);
 useEffect(()=>{const canvas=canvasRef.current,ctx=canvas?.getContext("2d");if(!canvas||!ctx)return;let raf=0,w=0,h=0,dpr=1;
  const resize=()=>{const r=canvas.getBoundingClientRect();w=Math.max(320,r.width);h=Math.max(380,r.height);dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)};
  const grid=(r:number,cx:number,cy:number,yaw:number,pitch:number)=>{const halo=ctx.createRadialGradient(cx,cy-r*.62,r*.04,cx,cy,r*1.08);halo.addColorStop(0,"rgba(46,139,255,.045)");halo.addColorStop(.58,"rgba(29,104,198,.028)");halo.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=halo;ctx.beginPath();ctx.ellipse(cx,cy,r,r*.98,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=G;ctx.lineWidth=.8;
   for(let row=0;row<=ROWS;row++){const p=PHI0+(PHI1-PHI0)*row/ROWS;ctx.beginPath();let start=false;for(let i=0;i<=220;i++){const q=rot(sp(-Math.PI+2*Math.PI*i/220,p),yaw,pitch);if(q.z<-.02){start=false;continue}const v=proj(q,r,cx,cy);if(!start){ctx.moveTo(v.x,v.y);start=true}else ctx.lineTo(v.x,v.y)}ctx.stroke()}
   for(let sec=0;sec<SECTORS;sec+=5){const t=-Math.PI+2*Math.PI*sec/SECTORS;ctx.beginPath();let start=false;for(let i=0;i<=110;i++){const q=rot(sp(t,PHI0+(PHI1-PHI0)*i/110),yaw,pitch);if(q.z<-.02){start=false;continue}const v=proj(q,r,cx,cy);if(!start){ctx.moveTo(v.x,v.y);start=true}else ctx.lineTo(v.x,v.y)}ctx.stroke()}
  };
  const draw=()=>{const s=stateRef.current;if(!s.dragging){s.yaw+=s.vx;s.pitch+=s.vy;s.vx*=.9;s.vy*=.9;if(Math.abs(s.vx)<.00002)s.vx=0;if(Math.abs(s.vy)<.00002)s.vy=0}s.pitch=Math.max(-.42,Math.min(.42,s.pitch));const r=Math.min(w*.48,h*.46)*s.zoom,cx=w*.5,cy=Math.min(h-r-18,r+14);ctx.clearRect(0,0,w,h);grid(r,cx,cy,s.yaw,s.pitch);
   const cs:C[]=[];for(const it of layoutRef.current){const t0=-Math.PI+2*Math.PI*it.sector/SECTORS,t1=-Math.PI+2*Math.PI*(it.sector+1)/SECTORS,p0=PHI0+(PHI1-PHI0)*it.row/ROWS,p1=PHI0+(PHI1-PHI0)*(it.row+1)/ROWS,c3=rot(sp((t0+t1)/2,(p0+p1)/2),s.yaw,s.pitch);if(c3.z<=.01)continue;const pts=[sp(t0,p0),sp(t1,p0),sp(t1,p1),sp(t0,p1)].map(p=>proj(rot(p,s.yaw,s.pitch),r,cx,cy)),c=proj(c3,r,cx,cy);cs.push({parcel:it.parcel,sector:it.sector,row:it.row,depth:c3.z,center:c,points:pts})}
   const vis=visible(cs,s.yaw).sort((a,b)=>a.depth-b.depth);hitRef.current=vis;for(const c of vis){ctx.beginPath();c.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.strokeStyle="rgba(170,220,255,.34)";ctx.lineWidth=.75;ctx.stroke()}for(const c of vis)if(c.parcel.id===selectedRef.current){const tier=c.parcel.tier;ctx.save();ctx.beginPath();c.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=SEL[tier];ctx.fill();ctx.strokeStyle=GLOW[tier];ctx.lineWidth=2.2;ctx.shadowColor=GLOW[tier];ctx.shadowBlur=18;ctx.stroke();ctx.shadowBlur=0;const{x,y}=c.center;ctx.fillStyle="#fff4bf";ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?3:7,px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill();ctx.font="600 11px Inter,system-ui,sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.lineWidth=3;ctx.strokeStyle="rgba(3,12,27,.72)";ctx.strokeText(String(c.parcel.parcel_number||""),x,y+18);ctx.fillStyle="#fff";ctx.fillText(String(c.parcel.parcel_number||""),x,y+18);ctx.restore()}
   ctx.save();ctx.beginPath();ctx.arc(cx,cy,r,Math.PI,0);ctx.strokeStyle="rgba(92,181,255,.20)";ctx.lineWidth=1;ctx.shadowColor="rgba(71,163,255,.12)";ctx.shadowBlur=8;ctx.stroke();ctx.restore();raf=requestAnimationFrame(draw)};
  resize();window.addEventListener("resize",resize);raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);window.removeEventListener("resize",resize)}} ,[]);
 const down=(e:PointerEvent<HTMLCanvasElement>)=>{const s=stateRef.current;s.dragging=true;s.moved=false;s.vx=0;s.vy=0;s.lastX=e.clientX;s.lastY=e.clientY;e.currentTarget.setPointerCapture(e.pointerId)};
 const move=(e:PointerEvent<HTMLCanvasElement>)=>{const s=stateRef.current;if(!s.dragging)return;e.preventDefault();const dx=e.clientX-s.lastX,dy=e.clientY-s.lastY;if(Math.abs(dx)+Math.abs(dy)>2)s.moved=true;s.yaw+=dx*.0075;s.pitch=Math.max(-.42,Math.min(.42,s.pitch-dy*.005));s.vx=dx*.0011;s.vy=-dy*.00065;s.lastX=e.clientX;s.lastY=e.clientY};
 const up=(e:PointerEvent<HTMLCanvasElement>)=>{stateRef.current.dragging=false;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}};
 const click=(e:MouseEvent<HTMLCanvasElement>)=>{if(stateRef.current.moved)return;const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best:C|null=null,depth=-Infinity;for(const c of hitRef.current)if(inside(x,y,c.points)&&c.depth>depth){best=c;depth=c.depth}if(best)onSelect(best.parcel.id)};
 const wheel=(e:WheelEvent<HTMLCanvasElement>)=>{e.preventDefault();stateRef.current.zoom=Math.max(.86,Math.min(1.1,stateRef.current.zoom-e.deltaY*.0007))};
 const reset=()=>{const s=stateRef.current;s.yaw=0;s.pitch=.08;s.zoom=1;s.vx=0;s.vy=0};
 return <div className="relative mx-auto h-[540px] w-full max-w-[1060px] touch-none sm:h-[640px]"><canvas ref={canvasRef} className="absolute inset-0 h-full w-full touch-none select-none" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onLostPointerCapture={()=>{stateRef.current.dragging=false}} onClick={click} onWheel={wheel} aria-label="MySkyParcel dijital gökyüzü kubbesi. Sürükleyerek döndürün ve parsele tıklayarak kodunu görün."/><button type="button" onClick={reset} className="absolute right-3 top-3 rounded-xl border border-amber-400/30 bg-slate-950/70 px-4 py-2 text-xs font-medium text-amber-300 backdrop-blur-sm transition hover:bg-slate-900/85">↻ SIFIRLA</button></div>;
}
