import { useEffect, useMemo, useRef } from "react";
import type { Parcel, ParcelTier } from "@/types/parcel";

type Props = { parcels: Parcel[]; selectedId: string | null; onSelect: (id: string) => void; layerFilter?: number | null; sectorFilter?: number | null };
type P3 = { x: number; y: number; z: number };
type Cell = { parcel: Parcel; layer: number; sector: number; center: P3; points: P3[]; depth: number; tier: ParcelTier };
type LayoutCell = { parcel: Parcel; layer: number; sector: number };
type DomeState = { yaw:number; pitch:number; zoom:number; dragging:boolean; moved:boolean; lastX:number; lastY:number; velocityX:number; velocityY:number };

const SECTORS=100, LAYERS=10, VISIBLE_CELLS=220;
const PHI_MIN=0.10, PHI_MAX=Math.PI*0.54, X_SCALE=1.58, Y_SCALE=0.92;
const GRID="rgba(191,231,255,0.38)", GRID_FAINT="rgba(177,224,255,0.11)";
const FILL:Record<ParcelTier,string>={digital:"rgba(54,170,246,0.028)",elite:"rgba(165,101,244,0.038)",premium:"rgba(247,186,63,0.045)"};
const SELECTED:Record<ParcelTier,string>={digital:"rgba(53,170,247,0.22)",elite:"rgba(171,102,247,0.23)",premium:"rgba(247,186,63,0.25)"};
const GLOW:Record<ParcelTier,string>={digital:"rgba(92,205,255,0.98)",elite:"rgba(194,125,255,0.98)",premium:"rgba(255,210,91,0.99)"};

function spherePoint(theta:number,phi:number):P3{const s=Math.sin(phi);return{x:s*Math.cos(theta),y:Math.cos(phi),z:s*Math.sin(theta)}}
function rotatePoint(p:P3,yaw:number,pitch:number):P3{const cy=Math.cos(yaw),sy=Math.sin(yaw),x=p.x*cy-p.z*sy,z0=p.x*sy+p.z*cy,cp=Math.cos(pitch),sp=Math.sin(pitch);return{x,y:p.y*cp-z0*sp,z:p.y*sp+z0*cp}}
function project(p:P3,radius:number,cx:number,cy:number):P3{const depth01=Math.max(0,Math.min(1,(p.z+0.12)/1.12)),centerWeight=Math.max(0,1-Math.abs(p.x)),edgeWeight=Math.min(1,Math.abs(p.x)),hp=0.92+depth01*0.14+edgeWeight*0.18,vp=0.90+depth01*0.12+centerWeight*0.06,curvatureLift=centerWeight*radius*0.045;return{x:cx+p.x*radius*X_SCALE*hp,y:cy-p.y*radius*Y_SCALE*vp-curvatureLift,z:p.z}}
function parseParcelCode(code:string){const s=code.match(/-S(\d{1,3})-/i),l=code.match(/-K(\d{1,3})-/i);return{sector:s?Math.max(1,Math.min(SECTORS,Number(s[1]))):null,layer:l?Math.max(1,Math.min(LAYERS,Number(l[1]))):null}}
function normalizeTier(tier:unknown):ParcelTier{return tier==="elite"||tier==="premium"?tier:"digital"}
function getHierarchy(parcel:Parcel){const parsed=parseParcelCode(String(parcel.parcel_number??"")),layer=parcel.layer_number??parsed.layer,sector=parcel.sector_number??parsed.sector;return{layer:layer?Math.max(1,Math.min(LAYERS,Number(layer))):null,sector:sector?Math.max(1,Math.min(SECTORS,Number(sector))):null}}
function buildLayout(parcels:Parcel[]):LayoutCell[]{const result:LayoutCell[]=[],used=new Set<string>(),placed=new Set<string>();for(const parcel of parcels){const h=getHierarchy(parcel);if(h.layer===null||h.sector===null)continue;const key=`${h.layer}:${h.sector}`;if(used.has(key))continue;used.add(key);placed.add(parcel.id);result.push({parcel,layer:h.layer,sector:h.sector})}let cursor=0;for(const parcel of parcels){if(placed.has(parcel.id))continue;while(cursor<LAYERS*SECTORS){const layer=Math.floor(cursor/SECTORS)+1,sector=cursor%SECTORS+1;if(!used.has(`${layer}:${sector}`))break;cursor++}if(cursor>=LAYERS*SECTORS)break;const layer=Math.floor(cursor/SECTORS)+1,sector=cursor%SECTORS+1;used.add(`${layer}:${sector}`);placed.add(parcel.id);result.push({parcel,layer,sector});cursor++}return result}
function pointInPolygon(x:number,y:number,points:P3[]){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if(!a||!b)continue;const intersect=a.y>y!==b.y>y&&x<((b.x-a.x)*(y-a.y))/(b.y-a.y)+a.x;if(intersect)inside=!inside}return inside}
function drawCurve(ctx:CanvasRenderingContext2D,points:P3[]){if(points.length<2)return;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}

export function SkyParcelDome({parcels,selectedId,onSelect,layerFilter=null,sectorFilter=null}:Props){
 const canvasRef=useRef<HTMLCanvasElement|null>(null),selectedRef=useRef(selectedId),layoutRef=useRef<LayoutCell[]>([]),hitRef=useRef<Cell[]>([]);
 const stateRef=useRef<DomeState>({yaw:0,pitch:-0.12,zoom:1,dragging:false,moved:false,lastX:0,lastY:0,velocityX:0,velocityY:0});
 const layout=useMemo(()=>buildLayout(parcels),[parcels]);
 useEffect(()=>{selectedRef.current=selectedId},[selectedId]);useEffect(()=>{layoutRef.current=layout},[layout]);
 useEffect(()=>{
  const canvas=canvasRef.current,ctx=canvas?.getContext("2d");if(!canvas||!ctx)return;let raf=0,width=0,height=0,dpr=1;
  const resize=()=>{const r=canvas.getBoundingClientRect();width=Math.max(320,r.width);height=Math.max(440,r.height);dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)};
  const atmosphere=()=>{const g=ctx.createLinearGradient(0,0,0,height);g.addColorStop(0,"rgba(111,198,255,.025)");g.addColorStop(.52,"rgba(72,170,239,.012)");g.addColorStop(1,"rgba(4,28,55,.10)");ctx.fillStyle=g;ctx.fillRect(0,0,width,height);const glow=ctx.createRadialGradient(width*.5,height*.16,0,width*.5,height*.30,width*.72);glow.addColorStop(0,"rgba(239,252,255,.10)");glow.addColorStop(.45,"rgba(104,203,255,.025)");glow.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=glow;ctx.fillRect(0,0,width,height*.76)};
  const domePoint=(theta:number,phi:number,yaw:number,pitch:number,r:number,cx:number,cy:number)=>project(rotatePoint(spherePoint(theta,phi),yaw,pitch),r,cx,cy);
  const drawDome=(r:number,cx:number,cy:number,yaw:number,pitch:number)=>{ctx.save();ctx.lineCap="round";ctx.lineJoin="round";const halo=ctx.createRadialGradient(cx,cy-r*.92,0,cx,cy-r*.22,r*1.38);halo.addColorStop(0,"rgba(111,210,255,.075)");halo.addColorStop(.45,"rgba(60,168,236,.025)");halo.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=halo;ctx.beginPath();ctx.ellipse(cx,cy-r*.13,r*1.42,r*1.02,0,Math.PI,Math.PI*2);ctx.fill();
   for(let layer=0;layer<=LAYERS;layer++){const phi=PHI_MIN+(PHI_MAX-PHI_MIN)*(layer/LAYERS),pts:P3[]=[];for(let i=0;i<=280;i++){const theta=-Math.PI-.16+(2*Math.PI+.32)*i/280,p=domePoint(theta,phi,yaw,pitch,r,cx,cy);if(p.z>-.45)pts.push(p)}const centerLift=layer<3?.06:0;ctx.strokeStyle=layer===0?"rgba(238,251,255,.68)":`rgba(191,231,255,${.30+centerLift})`;ctx.lineWidth=layer===0?1.15:.62+(LAYERS-layer)*.008;drawCurve(ctx,pts)}
   for(let sector=0;sector<SECTORS;sector+=2){const theta=-Math.PI+2*Math.PI*sector/SECTORS,pts:P3[]=[];for(let i=0;i<=140;i++){const phi=PHI_MIN+(PHI_MAX-PHI_MIN)*i/140,p=domePoint(theta,phi,yaw,pitch,r,cx,cy);if(p.z>-.45)pts.push(p)}ctx.strokeStyle=sector%10===0?"rgba(219,247,255,.44)":GRID_FAINT;ctx.lineWidth=sector%10===0?.78:.48;drawCurve(ctx,pts)}
   const rimY=cy+r*.025;ctx.strokeStyle="rgba(211,244,255,.32)";ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(cx,rimY,r*1.48,r*.31,0,Math.PI,Math.PI*2);ctx.stroke();ctx.strokeStyle="rgba(189,231,255,.095)";ctx.lineWidth=.52;for(let i=-12;i<=12;i++){const sx=cx+i*r*.12,ex=cx+i*r*.58;ctx.beginPath();ctx.moveTo(sx,rimY-r*.015);ctx.bezierCurveTo(cx+i*r*.18,rimY+r*.08,cx+i*r*.38,height*.78,ex,height+r*.20);ctx.stroke()}ctx.strokeStyle="rgba(206,241,255,.08)";ctx.lineWidth=.7;ctx.beginPath();ctx.ellipse(cx,rimY+r*.06,r*1.62,r*.42,0,Math.PI,Math.PI*2);ctx.stroke();ctx.restore()};
  const draw=()=>{const state=stateRef.current;if(!state.dragging){state.yaw+=state.velocityX;state.pitch+=state.velocityY;state.velocityX*=.91;state.velocityY*=.91;if(Math.abs(state.velocityX)<.00002)state.velocityX=0;if(Math.abs(state.velocityY)<.00002)state.velocityY=0}state.pitch=Math.max(-.34,Math.min(.26,state.pitch));const r=Math.min(width*.72,height*.86)*state.zoom,cx=width*.5,cy=height*.87;ctx.clearRect(0,0,width,height);atmosphere();drawDome(r,cx,cy,state.yaw,state.pitch);
   const filtered=layerFilter!==null||sectorFilter!==null;
   const cells:Cell[]=[];for(const item of layoutRef.current){const phi0=PHI_MIN+(PHI_MAX-PHI_MIN)*(item.layer-1)/LAYERS,phi1=PHI_MIN+(PHI_MAX-PHI_MIN)*item.layer/LAYERS,theta0=-Math.PI+2*Math.PI*(item.sector-1)/SECTORS,theta1=-Math.PI+2*Math.PI*item.sector/SECTORS,c3=rotatePoint(spherePoint((theta0+theta1)*.5,(phi0+phi1)*.5),state.yaw,state.pitch);if(c3.z<=-.05)continue;const points=[spherePoint(theta0,phi0),spherePoint(theta1,phi0),spherePoint(theta1,phi1),spherePoint(theta0,phi1)].map(p=>project(rotatePoint(p,state.yaw,state.pitch),r,cx,cy)),center=project(c3,r,cx,cy);if(center.x< -r*.7||center.x>width+r*.7||center.y< -r*1.1||center.y>height+r*.3)continue;cells.push({parcel:item.parcel,layer:item.layer,sector:item.sector,center,points,depth:c3.z,tier:normalizeTier(item.parcel.tier)})}
   cells.sort((a,b)=>a.depth-b.depth);const visible=cells.slice(Math.max(0,cells.length-VISIBLE_CELLS));hitRef.current=visible;
   for(const cell of visible){const match=(layerFilter===null||cell.layer===layerFilter)&&(sectorFilter===null||cell.sector===sectorFilter),selected=cell.parcel.id===selectedRef.current,depth01=Math.max(0,Math.min(1,(cell.depth+.05)/1.05)),edge01=Math.min(1,Math.abs(cell.center.x-cx)/Math.max(1,r*X_SCALE)),edgeFade=.90-edge01*.28,statusOpacity=cell.parcel.status==="sold"?.43:cell.parcel.status==="reserved"?.62:1,focus=filtered?(match?1:.12):1,baseAlpha=statusOpacity*(.25+depth01*.75)*edgeFade*focus;
    ctx.save();ctx.globalAlpha=baseAlpha;ctx.beginPath();cell.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=selected?SELECTED[cell.tier]:FILL[cell.tier];ctx.globalAlpha*=.52+depth01*.30;ctx.fill();
    ctx.globalAlpha=baseAlpha*.82;ctx.lineWidth=selected?2.3:.32+depth01*.48;ctx.strokeStyle=selected?GLOW[cell.tier]:GRID;ctx.stroke();
    if(cell.parcel.status==="reserved"){ctx.setLineDash([3,3]);ctx.globalAlpha=baseAlpha*.78;ctx.strokeStyle="rgba(255,225,139,.48)";ctx.lineWidth=.72;ctx.stroke();ctx.setLineDash([])}
    if(selected){ctx.globalAlpha=1;ctx.shadowColor=GLOW[cell.tier];ctx.shadowBlur=20;ctx.strokeStyle=GLOW[cell.tier];ctx.lineWidth=2.7;ctx.stroke();ctx.shadowBlur=0;const pulse=1+Math.sin(performance.now()/260)*.16,glow=ctx.createRadialGradient(cell.center.x,cell.center.y,0,cell.center.x,cell.center.y,18*pulse);glow.addColorStop(0,"rgba(255,255,255,.98)");glow.addColorStop(.12,GLOW[cell.tier]);glow.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cell.center.x,cell.center.y,18*pulse,0,Math.PI*2);ctx.fill()}
    if(filtered&&match&&!selected){const pulse=.72+.28*Math.sin(performance.now()/520);ctx.globalAlpha=.38*pulse;ctx.fillStyle="rgba(220,249,255,.95)";ctx.beginPath();ctx.arc(cell.center.x,cell.center.y,1.4+2*pulse,0,Math.PI*2);ctx.fill()}
    ctx.restore()}
   if(filtered){ctx.save();ctx.globalAlpha=.16;ctx.strokeStyle="rgba(225,248,255,.88)";ctx.lineWidth=.62;for(let i=0;i<visible.length;i++){const a=visible[i],matchA=(layerFilter===null||a.layer===layerFilter)&&(sectorFilter===null||a.sector===sectorFilter);if(!matchA||i%2!==0)continue;const right=visible.find(b=>b.layer===a.layer&&b.sector===a.sector+1&&((layerFilter===null||b.layer===layerFilter)&&(sectorFilter===null||b.sector===sectorFilter))),down=visible.find(b=>b.sector===a.sector&&b.layer===a.layer+1&&((layerFilter===null||b.layer===layerFilter)&&(sectorFilter===null||b.sector===sectorFilter)));if(right){ctx.beginPath();ctx.moveTo(a.points[1].x,a.points[1].y);ctx.lineTo(right.points[0].x,right.points[0].y);ctx.stroke()}if(down){ctx.beginPath();ctx.moveTo(a.points[3].x,a.points[3].y);ctx.lineTo(down.points[0].x,down.points[0].y);ctx.stroke()}}ctx.restore()}
   raf=requestAnimationFrame(draw)};
  const down=(e:PointerEvent)=>{const s=stateRef.current;s.dragging=true;s.moved=false;s.lastX=e.clientX;s.lastY=e.clientY;s.velocityX=0;s.velocityY=0;canvas.setPointerCapture(e.pointerId)};
  const move=(e:PointerEvent)=>{const s=stateRef.current;if(!s.dragging)return;const dx=e.clientX-s.lastX,dy=e.clientY-s.lastY;if(Math.abs(dx)+Math.abs(dy)>2)s.moved=true;s.yaw+=dx*.0042;s.pitch+=dy*.003;s.velocityX=dx*.0008;s.velocityY=dy*.0005;s.lastX=e.clientX;s.lastY=e.clientY};
  const up=(e:PointerEvent)=>{const s=stateRef.current;s.dragging=false;if(!s.moved){const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,target=[...hitRef.current].reverse().find(c=>pointInPolygon(x,y,c.points));if(target)onSelect(target.parcel.id)}if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)};
  const wheel=(e:WheelEvent)=>{e.preventDefault();stateRef.current.zoom=Math.max(.82,Math.min(1.28,stateRef.current.zoom*(e.deltaY>0?.94:1.06)))};
  resize();window.addEventListener("resize",resize);canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);canvas.addEventListener("wheel",wheel,{passive:false});raf=requestAnimationFrame(draw);
  return()=>{cancelAnimationFrame(raf);window.removeEventListener("resize",resize);canvas.removeEventListener("pointerdown",down);canvas.removeEventListener("pointermove",move);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("pointercancel",up);canvas.removeEventListener("wheel",wheel)};
 },[layerFilter,sectorFilter,onSelect]);
 return <canvas ref={canvasRef} aria-label="MySkyParcel gökyüzü parsel haritası" className="absolute inset-0 h-full w-full touch-none select-none"/>;
}
