import { useEffect, useRef } from "react";
import type { MouseEvent, PointerEvent, WheelEvent } from "react";
import type { Parcel } from "@/types/parcel";

type Props={parcels:Parcel[];selectedId:string|null;onSelect:(id:string)=>void};
type P={x:number;y:number;z:number};
type Hit={parcel:Parcel;points:P[];center:P;depth:number;sector:number};
type State={yaw:number;pitch:number;zoom:number;dragging:boolean;moved:boolean;lastX:number;lastY:number;vx:number;vy:number};
const C={digital:"#4da3ff",elite:"#b68cff",premium:"#e8ad3f"} as const;
const n=(p:Parcel)=>Number(p.parcel_number.split("-").pop()||1);
const sec=(p:Parcel)=>Math.max(1,Math.min(100,Math.ceil(n(p)/10)));
const row=(p:Parcel)=>(n(p)-1)%10;
const tier=(p:Parcel)=>p.tier==="elite"||p.tier==="premium"?p.tier:"digital";
function rot(p:P,y:number,pi:number):P{const cy=Math.cos(y),sy=Math.sin(y),cp=Math.cos(pi),sp=Math.sin(pi);const x=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy;return{x,y:p.y*cp-z*sp,z:p.y*sp+z*cp};}
function pt(lon:number,e:number):P{const a=lon*Math.PI/180,r=e*Math.PI/180,c=Math.cos(r);return{x:c*Math.sin(a),y:Math.sin(r),z:c*Math.cos(a)};}
function star(ctx:CanvasRenderingContext2D,x:number,y:number,r:number){ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?r*.38:r,px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill();}
export function SkyParcelDomeReference({parcels,selectedId,onSelect}:Props){
 const canvasRef=useRef<HTMLCanvasElement>(null),sel=useRef(selectedId),data=useRef(parcels),hits=useRef<Hit[]>([]);
 const sref=useRef<State>({yaw:-.34,pitch:.06,zoom:1,dragging:false,moved:false,lastX:0,lastY:0,vx:0,vy:0});
 useEffect(()=>{sel.current=selectedId;data.current=parcels},[selectedId,parcels]);
 useEffect(()=>{const canvas=canvasRef.current,ctx=canvas?.getContext("2d");if(!canvas||!ctx)return;let raf=0,w=0,h=0,dpr=1;
  const resize=()=>{const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);w=Math.max(320,r.width);h=Math.max(430,r.height);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};
  const proj=(p:P,r:number,cx:number,cy:number)=>({x:cx+p.x*r,y:cy-p.y*r,z:p.z});
  const draw=()=>{const s=sref.current;if(!s.dragging){s.yaw+=s.vx;s.pitch+=s.vy;s.vx*=.94;s.vy*=.94}s.pitch=Math.max(-.42,Math.min(.55,s.pitch));const r=Math.min(w*.49,h*.46)*s.zoom,cx=w/2,base=h*.57;ctx.clearRect(0,0,w,h);
   const halo=ctx.createRadialGradient(cx,base-r*.82,r*.04,cx,base-r*.38,r*1.28);halo.addColorStop(0,"rgba(48,143,255,.13)");halo.addColorStop(.62,"rgba(48,143,255,.045)");halo.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=halo;ctx.beginPath();ctx.arc(cx,base,r*1.24,Math.PI,Math.PI*2);ctx.fill();
   ctx.save();ctx.beginPath();ctx.rect(0,0,w,base+2);ctx.clip();const fill=ctx.createLinearGradient(cx,base-r,cx,base);fill.addColorStop(0,"rgba(35,125,225,.12)");fill.addColorStop(.42,"rgba(14,78,145,.065)");fill.addColorStop(.74,"rgba(8,52,105,.025)");fill.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=fill;ctx.beginPath();ctx.arc(cx,base,r,Math.PI,Math.PI*2);ctx.fill();
   for(let e=10;e<=80;e+=10){ctx.beginPath();let on=false;for(let lon=-90;lon<=90;lon+=3){const p=rot(pt(lon,e),s.yaw,s.pitch);if(p.z<-.08||p.y<0){on=false;continue}const q=proj(p,r,cx,base);on?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);on=true}ctx.lineWidth=.75;ctx.strokeStyle=`rgba(120,190,255,${(.08+e/80*.15).toFixed(3)})`;ctx.stroke()}
   for(let lon=-90;lon<=90;lon+=10){ctx.beginPath();let on=false;for(let e=0;e<=90;e+=3){const p=rot(pt(lon,e),s.yaw,s.pitch);if(p.z<-.08||p.y<0){on=false;continue}const q=proj(p,r,cx,base);on?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);on=true}ctx.lineWidth=.7;ctx.strokeStyle="rgba(120,190,255,.16)";ctx.stroke()}
   const by=new Map<number,Parcel[]>();[...data.current()].sort((a,b)=>n(a)-n(b)).forEach(p=>{const k=sec(p),list=by.get(k)||[];list.push(p);by.set(k,list)});
   const center=((Math.round((((s.yaw/(Math.PI*2))%1+1)%1)*100)+50)%100)+1,visible:number[]=[];for(let i=-2;i<=3;i++)visible.push(((center-1+i+100)%100)+1);
   const hs:Hit[]=[];visible.forEach(k=>{const list=(by.get(k)||[]).sort((a,b)=>row(a)-row(b));for(let rr=0;rr<10;rr++){const p=list.find(x=>row(x)===rr);if(!p)continue;const lon0=-90+(k-1)*1.8+.08,lon1=lon0+1.64,e0=8+rr*7.2,e1=e0+6.2,raw=[pt(lon0,e0),pt(lon1,e0),pt(lon1,e1),pt(lon0,e1)].map(x=>rot(x,s.yaw,s.pitch)),c=rot(pt((lon0+lon1)/2,(e0+e1)/2),s.yaw,s.pitch);if(c.z<.02||c.y<-.08)continue;hs.push({parcel:p,points:raw.map(x=>proj(x,r,cx,base)),center:proj(c,r,cx,base),depth:c.z,sector:k})}});hs.sort((a,b)=>a.depth-b.depth);hits.current=hs;
   for(const item of hs){const selected=item.parcel.id===sel.current,color=C[tier(item.parcel)],v=Math.max(.22,Math.min(1,item.depth));ctx.beginPath();item.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=selected?`${color}d9`:`${color}${Math.round((.035+v*.07)*255).toString(16).padStart(2,"0")}`;ctx.fill();ctx.lineWidth=selected?2.8:1.45;ctx.strokeStyle=selected?color:`${color}${Math.round((.46+v*.42)*255).toString(16).padStart(2,"0")}`;ctx.stroke();ctx.font="700 9px Inter,system-ui,sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle=`rgba(238,247,255,${Math.min(.95,.58+v*.35)})`;ctx.fillText(`S${item.sector}`,item.center.x,item.center.y);if(selected){ctx.save();ctx.shadowColor=color;ctx.shadowBlur=24;ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();item.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.fillStyle="#fff7d6";star(ctx,item.center.x,item.center.y,Math.max(8,r*.018));ctx.restore();const label=item.parcel.parcel_number;ctx.font="700 12px Inter,system-ui,sans-serif";ctx.textAlign="left";const lw=ctx.measureText(label).width+26,bx=Math.min(w-lw-12,Math.max(12,item.center.x+18)),by=Math.max(12,item.center.y-48);ctx.fillStyle="rgba(3,12,27,.97)";ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(bx,by,lw,32,7);ctx.fill();ctx.stroke();ctx.fillStyle="#fff";ctx.fillText(label,bx+13,by+21)}}
   const edge=ctx.createLinearGradient(cx,base,cx,base-r);edge.addColorStop(0,"rgba(80,160,240,0)");edge.addColorStop(.58,"rgba(80,160,240,.08)");edge.addColorStop(1,"rgba(124,198,255,.34)");ctx.save();ctx.lineWidth=1.3;ctx.shadowColor="rgba(77,165,255,.18)";ctx.shadowBlur=9;ctx.strokeStyle=edge;ctx.beginPath();ctx.arc(cx,base,r,Math.PI,Math.PI*2);ctx.stroke();ctx.restore();ctx.restore();raf=requestAnimationFrame(draw)};
  resize();window.addEventListener("resize",resize);raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);window.removeEventListener("resize",resize)}
 },[]);
 const down=(e:PointerEvent<HTMLCanvasElement>)=>{const s=sref.current;s.dragging=true;s.moved=false;s.vx=0;s.vy=0;s.lastX=e.clientX;s.lastY=e.clientY;e.currentTarget.setPointerCapture(e.pointerId)};
 const move=(e:PointerEvent<HTMLCanvasElement>)=>{const s=sref.current;if(!s.dragging)return;const dx=e.clientX-s.lastX,dy=e.clientY-s.lastY;if(Math.abs(dx)+Math.abs(dy)>3)s.moved=true;s.yaw-=dx*.0068;s.pitch=Math.max(-.42,Math.min(.55,s.pitch-dy*.004));s.vx=-dx*.00105;s.vy=-dy*.0005;s.lastX=e.clientX;s.lastY=e.clientY};
 const up=(e:PointerEvent<HTMLCanvasElement>)=>{sref.current.dragging=false;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}};
 const click=(e:MouseEvent<HTMLCanvasElement>)=>{if(sref.current.moved)return;const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best:Hit|null=null;for(const item of hits.current){const d=Math.hypot(x-item.center.x,y-item.center.y);if(d<28&&(!best||item.depth>best.depth||d<Math.hypot(x-best.center.x,y-best.center.y)))best=item}if(best)onSelect(best.parcel.id)};
 const wheel=(e:WheelEvent<HTMLCanvasElement>)=>{e.preventDefault();sref.current.zoom=Math.max(.86,Math.min(1.1,sref.current.zoom-e.deltaY*.0005))};
 const reset=()=>{sref.current.yaw=-.34;sref.current.pitch=.06;sref.current.zoom=1;sref.current.vx=0;sref.current.vy=0};
 return <div className="relative w-full -mt-2 sm:-mt-4"><canvas ref={canvasRef} className="h-[540px] w-full touch-none select-none sm:h-[600px]" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onClick={click} onWheel={wheel} aria-label="Havada duran dijital gökyüzü kubbesi"/><div className="pointer-events-none absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full border border-gold/30 bg-navy-deep/70 px-4 py-2 text-[10px] text-muted-foreground"><span className="text-gold">Premium %20</span> · <span className="text-violet-300">Elit %30</span> · <span className="text-blue-300">Dijital %50</span></div><button type="button" onClick={reset} className="absolute right-3 top-3 rounded-md border border-gold/25 bg-navy-deep/65 px-3 py-2 text-[10px] text-gold backdrop-blur-sm">↻ SIFIRLA</button></div>;
}