/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminCheckRouteImport } from './routes/admin-check'
import { Route as AnaSayfaRouteImport } from './routes/ana-sayfa'
import { Route as BildirimlerRouteImport } from './routes/bildirimler'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as DestekRouteImport } from './routes/destek'
import { Route as DogrulaRouteImport } from './routes/dogrula'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as GokyuzuHaritasiRouteImport } from './routes/gokyuzu-haritasi'
import { Route as GuvenlikAyarlariRouteImport } from './routes/guvenlik-ayarlari'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HediyeKabulRouteImport } from './routes/hediye-kabul'
import { Route as HediyelerimRouteImport } from './routes/hediyelerim'
import { Route as IadeIptalPolitikasiRouteImport } from './routes/iade-iptal-politikasi'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KayitOlRouteImport } from './routes/kayit-ol'
import { Route as KullanimSartlariRouteImport } from './routes/kullanim-sartlari'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as MesafeliSatisSozlesmesiRouteImport } from './routes/mesafeli-satis-sozlesmesi'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as OnBilgilendirmeFormuRouteImport } from './routes/on-bilgilendirme-formu'
import { Route as PaketlerRouteImport } from './routes/paketler'
import { Route as PanelimRouteImport } from './routes/panelim'
import { Route as ParselHatirasiRouteImport } from './routes/parsel-hatirasi'
import { Route as ParselSatinAlRouteImport } from './routes/parsel-satin-al'
import { Route as ParsellerimRouteImport } from './routes/parsellerim'
import { Route as PazarYeriRouteImport } from './routes/pazar-yeri'
import { Route as ProfilimRouteImport } from './routes/profilim'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PurchaseBulkRouteImport } from './routes/purchase-bulk'
import { Route as SertifikaDogrulaRouteImport } from './routes/sertifika-dogrula'
import { Route as SertifikaTalepRouteImport } from './routes/sertifika-talep'
import { Route as SertifikalarimRouteImport } from './routes/sertifikalarim'
import { Route as SifreYenileRouteImport } from './routes/sifre-yenile'
import { Route as SifremiUnuttumRouteImport } from './routes/sifremi-unuttum'
import { Route as SiparislerimRouteImport } from './routes/siparislerim'
import { Route as TurkiyeHaritasiRouteImport } from './routes/turkiye-haritasi'
import { Route as UyelikSozlesmesiRouteImport } from './routes/uyelik-sozlesmesi'
import { Route as YonetimRouteImport } from './routes/yonetim'
import { Route as ApiEarthAssetsRouteImport } from './routes/api/earth-assets'
import { Route as SehirSlugRouteImport } from './routes/sehir/$slug'
import { Route as ApiShopierCheckoutRouteImport } from './routes/api/shopier/checkout'
import { Route as ApiShopierRedirectRouteImport } from './routes/api/shopier/redirect'
import { Route as ApiShopierWebhookRouteImport } from './routes/api/shopier/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckRoute = AdminCheckRouteImport.update({
  id: '/admin-check',
  path: '/admin-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaSayfaRoute = AnaSayfaRouteImport.update({
  id: '/ana-sayfa',
  path: '/ana-sayfa',
  getParentRoute: () => rootRouteImport,
} as any)
const BildirimlerRoute = BildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const DestekRoute = DestekRouteImport.update({
  id: '/destek',
  path: '/destek',
  getParentRoute: () => rootRouteImport,
} as any)
const DogrulaRoute = DogrulaRouteImport.update({
  id: '/dogrula',
  path: '/dogrula',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const GokyuzuHaritasiRoute = GokyuzuHaritasiRouteImport.update({
  id: '/gokyuzu-haritasi',
  path: '/gokyuzu-haritasi',
  getParentRoute: () => rootRouteImport,
} as any)
const GuvenlikAyarlariRoute = GuvenlikAyarlariRouteImport.update({
  id: '/guvenlik-ayarlari',
  path: '/guvenlik-ayarlari',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HediyeKabulRoute = HediyeKabulRouteImport.update({
  id: '/hediye-kabul',
  path: '/hediye-kabul',
  getParentRoute: () => rootRouteImport,
} as any)
const HediyelerimRoute = HediyelerimRouteImport.update({
  id: '/hediyelerim',
  path: '/hediyelerim',
  getParentRoute: () => rootRouteImport,
} as any)
const IadeIptalPolitikasiRoute = IadeIptalPolitikasiRouteImport.update({
  id: '/iade-iptal-politikasi',
  path: '/iade-iptal-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitOlRoute = KayitOlRouteImport.update({
  id: '/kayit-ol',
  path: '/kayit-ol',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanimSartlariRoute = KullanimSartlariRouteImport.update({
  id: '/kullanim-sartlari',
  path: '/kullanim-sartlari',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const MesafeliSatisSozlesmesiRoute = MesafeliSatisSozlesmesiRouteImport.update({
  id: '/mesafeli-satis-sozlesmesi',
  path: '/mesafeli-satis-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const OnBilgilendirmeFormuRoute = OnBilgilendirmeFormuRouteImport.update({
  id: '/on-bilgilendirme-formu',
  path: '/on-bilgilendirme-formu',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketlerRoute = PaketlerRouteImport.update({
  id: '/paketler',
  path: '/paketler',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelimRoute = PanelimRouteImport.update({
  id: '/panelim',
  path: '/panelim',
  getParentRoute: () => rootRouteImport,
} as any)
const ParselHatirasiRoute = ParselHatirasiRouteImport.update({
  id: '/parsel-hatirasi',
  path: '/parsel-hatirasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ParselSatinAlRoute = ParselSatinAlRouteImport.update({
  id: '/parsel-satin-al',
  path: '/parsel-satin-al',
  getParentRoute: () => rootRouteImport,
} as any)
const ParsellerimRoute = ParsellerimRouteImport.update({
  id: '/parsellerim',
  path: '/parsellerim',
  getParentRoute: () => rootRouteImport,
} as any)
const PazarYeriRoute = PazarYeriRouteImport.update({
  id: '/pazar-yeri',
  path: '/pazar-yeri',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilimRoute = ProfilimRouteImport.update({
  id: '/profilim',
  path: '/profilim',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseBulkRoute = PurchaseBulkRouteImport.update({
  id: '/purchase-bulk',
  path: '/purchase-bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikaDogrulaRoute = SertifikaDogrulaRouteImport.update({
  id: '/sertifika-dogrula',
  path: '/sertifika-dogrula',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikaTalepRoute = SertifikaTalepRouteImport.update({
  id: '/sertifika-talep',
  path: '/sertifika-talep',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikalarimRoute = SertifikalarimRouteImport.update({
  id: '/sertifikalarim',
  path: '/sertifikalarim',
  getParentRoute: () => rootRouteImport,
} as any)
const SifreYenileRoute = SifreYenileRouteImport.update({
  id: '/sifre-yenile',
  path: '/sifre-yenile',
  getParentRoute: () => rootRouteImport,
} as any)
const SifremiUnuttumRoute = SifremiUnuttumRouteImport.update({
  id: '/sifremi-unuttum',
  path: '/sifremi-unuttum',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparislerimRoute = SiparislerimRouteImport.update({
  id: '/siparislerim',
  path: '/siparislerim',
  getParentRoute: () => rootRouteImport,
} as any)
const TurkiyeHaritasiRoute = TurkiyeHaritasiRouteImport.update({
  id: '/turkiye-haritasi',
  path: '/turkiye-haritasi',
  getParentRoute: () => rootRouteImport,
} as any)
const UyelikSozlesmesiRoute = UyelikSozlesmesiRouteImport.update({
  id: '/uyelik-sozlesmesi',
  path: '/uyelik-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEarthAssetsRoute = ApiEarthAssetsRouteImport.update({
  id: '/api/earth-assets',
  path: '/api/earth-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const SehirSlugRoute = SehirSlugRouteImport.update({
  id: '/sehir/$slug',
  path: '/sehir/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopierCheckoutRoute = ApiShopierCheckoutRouteImport.update({
  id: '/api/shopier/checkout',
  path: '/api/shopier/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopierRedirectRoute = ApiShopierRedirectRouteImport.update({
  id: '/api/shopier/redirect',
  path: '/api/shopier/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopierWebhookRoute = ApiShopierWebhookRouteImport.update({
  id: '/api/shopier/webhook',
  path: '/api/shopier/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-check': typeof AdminCheckRoute
  '/ana-sayfa': typeof AnaSayfaRoute
  '/bildirimler': typeof BildirimlerRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/destek': typeof DestekRoute
  '/dogrula': typeof DogrulaRoute
  '/giris': typeof GirisRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/gokyuzu-haritasi': typeof GokyuzuHaritasiRoute
  '/guvenlik-ayarlari': typeof GuvenlikAyarlariRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hediye-kabul': typeof HediyeKabulRoute
  '/hediyelerim': typeof HediyelerimRoute
  '/iade-iptal-politikasi': typeof IadeIptalPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/kayit-ol': typeof KayitOlRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/on-bilgilendirme-formu': typeof OnBilgilendirmeFormuRoute
  '/paketler': typeof PaketlerRoute
  '/panelim': typeof PanelimRoute
  '/parsel-hatirasi': typeof ParselHatirasiRoute
  '/parsel-satin-al': typeof ParselSatinAlRoute
  '/parsellerim': typeof ParsellerimRoute
  '/pazar-yeri': typeof PazarYeriRoute
  '/profilim': typeof ProfilimRoute
  '/purchase': typeof PurchaseRoute
  '/purchase-bulk': typeof PurchaseBulkRoute
  '/sertifika-dogrula': typeof SertifikaDogrulaRoute
  '/sertifika-talep': typeof SertifikaTalepRoute
  '/sertifikalarim': typeof SertifikalarimRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/siparislerim': typeof SiparislerimRoute
  '/turkiye-haritasi': typeof TurkiyeHaritasiRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/yonetim': typeof YonetimRoute
  '/api/earth-assets': typeof ApiEarthAssetsRoute
  '/sehir/$slug': typeof SehirSlugRoute
  '/api/shopier/checkout': typeof ApiShopierCheckoutRoute
  '/api/shopier/redirect': typeof ApiShopierRedirectRoute
  '/api/shopier/webhook': typeof ApiShopierWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-check': typeof AdminCheckRoute
  '/ana-sayfa': typeof AnaSayfaRoute
  '/bildirimler': typeof BildirimlerRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/destek': typeof DestekRoute
  '/dogrula': typeof DogrulaRoute
  '/giris': typeof GirisRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/gokyuzu-haritasi': typeof GokyuzuHaritasiRoute
  '/guvenlik-ayarlari': typeof GuvenlikAyarlariRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hediye-kabul': typeof HediyeKabulRoute
  '/hediyelerim': typeof HediyelerimRoute
  '/iade-iptal-politikasi': typeof IadeIptalPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/kayit-ol': typeof KayitOlRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/on-bilgilendirme-formu': typeof OnBilgilendirmeFormuRoute
  '/paketler': typeof PaketlerRoute
  '/panelim': typeof PanelimRoute
  '/parsel-hatirasi': typeof ParselHatirasiRoute
  '/parsel-satin-al': typeof ParselSatinAlRoute
  '/parsellerim': typeof ParsellerimRoute
  '/pazar-yeri': typeof PazarYeriRoute
  '/profilim': typeof ProfilimRoute
  '/purchase': typeof PurchaseRoute
  '/purchase-bulk': typeof PurchaseBulkRoute
  '/sertifika-dogrula': typeof SertifikaDogrulaRoute
  '/sertifika-talep': typeof SertifikaTalepRoute
  '/sertifikalarim': typeof SertifikalarimRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/siparislerim': typeof SiparislerimRoute
  '/turkiye-haritasi': typeof TurkiyeHaritasiRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/yonetim': typeof YonetimRoute
  '/api/earth-assets': typeof ApiEarthAssetsRoute
  '/sehir/$slug': typeof SehirSlugRoute
  '/api/shopier/checkout': typeof ApiShopierCheckoutRoute
  '/api/shopier/redirect': typeof ApiShopierRedirectRoute
  '/api/shopier/webhook': typeof ApiShopierWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-check': typeof AdminCheckRoute
  '/ana-sayfa': typeof AnaSayfaRoute
  '/bildirimler': typeof BildirimlerRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/destek': typeof DestekRoute
  '/dogrula': typeof DogrulaRoute
  '/giris': typeof GirisRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/gokyuzu-haritasi': typeof GokyuzuHaritasiRoute
  '/guvenlik-ayarlari': typeof GuvenlikAyarlariRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hediye-kabul': typeof HediyeKabulRoute
  '/hediyelerim': typeof HediyelerimRoute
  '/iade-iptal-politikasi': typeof IadeIptalPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/kayit-ol': typeof KayitOlRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/on-bilgilendirme-formu': typeof OnBilgilendirmeFormuRoute
  '/paketler': typeof PaketlerRoute
  '/panelim': typeof PanelimRoute
  '/parsel-hatirasi': typeof ParselHatirasiRoute
  '/parsel-satin-al': typeof ParselSatinAlRoute
  '/parsellerim': typeof ParsellerimRoute
  '/pazar-yeri': typeof PazarYeriRoute
  '/profilim': typeof ProfilimRoute
  '/purchase': typeof PurchaseRoute
  '/purchase-bulk': typeof PurchaseBulkRoute
  '/sertifika-dogrula': typeof SertifikaDogrulaRoute
  '/sertifika-talep': typeof SertifikaTalepRoute
  '/sertifikalarim': typeof SertifikalarimRoute
  '/sifre-yenile': typeof SifreYenileRoute
  '/sifremi-unuttum': typeof SifremiUnuttumRoute
  '/siparislerim': typeof SiparislerimRoute
  '/turkiye-haritasi': typeof TurkiyeHaritasiRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/yonetim': typeof YonetimRoute
  '/api/earth-assets': typeof ApiEarthAssetsRoute
  '/sehir/$slug': typeof SehirSlugRoute
  '/api/shopier/checkout': typeof ApiShopierCheckoutRoute
  '/api/shopier/redirect': typeof ApiShopierRedirectRoute
  '/api/shopier/webhook': typeof ApiShopierWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-check'
    | '/ana-sayfa'
    | '/bildirimler'
    | '/cerez-politikasi'
    | '/destek'
    | '/dogrula'
    | '/giris'
    | '/gizlilik-politikasi'
    | '/gokyuzu-haritasi'
    | '/guvenlik-ayarlari'
    | '/hakkimizda'
    | '/hediye-kabul'
    | '/hediyelerim'
    | '/iade-iptal-politikasi'
    | '/iletisim'
    | '/kayit-ol'
    | '/kullanim-sartlari'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/nasil-calisir'
    | '/on-bilgilendirme-formu'
    | '/paketler'
    | '/panelim'
    | '/parsel-hatirasi'
    | '/parsel-satin-al'
    | '/parsellerim'
    | '/pazar-yeri'
    | '/profilim'
    | '/purchase'
    | '/purchase-bulk'
    | '/sertifika-dogrula'
    | '/sertifika-talep'
    | '/sertifikalarim'
    | '/sifre-yenile'
    | '/sifremi-unuttum'
    | '/siparislerim'
    | '/turkiye-haritasi'
    | '/uyelik-sozlesmesi'
    | '/yonetim'
    | '/api/earth-assets'
    | '/sehir/$slug'
    | '/api/shopier/checkout'
    | '/api/shopier/redirect'
    | '/api/shopier/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-check'
    | '/ana-sayfa'
    | '/bildirimler'
    | '/cerez-politikasi'
    | '/destek'
    | '/dogrula'
    | '/giris'
    | '/gizlilik-politikasi'
    | '/gokyuzu-haritasi'
    | '/guvenlik-ayarlari'
    | '/hakkimizda'
    | '/hediye-kabul'
    | '/hediyelerim'
    | '/iade-iptal-politikasi'
    | '/iletisim'
    | '/kayit-ol'
    | '/kullanim-sartlari'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/nasil-calisir'
    | '/on-bilgilendirme-formu'
    | '/paketler'
    | '/panelim'
    | '/parsel-hatirasi'
    | '/parsel-satin-al'
    | '/parsellerim'
    | '/pazar-yeri'
    | '/profilim'
    | '/purchase'
    | '/purchase-bulk'
    | '/sertifika-dogrula'
    | '/sertifika-talep'
    | '/sertifikalarim'
    | '/sifre-yenile'
    | '/sifremi-unuttum'
    | '/siparislerim'
    | '/turkiye-haritasi'
    | '/uyelik-sozlesmesi'
    | '/yonetim'
    | '/api/earth-assets'
    | '/sehir/$slug'
    | '/api/shopier/checkout'
    | '/api/shopier/redirect'
    | '/api/shopier/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin-check'
    | '/ana-sayfa'
    | '/bildirimler'
    | '/cerez-politikasi'
    | '/destek'
    | '/dogrula'
    | '/giris'
    | '/gizlilik-politikasi'
    | '/gokyuzu-haritasi'
    | '/guvenlik-ayarlari'
    | '/hakkimizda'
    | '/hediye-kabul'
    | '/hediyelerim'
    | '/iade-iptal-politikasi'
    | '/iletisim'
    | '/kayit-ol'
    | '/kullanim-sartlari'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/nasil-calisir'
    | '/on-bilgilendirme-formu'
    | '/paketler'
    | '/panelim'
    | '/parsel-hatirasi'
    | '/parsel-satin-al'
    | '/parsellerim'
    | '/pazar-yeri'
    | '/profilim'
    | '/purchase'
    | '/purchase-bulk'
    | '/sertifika-dogrula'
    | '/sertifika-talep'
    | '/sertifikalarim'
    | '/sifre-yenile'
    | '/sifremi-unuttum'
    | '/siparislerim'
    | '/turkiye-haritasi'
    | '/uyelik-sozlesmesi'
    | '/yonetim'
    | '/api/earth-assets'
    | '/sehir/$slug'
    | '/api/shopier/checkout'
    | '/api/shopier/redirect'
    | '/api/shopier/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCheckRoute: typeof AdminCheckRoute
  AnaSayfaRoute: typeof AnaSayfaRoute
  BildirimlerRoute: typeof BildirimlerRoute
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  DestekRoute: typeof DestekRoute
  DogrulaRoute: typeof DogrulaRoute
  GirisRoute: typeof GirisRoute
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  GokyuzuHaritasiRoute: typeof GokyuzuHaritasiRoute
  GuvenlikAyarlariRoute: typeof GuvenlikAyarlariRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HediyeKabulRoute: typeof HediyeKabulRoute
  HediyelerimRoute: typeof HediyelerimRoute
  IadeIptalPolitikasiRoute: typeof IadeIptalPolitikasiRoute
  IletisimRoute: typeof IletisimRoute
  KayitOlRoute: typeof KayitOlRoute
  KullanimSartlariRoute: typeof KullanimSartlariRoute
  KvkkRoute: typeof KvkkRoute
  MesafeliSatisSozlesmesiRoute: typeof MesafeliSatisSozlesmesiRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  OnBilgilendirmeFormuRoute: typeof OnBilgilendirmeFormuRoute
  PaketlerRoute: typeof PaketlerRoute
  PanelimRoute: typeof PanelimRoute
  ParselHatirasiRoute: typeof ParselHatirasiRoute
  ParselSatinAlRoute: typeof ParselSatinAlRoute
  ParsellerimRoute: typeof ParsellerimRoute
  PazarYeriRoute: typeof PazarYeriRoute
  ProfilimRoute: typeof ProfilimRoute
  PurchaseRoute: typeof PurchaseRoute
  PurchaseBulkRoute: typeof PurchaseBulkRoute
  SertifikaDogrulaRoute: typeof SertifikaDogrulaRoute
  SertifikaTalepRoute: typeof SertifikaTalepRoute
  SertifikalarimRoute: typeof SertifikalarimRoute
  SifreYenileRoute: typeof SifreYenileRoute
  SifremiUnuttumRoute: typeof SifremiUnuttumRoute
  SiparislerimRoute: typeof SiparislerimRoute
  TurkiyeHaritasiRoute: typeof TurkiyeHaritasiRoute
  UyelikSozlesmesiRoute: typeof UyelikSozlesmesiRoute
  YonetimRoute: typeof YonetimRoute
  ApiEarthAssetsRoute: typeof ApiEarthAssetsRoute
  SehirSlugRoute: typeof SehirSlugRoute
  ApiShopierCheckoutRoute: typeof ApiShopierCheckoutRoute
  ApiShopierRedirectRoute: typeof ApiShopierRedirectRoute
  ApiShopierWebhookRoute: typeof ApiShopierWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-check': {
      id: '/admin-check'
      path: '/admin-check'
      fullPath: '/admin-check'
      preLoaderRoute: typeof AdminCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ana-sayfa': {
      id: '/ana-sayfa'
      path: '/ana-sayfa'
      fullPath: '/ana-sayfa'
      preLoaderRoute: typeof AnaSayfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bildirimler': {
      id: '/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof BildirimlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destek': {
      id: '/destek'
      path: '/destek'
      fullPath: '/destek'
      preLoaderRoute: typeof DestekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogrula': {
      id: '/dogrula'
      path: '/dogrula'
      fullPath: '/dogrula'
      preLoaderRoute: typeof DogrulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gokyuzu-haritasi': {
      id: '/gokyuzu-haritasi'
      path: '/gokyuzu-haritasi'
      fullPath: '/gokyuzu-haritasi'
      preLoaderRoute: typeof GokyuzuHaritasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guvenlik-ayarlari': {
      id: '/guvenlik-ayarlari'
      path: '/guvenlik-ayarlari'
      fullPath: '/guvenlik-ayarlari'
      preLoaderRoute: typeof GuvenlikAyarlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hediye-kabul': {
      id: '/hediye-kabul'
      path: '/hediye-kabul'
      fullPath: '/hediye-kabul'
      preLoaderRoute: typeof HediyeKabulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hediyelerim': {
      id: '/hediyelerim'
      path: '/hediyelerim'
      fullPath: '/hediyelerim'
      preLoaderRoute: typeof HediyelerimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iade-iptal-politikasi': {
      id: '/iade-iptal-politikasi'
      path: '/iade-iptal-politikasi'
      fullPath: '/iade-iptal-politikasi'
      preLoaderRoute: typeof IadeIptalPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit-ol': {
      id: '/kayit-ol'
      path: '/kayit-ol'
      fullPath: '/kayit-ol'
      preLoaderRoute: typeof KayitOlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanim-sartlari': {
      id: '/kullanim-sartlari'
      path: '/kullanim-sartlari'
      fullPath: '/kullanim-sartlari'
      preLoaderRoute: typeof KullanimSartlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesafeli-satis-sozlesmesi': {
      id: '/mesafeli-satis-sozlesmesi'
      path: '/mesafeli-satis-sozlesmesi'
      fullPath: '/mesafeli-satis-sozlesmesi'
      preLoaderRoute: typeof MesafeliSatisSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-bilgilendirme-formu': {
      id: '/on-bilgilendirme-formu'
      path: '/on-bilgilendirme-formu'
      fullPath: '/on-bilgilendirme-formu'
      preLoaderRoute: typeof OnBilgilendirmeFormuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paketler': {
      id: '/paketler'
      path: '/paketler'
      fullPath: '/paketler'
      preLoaderRoute: typeof PaketlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panelim': {
      id: '/panelim'
      path: '/panelim'
      fullPath: '/panelim'
      preLoaderRoute: typeof PanelimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parsel-hatirasi': {
      id: '/parsel-hatirasi'
      path: '/parsel-hatirasi'
      fullPath: '/parsel-hatirasi'
      preLoaderRoute: typeof ParselHatirasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parsel-satin-al': {
      id: '/parsel-satin-al'
      path: '/parsel-satin-al'
      fullPath: '/parsel-satin-al'
      preLoaderRoute: typeof ParselSatinAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parsellerim': {
      id: '/parsellerim'
      path: '/parsellerim'
      fullPath: '/parsellerim'
      preLoaderRoute: typeof ParsellerimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazar-yeri': {
      id: '/pazar-yeri'
      path: '/pazar-yeri'
      fullPath: '/pazar-yeri'
      preLoaderRoute: typeof PazarYeriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilim': {
      id: '/profilim'
      path: '/profilim'
      fullPath: '/profilim'
      preLoaderRoute: typeof ProfilimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-bulk': {
      id: '/purchase-bulk'
      path: '/purchase-bulk'
      fullPath: '/purchase-bulk'
      preLoaderRoute: typeof PurchaseBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifika-dogrula': {
      id: '/sertifika-dogrula'
      path: '/sertifika-dogrula'
      fullPath: '/sertifika-dogrula'
      preLoaderRoute: typeof SertifikaDogrulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifika-talep': {
      id: '/sertifika-talep'
      path: '/sertifika-talep'
      fullPath: '/sertifika-talep'
      preLoaderRoute: typeof SertifikaTalepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifikalarim': {
      id: '/sertifikalarim'
      path: '/sertifikalarim'
      fullPath: '/sertifikalarim'
      preLoaderRoute: typeof SertifikalarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifre-yenile': {
      id: '/sifre-yenile'
      path: '/sifre-yenile'
      fullPath: '/sifre-yenile'
      preLoaderRoute: typeof SifreYenileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifremi-unuttum': {
      id: '/sifremi-unuttum'
      path: '/sifremi-unuttum'
      fullPath: '/sifremi-unuttum'
      preLoaderRoute: typeof SifremiUnuttumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparislerim': {
      id: '/siparislerim'
      path: '/siparislerim'
      fullPath: '/siparislerim'
      preLoaderRoute: typeof SiparislerimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turkiye-haritasi': {
      id: '/turkiye-haritasi'
      path: '/turkiye-haritasi'
      fullPath: '/turkiye-haritasi'
      preLoaderRoute: typeof TurkiyeHaritasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uyelik-sozlesmesi': {
      id: '/uyelik-sozlesmesi'
      path: '/uyelik-sozlesmesi'
      fullPath: '/uyelik-sozlesmesi'
      preLoaderRoute: typeof UyelikSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/earth-assets': {
      id: '/api/earth-assets'
      path: '/api/earth-assets'
      fullPath: '/api/earth-assets'
      preLoaderRoute: typeof ApiEarthAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sehir/$slug': {
      id: '/sehir/$slug'
      path: '/sehir/$slug'
      fullPath: '/sehir/$slug'
      preLoaderRoute: typeof SehirSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopier/checkout': {
      id: '/api/shopier/checkout'
      path: '/api/shopier/checkout'
      fullPath: '/api/shopier/checkout'
      preLoaderRoute: typeof ApiShopierCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopier/redirect': {
      id: '/api/shopier/redirect'
      path: '/api/shopier/redirect'
      fullPath: '/api/shopier/redirect'
      preLoaderRoute: typeof ApiShopierRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopier/webhook': {
      id: '/api/shopier/webhook'
      path: '/api/shopier/webhook'
      fullPath: '/api/shopier/webhook'
      preLoaderRoute: typeof ApiShopierWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCheckRoute: AdminCheckRoute,
  AnaSayfaRoute: AnaSayfaRoute,
  BildirimlerRoute: BildirimlerRoute,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  DestekRoute: DestekRoute,
  DogrulaRoute: DogrulaRoute,
  GirisRoute: GirisRoute,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  GokyuzuHaritasiRoute: GokyuzuHaritasiRoute,
  GuvenlikAyarlariRoute: GuvenlikAyarlariRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HediyeKabulRoute: HediyeKabulRoute,
  HediyelerimRoute: HediyelerimRoute,
  IadeIptalPolitikasiRoute: IadeIptalPolitikasiRoute,
  IletisimRoute: IletisimRoute,
  KayitOlRoute: KayitOlRoute,
  KullanimSartlariRoute: KullanimSartlariRoute,
  KvkkRoute: KvkkRoute,
  MesafeliSatisSozlesmesiRoute: MesafeliSatisSozlesmesiRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  OnBilgilendirmeFormuRoute: OnBilgilendirmeFormuRoute,
  PaketlerRoute: PaketlerRoute,
  PanelimRoute: PanelimRoute,
  ParselHatirasiRoute: ParselHatirasiRoute,
  ParselSatinAlRoute: ParselSatinAlRoute,
  ParsellerimRoute: ParsellerimRoute,
  PazarYeriRoute: PazarYeriRoute,
  ProfilimRoute: ProfilimRoute,
  PurchaseRoute: PurchaseRoute,
  PurchaseBulkRoute: PurchaseBulkRoute,
  SertifikaDogrulaRoute: SertifikaDogrulaRoute,
  SertifikaTalepRoute: SertifikaTalepRoute,
  SertifikalarimRoute: SertifikalarimRoute,
  SifreYenileRoute: SifreYenileRoute,
  SifremiUnuttumRoute: SifremiUnuttumRoute,
  SiparislerimRoute: SiparislerimRoute,
  TurkiyeHaritasiRoute: TurkiyeHaritasiRoute,
  UyelikSozlesmesiRoute: UyelikSozlesmesiRoute,
  YonetimRoute: YonetimRoute,
  ApiEarthAssetsRoute: ApiEarthAssetsRoute,
  SehirSlugRoute: SehirSlugRoute,
  ApiShopierCheckoutRoute: ApiShopierCheckoutRoute,
  ApiShopierRedirectRoute: ApiShopierRedirectRoute,
  ApiShopierWebhookRoute: ApiShopierWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
