name: FTP Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files via FTP
      uses: SamKirsch/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.myskyparcel.com
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        server-dir: /public_html/
